// Code generated by ent, DO NOT EDIT.

package workitem

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the workitem type in the database.
	Label = "work_item"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldRepositoryID holds the string denoting the repository_id field in the database.
	FieldRepositoryID = "repository_id"
	// FieldKind holds the string denoting the kind field in the database.
	FieldKind = "kind"
	// FieldExternalNumber holds the string denoting the external_number field in the database.
	FieldExternalNumber = "external_number"
	// FieldTitle holds the string denoting the title field in the database.
	FieldTitle = "title"
	// FieldState holds the string denoting the state field in the database.
	FieldState = "state"
	// FieldAgentOwned holds the string denoting the agent_owned field in the database.
	FieldAgentOwned = "agent_owned"
	// FieldBaseSha holds the string denoting the base_sha field in the database.
	FieldBaseSha = "base_sha"
	// FieldHeadSha holds the string denoting the head_sha field in the database.
	FieldHeadSha = "head_sha"
	// FieldBaseRef holds the string denoting the base_ref field in the database.
	FieldBaseRef = "base_ref"
	// FieldHeadRef holds the string denoting the head_ref field in the database.
	FieldHeadRef = "head_ref"
	// FieldHeadRepository holds the string denoting the head_repository field in the database.
	FieldHeadRepository = "head_repository"
	// FieldHTMLURL holds the string denoting the html_url field in the database.
	FieldHTMLURL = "html_url"
	// FieldContextVersion holds the string denoting the context_version field in the database.
	FieldContextVersion = "context_version"
	// FieldClosedAt holds the string denoting the closed_at field in the database.
	FieldClosedAt = "closed_at"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// Table holds the table name of the workitem in the database.
	Table = "work_items"
)

// Columns holds all SQL columns for workitem fields.
var Columns = []string{
	FieldID,
	FieldRepositoryID,
	FieldKind,
	FieldExternalNumber,
	FieldTitle,
	FieldState,
	FieldAgentOwned,
	FieldBaseSha,
	FieldHeadSha,
	FieldBaseRef,
	FieldHeadRef,
	FieldHeadRepository,
	FieldHTMLURL,
	FieldContextVersion,
	FieldClosedAt,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultTitle holds the default value on creation for the "title" field.
	DefaultTitle string
	// DefaultState holds the default value on creation for the "state" field.
	DefaultState string
	// DefaultAgentOwned holds the default value on creation for the "agent_owned" field.
	DefaultAgentOwned bool
	// DefaultContextVersion holds the default value on creation for the "context_version" field.
	DefaultContextVersion int64
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)

// OrderOption defines the ordering options for the WorkItem queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByRepositoryID orders the results by the repository_id field.
func ByRepositoryID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRepositoryID, opts...).ToFunc()
}

// ByKind orders the results by the kind field.
func ByKind(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldKind, opts...).ToFunc()
}

// ByExternalNumber orders the results by the external_number field.
func ByExternalNumber(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldExternalNumber, opts...).ToFunc()
}

// ByTitle orders the results by the title field.
func ByTitle(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTitle, opts...).ToFunc()
}

// ByState orders the results by the state field.
func ByState(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldState, opts...).ToFunc()
}

// ByAgentOwned orders the results by the agent_owned field.
func ByAgentOwned(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAgentOwned, opts...).ToFunc()
}

// ByBaseSha orders the results by the base_sha field.
func ByBaseSha(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBaseSha, opts...).ToFunc()
}

// ByHeadSha orders the results by the head_sha field.
func ByHeadSha(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldHeadSha, opts...).ToFunc()
}

// ByBaseRef orders the results by the base_ref field.
func ByBaseRef(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBaseRef, opts...).ToFunc()
}

// ByHeadRef orders the results by the head_ref field.
func ByHeadRef(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldHeadRef, opts...).ToFunc()
}

// ByHeadRepository orders the results by the head_repository field.
func ByHeadRepository(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldHeadRepository, opts...).ToFunc()
}

// ByHTMLURL orders the results by the html_url field.
func ByHTMLURL(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldHTMLURL, opts...).ToFunc()
}

// ByContextVersion orders the results by the context_version field.
func ByContextVersion(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldContextVersion, opts...).ToFunc()
}

// ByClosedAt orders the results by the closed_at field.
func ByClosedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldClosedAt, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}
