// Code generated by ent, DO NOT EDIT.

package codexthreadcontrol

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the codexthreadcontrol type in the database.
	Label = "codex_thread_control"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldSourceType holds the string denoting the source_type field in the database.
	FieldSourceType = "source_type"
	// FieldWorkItemID holds the string denoting the work_item_id field in the database.
	FieldWorkItemID = "work_item_id"
	// FieldDiscordConversationID holds the string denoting the discord_conversation_id field in the database.
	FieldDiscordConversationID = "discord_conversation_id"
	// FieldRepositoryID holds the string denoting the repository_id field in the database.
	FieldRepositoryID = "repository_id"
	// FieldAgentProfileID holds the string denoting the agent_profile_id field in the database.
	FieldAgentProfileID = "agent_profile_id"
	// FieldContextVersion holds the string denoting the context_version field in the database.
	FieldContextVersion = "context_version"
	// FieldExecutionNodeID holds the string denoting the execution_node_id field in the database.
	FieldExecutionNodeID = "execution_node_id"
	// FieldExternalThreadID holds the string denoting the external_thread_id field in the database.
	FieldExternalThreadID = "external_thread_id"
	// FieldProvider holds the string denoting the provider field in the database.
	FieldProvider = "provider"
	// FieldCodexHomeKey holds the string denoting the codex_home_key field in the database.
	FieldCodexHomeKey = "codex_home_key"
	// FieldProviderSignature holds the string denoting the provider_signature field in the database.
	FieldProviderSignature = "provider_signature"
	// FieldThreadGeneration holds the string denoting the thread_generation field in the database.
	FieldThreadGeneration = "thread_generation"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldNextSequenceNo holds the string denoting the next_sequence_no field in the database.
	FieldNextSequenceNo = "next_sequence_no"
	// FieldActiveIntentID holds the string denoting the active_intent_id field in the database.
	FieldActiveIntentID = "active_intent_id"
	// FieldRemoteStatus holds the string denoting the remote_status field in the database.
	FieldRemoteStatus = "remote_status"
	// FieldActiveCodexTurnID holds the string denoting the active_codex_turn_id field in the database.
	FieldActiveCodexTurnID = "active_codex_turn_id"
	// FieldActiveClientID holds the string denoting the active_client_id field in the database.
	FieldActiveClientID = "active_client_id"
	// FieldLeaseEpoch holds the string denoting the lease_epoch field in the database.
	FieldLeaseEpoch = "lease_epoch"
	// FieldLeaseExpiresAt holds the string denoting the lease_expires_at field in the database.
	FieldLeaseExpiresAt = "lease_expires_at"
	// FieldHeartbeatAt holds the string denoting the heartbeat_at field in the database.
	FieldHeartbeatAt = "heartbeat_at"
	// FieldLastReconciledAt holds the string denoting the last_reconciled_at field in the database.
	FieldLastReconciledAt = "last_reconciled_at"
	// FieldNextWakeupAt holds the string denoting the next_wakeup_at field in the database.
	FieldNextWakeupAt = "next_wakeup_at"
	// FieldWorkerID holds the string denoting the worker_id field in the database.
	FieldWorkerID = "worker_id"
	// FieldLeaseToken holds the string denoting the lease_token field in the database.
	FieldLeaseToken = "lease_token"
	// FieldLastErrorCode holds the string denoting the last_error_code field in the database.
	FieldLastErrorCode = "last_error_code"
	// FieldLastErrorMessage holds the string denoting the last_error_message field in the database.
	FieldLastErrorMessage = "last_error_message"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// Table holds the table name of the codexthreadcontrol in the database.
	Table = "codex_thread_controls"
)

// Columns holds all SQL columns for codexthreadcontrol fields.
var Columns = []string{
	FieldID,
	FieldSourceType,
	FieldWorkItemID,
	FieldDiscordConversationID,
	FieldRepositoryID,
	FieldAgentProfileID,
	FieldContextVersion,
	FieldExecutionNodeID,
	FieldExternalThreadID,
	FieldProvider,
	FieldCodexHomeKey,
	FieldProviderSignature,
	FieldThreadGeneration,
	FieldStatus,
	FieldNextSequenceNo,
	FieldActiveIntentID,
	FieldRemoteStatus,
	FieldActiveCodexTurnID,
	FieldActiveClientID,
	FieldLeaseEpoch,
	FieldLeaseExpiresAt,
	FieldHeartbeatAt,
	FieldLastReconciledAt,
	FieldNextWakeupAt,
	FieldWorkerID,
	FieldLeaseToken,
	FieldLastErrorCode,
	FieldLastErrorMessage,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultProvider holds the default value on creation for the "provider" field.
	DefaultProvider string
	// DefaultThreadGeneration holds the default value on creation for the "thread_generation" field.
	DefaultThreadGeneration int
	// DefaultStatus holds the default value on creation for the "status" field.
	DefaultStatus string
	// DefaultNextSequenceNo holds the default value on creation for the "next_sequence_no" field.
	DefaultNextSequenceNo int64
	// DefaultLeaseEpoch holds the default value on creation for the "lease_epoch" field.
	DefaultLeaseEpoch int64
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)

// OrderOption defines the ordering options for the CodexThreadControl queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// BySourceType orders the results by the source_type field.
func BySourceType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSourceType, opts...).ToFunc()
}

// ByWorkItemID orders the results by the work_item_id field.
func ByWorkItemID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldWorkItemID, opts...).ToFunc()
}

// ByDiscordConversationID orders the results by the discord_conversation_id field.
func ByDiscordConversationID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDiscordConversationID, opts...).ToFunc()
}

// ByRepositoryID orders the results by the repository_id field.
func ByRepositoryID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRepositoryID, opts...).ToFunc()
}

// ByAgentProfileID orders the results by the agent_profile_id field.
func ByAgentProfileID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAgentProfileID, opts...).ToFunc()
}

// ByContextVersion orders the results by the context_version field.
func ByContextVersion(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldContextVersion, opts...).ToFunc()
}

// ByExecutionNodeID orders the results by the execution_node_id field.
func ByExecutionNodeID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldExecutionNodeID, opts...).ToFunc()
}

// ByExternalThreadID orders the results by the external_thread_id field.
func ByExternalThreadID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldExternalThreadID, opts...).ToFunc()
}

// ByProvider orders the results by the provider field.
func ByProvider(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldProvider, opts...).ToFunc()
}

// ByCodexHomeKey orders the results by the codex_home_key field.
func ByCodexHomeKey(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCodexHomeKey, opts...).ToFunc()
}

// ByProviderSignature orders the results by the provider_signature field.
func ByProviderSignature(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldProviderSignature, opts...).ToFunc()
}

// ByThreadGeneration orders the results by the thread_generation field.
func ByThreadGeneration(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldThreadGeneration, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// ByNextSequenceNo orders the results by the next_sequence_no field.
func ByNextSequenceNo(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldNextSequenceNo, opts...).ToFunc()
}

// ByActiveIntentID orders the results by the active_intent_id field.
func ByActiveIntentID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldActiveIntentID, opts...).ToFunc()
}

// ByRemoteStatus orders the results by the remote_status field.
func ByRemoteStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRemoteStatus, opts...).ToFunc()
}

// ByActiveCodexTurnID orders the results by the active_codex_turn_id field.
func ByActiveCodexTurnID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldActiveCodexTurnID, opts...).ToFunc()
}

// ByActiveClientID orders the results by the active_client_id field.
func ByActiveClientID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldActiveClientID, opts...).ToFunc()
}

// ByLeaseEpoch orders the results by the lease_epoch field.
func ByLeaseEpoch(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLeaseEpoch, opts...).ToFunc()
}

// ByLeaseExpiresAt orders the results by the lease_expires_at field.
func ByLeaseExpiresAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLeaseExpiresAt, opts...).ToFunc()
}

// ByHeartbeatAt orders the results by the heartbeat_at field.
func ByHeartbeatAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldHeartbeatAt, opts...).ToFunc()
}

// ByLastReconciledAt orders the results by the last_reconciled_at field.
func ByLastReconciledAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLastReconciledAt, opts...).ToFunc()
}

// ByNextWakeupAt orders the results by the next_wakeup_at field.
func ByNextWakeupAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldNextWakeupAt, opts...).ToFunc()
}

// ByWorkerID orders the results by the worker_id field.
func ByWorkerID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldWorkerID, opts...).ToFunc()
}

// ByLeaseToken orders the results by the lease_token field.
func ByLeaseToken(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLeaseToken, opts...).ToFunc()
}

// ByLastErrorCode orders the results by the last_error_code field.
func ByLastErrorCode(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLastErrorCode, opts...).ToFunc()
}

// ByLastErrorMessage orders the results by the last_error_message field.
func ByLastErrorMessage(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLastErrorMessage, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}
