// Code generated by ent, DO NOT EDIT.

package codexthreadcontrol

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
	"github.com/slovx2/tyrs-hand/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.CodexThreadControl {
	return predicate.CodexThreadControl(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.CodexThreadControl {
	return predicate.CodexThreadControl(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.CodexThreadControl {
	return predicate.CodexThreadControl(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.CodexThreadControl {
	return predicate.CodexThreadControl(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.CodexThreadControl {
	return predicate.CodexThreadControl(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.CodexThreadControl {
	return predicate.CodexThreadControl(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.CodexThreadControl {
	return predicate.CodexThreadControl(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.CodexThreadControl {
	return predicate.CodexThreadControl(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.CodexThreadControl {
	return predicate.CodexThreadControl(sql.FieldLTE(FieldID, id))
}

// SourceType applies equality check predicate on the "source_type" field. It's identical to SourceTypeEQ.
func SourceType(v string) predicate.CodexThreadControl {
	return predicate.CodexThreadControl(sql.FieldEQ(FieldSourceType, v))
}

// WorkItemID applies equality check predicate on the "work_item_id" field. It's identical to WorkItemIDEQ.
func WorkItemID(v uuid.UUID) predicate.CodexThreadControl {
	return predicate.CodexThreadControl(sql.FieldEQ(FieldWorkItemID, v))
}

// DiscordConversationID applies equality check predicate on the "discord_conversation_id" field. It's identical to DiscordConversationIDEQ.
func DiscordConversationID(v uuid.UUID) predicate.CodexThreadControl {
	return predicate.CodexThreadControl(sql.FieldEQ(FieldDiscordConversationID, v))
}

// RepositoryID applies equality check predicate on the "repository_id" field. It's identical to RepositoryIDEQ.
func RepositoryID(v uuid.UUID) predicate.CodexThreadControl {
	return predicate.CodexThreadControl(sql.FieldEQ(FieldRepositoryID, v))
}

// AgentProfileID applies equality check predicate on the "agent_profile_id" field. It's identical to AgentProfileIDEQ.
func AgentProfileID(v uuid.UUID) predicate.CodexThreadControl {
	return predicate.CodexThreadControl(sql.FieldEQ(FieldAgentProfileID, v))
}

// ExecutionNodeID applies equality check predicate on the "execution_node_id" field. It's identical to ExecutionNodeIDEQ.
func ExecutionNodeID(v uuid.UUID) predicate.CodexThreadControl {
	return predicate.CodexThreadControl(sql.FieldEQ(FieldExecutionNodeID, v))
}

// ExternalThreadID applies equality check predicate on the "external_thread_id" field. It's identical to ExternalThreadIDEQ.
func ExternalThreadID(v string) predicate.CodexThreadControl {
	return predicate.CodexThreadControl(sql.FieldEQ(FieldExternalThreadID, v))
}

// CodexHomeKey applies equality check predicate on the "codex_home_key" field. It's identical to CodexHomeKeyEQ.
func CodexHomeKey(v string) predicate.CodexThreadControl {
	return predicate.CodexThreadControl(sql.FieldEQ(FieldCodexHomeKey, v))
}

// Status applies equality check predicate on the "status" field. It's identical to StatusEQ.
func Status(v string) predicate.CodexThreadControl {
	return predicate.CodexThreadControl(sql.FieldEQ(FieldStatus, v))
}

// NextSequenceNo applies equality check predicate on the "next_sequence_no" field. It's identical to NextSequenceNoEQ.
func NextSequenceNo(v int64) predicate.CodexThreadControl {
	return predicate.CodexThreadControl(sql.FieldEQ(FieldNextSequenceNo, v))
}

// ActiveIntentID applies equality check predicate on the "active_intent_id" field. It's identical to ActiveIntentIDEQ.
func ActiveIntentID(v uuid.UUID) predicate.CodexThreadControl {
	return predicate.CodexThreadControl(sql.FieldEQ(FieldActiveIntentID, v))
}

// RemoteStatus applies equality check predicate on the "remote_status" field. It's identical to RemoteStatusEQ.
func RemoteStatus(v string) predicate.CodexThreadControl {
	return predicate.CodexThreadControl(sql.FieldEQ(FieldRemoteStatus, v))
}

// ActiveCodexTurnID applies equality check predicate on the "active_codex_turn_id" field. It's identical to ActiveCodexTurnIDEQ.
func ActiveCodexTurnID(v string) predicate.CodexThreadControl {
	return predicate.CodexThreadControl(sql.FieldEQ(FieldActiveCodexTurnID, v))
}

// ActiveClientID applies equality check predicate on the "active_client_id" field. It's identical to ActiveClientIDEQ.
func ActiveClientID(v string) predicate.CodexThreadControl {
	return predicate.CodexThreadControl(sql.FieldEQ(FieldActiveClientID, v))
}

// LeaseEpoch applies equality check predicate on the "lease_epoch" field. It's identical to LeaseEpochEQ.
func LeaseEpoch(v int64) predicate.CodexThreadControl {
	return predicate.CodexThreadControl(sql.FieldEQ(FieldLeaseEpoch, v))
}

// LeaseExpiresAt applies equality check predicate on the "lease_expires_at" field. It's identical to LeaseExpiresAtEQ.
func LeaseExpiresAt(v time.Time) predicate.CodexThreadControl {
	return predicate.CodexThreadControl(sql.FieldEQ(FieldLeaseExpiresAt, v))
}

// HeartbeatAt applies equality check predicate on the "heartbeat_at" field. It's identical to HeartbeatAtEQ.
func HeartbeatAt(v time.Time) predicate.CodexThreadControl {
	return predicate.CodexThreadControl(sql.FieldEQ(FieldHeartbeatAt, v))
}

// LastReconciledAt applies equality check predicate on the "last_reconciled_at" field. It's identical to LastReconciledAtEQ.
func LastReconciledAt(v time.Time) predicate.CodexThreadControl {
	return predicate.CodexThreadControl(sql.FieldEQ(FieldLastReconciledAt, v))
}

// NextWakeupAt applies equality check predicate on the "next_wakeup_at" field. It's identical to NextWakeupAtEQ.
func NextWakeupAt(v time.Time) predicate.CodexThreadControl {
	return predicate.CodexThreadControl(sql.FieldEQ(FieldNextWakeupAt, v))
}

// WorkerID applies equality check predicate on the "worker_id" field. It's identical to WorkerIDEQ.
func WorkerID(v string) predicate.CodexThreadControl {
	return predicate.CodexThreadControl(sql.FieldEQ(FieldWorkerID, v))
}

// LeaseToken applies equality check predicate on the "lease_token" field. It's identical to LeaseTokenEQ.
func LeaseToken(v string) predicate.CodexThreadControl {
	return predicate.CodexThreadControl(sql.FieldEQ(FieldLeaseToken, v))
}

// LastErrorCode applies equality check predicate on the "last_error_code" field. It's identical to LastErrorCodeEQ.
func LastErrorCode(v string) predicate.CodexThreadControl {
	return predicate.CodexThreadControl(sql.FieldEQ(FieldLastErrorCode, v))
}

// LastErrorMessage applies equality check predicate on the "last_error_message" field. It's identical to LastErrorMessageEQ.
func LastErrorMessage(v string) predicate.CodexThreadControl {
	return predicate.CodexThreadControl(sql.FieldEQ(FieldLastErrorMessage, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.CodexThreadControl {
	return predicate.CodexThreadControl(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.CodexThreadControl {
	return predicate.CodexThreadControl(sql.FieldEQ(FieldUpdatedAt, v))
}

// SourceTypeEQ applies the EQ predicate on the "source_type" field.
func SourceTypeEQ(v string) predicate.CodexThreadControl {
	return predicate.CodexThreadControl(sql.FieldEQ(FieldSourceType, v))
}

// SourceTypeNEQ applies the NEQ predicate on the "source_type" field.
func SourceTypeNEQ(v string) predicate.CodexThreadControl {
	return predicate.CodexThreadControl(sql.FieldNEQ(FieldSourceType, v))
}

// SourceTypeIn applies the In predicate on the "source_type" field.
func SourceTypeIn(vs ...string) predicate.CodexThreadControl {
	return predicate.CodexThreadControl(sql.FieldIn(FieldSourceType, vs...))
}

// SourceTypeNotIn applies the NotIn predicate on the "source_type" field.
func SourceTypeNotIn(vs ...string) predicate.CodexThreadControl {
	return predicate.CodexThreadControl(sql.FieldNotIn(FieldSourceType, vs...))
}

// SourceTypeGT applies the GT predicate on the "source_type" field.
func SourceTypeGT(v string) predicate.CodexThreadControl {
	return predicate.CodexThreadControl(sql.FieldGT(FieldSourceType, v))
}

// SourceTypeGTE applies the GTE predicate on the "source_type" field.
func SourceTypeGTE(v string) predicate.CodexThreadControl {
	return predicate.CodexThreadControl(sql.FieldGTE(FieldSourceType, v))
}

// SourceTypeLT applies the LT predicate on the "source_type" field.
func SourceTypeLT(v string) predicate.CodexThreadControl {
	return predicate.CodexThreadControl(sql.FieldLT(FieldSourceType, v))
}

// SourceTypeLTE applies the LTE predicate on the "source_type" field.
func SourceTypeLTE(v string) predicate.CodexThreadControl {
	return predicate.CodexThreadControl(sql.FieldLTE(FieldSourceType, v))
}

// SourceTypeContains applies the Contains predicate on the "source_type" field.
func SourceTypeContains(v string) predicate.CodexThreadControl {
	return predicate.CodexThreadControl(sql.FieldContains(FieldSourceType, v))
}

// SourceTypeHasPrefix applies the HasPrefix predicate on the "source_type" field.
func SourceTypeHasPrefix(v string) predicate.CodexThreadControl {
	return predicate.CodexThreadControl(sql.FieldHasPrefix(FieldSourceType, v))
}

// SourceTypeHasSuffix applies the HasSuffix predicate on the "source_type" field.
func SourceTypeHasSuffix(v string) predicate.CodexThreadControl {
	return predicate.CodexThreadControl(sql.FieldHasSuffix(FieldSourceType, v))
}

// SourceTypeEqualFold applies the EqualFold predicate on the "source_type" field.
func SourceTypeEqualFold(v string) predicate.CodexThreadControl {
	return predicate.CodexThreadControl(sql.FieldEqualFold(FieldSourceType, v))
}

// SourceTypeContainsFold applies the ContainsFold predicate on the "source_type" field.
func SourceTypeContainsFold(v string) predicate.CodexThreadControl {
	return predicate.CodexThreadControl(sql.FieldContainsFold(FieldSourceType, v))
}

// WorkItemIDEQ applies the EQ predicate on the "work_item_id" field.
func WorkItemIDEQ(v uuid.UUID) predicate.CodexThreadControl {
	return predicate.CodexThreadControl(sql.FieldEQ(FieldWorkItemID, v))
}

// WorkItemIDNEQ applies the NEQ predicate on the "work_item_id" field.
func WorkItemIDNEQ(v uuid.UUID) predicate.CodexThreadControl {
	return predicate.CodexThreadControl(sql.FieldNEQ(FieldWorkItemID, v))
}

// WorkItemIDIn applies the In predicate on the "work_item_id" field.
func WorkItemIDIn(vs ...uuid.UUID) predicate.CodexThreadControl {
	return predicate.CodexThreadControl(sql.FieldIn(FieldWorkItemID, vs...))
}

// WorkItemIDNotIn applies the NotIn predicate on the "work_item_id" field.
func WorkItemIDNotIn(vs ...uuid.UUID) predicate.CodexThreadControl {
	return predicate.CodexThreadControl(sql.FieldNotIn(FieldWorkItemID, vs...))
}

// WorkItemIDGT applies the GT predicate on the "work_item_id" field.
func WorkItemIDGT(v uuid.UUID) predicate.CodexThreadControl {
	return predicate.CodexThreadControl(sql.FieldGT(FieldWorkItemID, v))
}

// WorkItemIDGTE applies the GTE predicate on the "work_item_id" field.
func WorkItemIDGTE(v uuid.UUID) predicate.CodexThreadControl {
	return predicate.CodexThreadControl(sql.FieldGTE(FieldWorkItemID, v))
}

// WorkItemIDLT applies the LT predicate on the "work_item_id" field.
func WorkItemIDLT(v uuid.UUID) predicate.CodexThreadControl {
	return predicate.CodexThreadControl(sql.FieldLT(FieldWorkItemID, v))
}

// WorkItemIDLTE applies the LTE predicate on the "work_item_id" field.
func WorkItemIDLTE(v uuid.UUID) predicate.CodexThreadControl {
	return predicate.CodexThreadControl(sql.FieldLTE(FieldWorkItemID, v))
}

// WorkItemIDIsNil applies the IsNil predicate on the "work_item_id" field.
func WorkItemIDIsNil() predicate.CodexThreadControl {
	return predicate.CodexThreadControl(sql.FieldIsNull(FieldWorkItemID))
}

// WorkItemIDNotNil applies the NotNil predicate on the "work_item_id" field.
func WorkItemIDNotNil() predicate.CodexThreadControl {
	return predicate.CodexThreadControl(sql.FieldNotNull(FieldWorkItemID))
}

// DiscordConversationIDEQ applies the EQ predicate on the "discord_conversation_id" field.
func DiscordConversationIDEQ(v uuid.UUID) predicate.CodexThreadControl {
	return predicate.CodexThreadControl(sql.FieldEQ(FieldDiscordConversationID, v))
}

// DiscordConversationIDNEQ applies the NEQ predicate on the "discord_conversation_id" field.
func DiscordConversationIDNEQ(v uuid.UUID) predicate.CodexThreadControl {
	return predicate.CodexThreadControl(sql.FieldNEQ(FieldDiscordConversationID, v))
}

// DiscordConversationIDIn applies the In predicate on the "discord_conversation_id" field.
func DiscordConversationIDIn(vs ...uuid.UUID) predicate.CodexThreadControl {
	return predicate.CodexThreadControl(sql.FieldIn(FieldDiscordConversationID, vs...))
}

// DiscordConversationIDNotIn applies the NotIn predicate on the "discord_conversation_id" field.
func DiscordConversationIDNotIn(vs ...uuid.UUID) predicate.CodexThreadControl {
	return predicate.CodexThreadControl(sql.FieldNotIn(FieldDiscordConversationID, vs...))
}

// DiscordConversationIDGT applies the GT predicate on the "discord_conversation_id" field.
func DiscordConversationIDGT(v uuid.UUID) predicate.CodexThreadControl {
	return predicate.CodexThreadControl(sql.FieldGT(FieldDiscordConversationID, v))
}

// DiscordConversationIDGTE applies the GTE predicate on the "discord_conversation_id" field.
func DiscordConversationIDGTE(v uuid.UUID) predicate.CodexThreadControl {
	return predicate.CodexThreadControl(sql.FieldGTE(FieldDiscordConversationID, v))
}

// DiscordConversationIDLT applies the LT predicate on the "discord_conversation_id" field.
func DiscordConversationIDLT(v uuid.UUID) predicate.CodexThreadControl {
	return predicate.CodexThreadControl(sql.FieldLT(FieldDiscordConversationID, v))
}

// DiscordConversationIDLTE applies the LTE predicate on the "discord_conversation_id" field.
func DiscordConversationIDLTE(v uuid.UUID) predicate.CodexThreadControl {
	return predicate.CodexThreadControl(sql.FieldLTE(FieldDiscordConversationID, v))
}

// DiscordConversationIDIsNil applies the IsNil predicate on the "discord_conversation_id" field.
func DiscordConversationIDIsNil() predicate.CodexThreadControl {
	return predicate.CodexThreadControl(sql.FieldIsNull(FieldDiscordConversationID))
}

// DiscordConversationIDNotNil applies the NotNil predicate on the "discord_conversation_id" field.
func DiscordConversationIDNotNil() predicate.CodexThreadControl {
	return predicate.CodexThreadControl(sql.FieldNotNull(FieldDiscordConversationID))
}

// RepositoryIDEQ applies the EQ predicate on the "repository_id" field.
func RepositoryIDEQ(v uuid.UUID) predicate.CodexThreadControl {
	return predicate.CodexThreadControl(sql.FieldEQ(FieldRepositoryID, v))
}

// RepositoryIDNEQ applies the NEQ predicate on the "repository_id" field.
func RepositoryIDNEQ(v uuid.UUID) predicate.CodexThreadControl {
	return predicate.CodexThreadControl(sql.FieldNEQ(FieldRepositoryID, v))
}

// RepositoryIDIn applies the In predicate on the "repository_id" field.
func RepositoryIDIn(vs ...uuid.UUID) predicate.CodexThreadControl {
	return predicate.CodexThreadControl(sql.FieldIn(FieldRepositoryID, vs...))
}

// RepositoryIDNotIn applies the NotIn predicate on the "repository_id" field.
func RepositoryIDNotIn(vs ...uuid.UUID) predicate.CodexThreadControl {
	return predicate.CodexThreadControl(sql.FieldNotIn(FieldRepositoryID, vs...))
}

// RepositoryIDGT applies the GT predicate on the "repository_id" field.
func RepositoryIDGT(v uuid.UUID) predicate.CodexThreadControl {
	return predicate.CodexThreadControl(sql.FieldGT(FieldRepositoryID, v))
}

// RepositoryIDGTE applies the GTE predicate on the "repository_id" field.
func RepositoryIDGTE(v uuid.UUID) predicate.CodexThreadControl {
	return predicate.CodexThreadControl(sql.FieldGTE(FieldRepositoryID, v))
}

// RepositoryIDLT applies the LT predicate on the "repository_id" field.
func RepositoryIDLT(v uuid.UUID) predicate.CodexThreadControl {
	return predicate.CodexThreadControl(sql.FieldLT(FieldRepositoryID, v))
}

// RepositoryIDLTE applies the LTE predicate on the "repository_id" field.
func RepositoryIDLTE(v uuid.UUID) predicate.CodexThreadControl {
	return predicate.CodexThreadControl(sql.FieldLTE(FieldRepositoryID, v))
}

// RepositoryIDIsNil applies the IsNil predicate on the "repository_id" field.
func RepositoryIDIsNil() predicate.CodexThreadControl {
	return predicate.CodexThreadControl(sql.FieldIsNull(FieldRepositoryID))
}

// RepositoryIDNotNil applies the NotNil predicate on the "repository_id" field.
func RepositoryIDNotNil() predicate.CodexThreadControl {
	return predicate.CodexThreadControl(sql.FieldNotNull(FieldRepositoryID))
}

// AgentProfileIDEQ applies the EQ predicate on the "agent_profile_id" field.
func AgentProfileIDEQ(v uuid.UUID) predicate.CodexThreadControl {
	return predicate.CodexThreadControl(sql.FieldEQ(FieldAgentProfileID, v))
}

// AgentProfileIDNEQ applies the NEQ predicate on the "agent_profile_id" field.
func AgentProfileIDNEQ(v uuid.UUID) predicate.CodexThreadControl {
	return predicate.CodexThreadControl(sql.FieldNEQ(FieldAgentProfileID, v))
}

// AgentProfileIDIn applies the In predicate on the "agent_profile_id" field.
func AgentProfileIDIn(vs ...uuid.UUID) predicate.CodexThreadControl {
	return predicate.CodexThreadControl(sql.FieldIn(FieldAgentProfileID, vs...))
}

// AgentProfileIDNotIn applies the NotIn predicate on the "agent_profile_id" field.
func AgentProfileIDNotIn(vs ...uuid.UUID) predicate.CodexThreadControl {
	return predicate.CodexThreadControl(sql.FieldNotIn(FieldAgentProfileID, vs...))
}

// AgentProfileIDGT applies the GT predicate on the "agent_profile_id" field.
func AgentProfileIDGT(v uuid.UUID) predicate.CodexThreadControl {
	return predicate.CodexThreadControl(sql.FieldGT(FieldAgentProfileID, v))
}

// AgentProfileIDGTE applies the GTE predicate on the "agent_profile_id" field.
func AgentProfileIDGTE(v uuid.UUID) predicate.CodexThreadControl {
	return predicate.CodexThreadControl(sql.FieldGTE(FieldAgentProfileID, v))
}

// AgentProfileIDLT applies the LT predicate on the "agent_profile_id" field.
func AgentProfileIDLT(v uuid.UUID) predicate.CodexThreadControl {
	return predicate.CodexThreadControl(sql.FieldLT(FieldAgentProfileID, v))
}

// AgentProfileIDLTE applies the LTE predicate on the "agent_profile_id" field.
func AgentProfileIDLTE(v uuid.UUID) predicate.CodexThreadControl {
	return predicate.CodexThreadControl(sql.FieldLTE(FieldAgentProfileID, v))
}

// ExecutionNodeIDEQ applies the EQ predicate on the "execution_node_id" field.
func ExecutionNodeIDEQ(v uuid.UUID) predicate.CodexThreadControl {
	return predicate.CodexThreadControl(sql.FieldEQ(FieldExecutionNodeID, v))
}

// ExecutionNodeIDNEQ applies the NEQ predicate on the "execution_node_id" field.
func ExecutionNodeIDNEQ(v uuid.UUID) predicate.CodexThreadControl {
	return predicate.CodexThreadControl(sql.FieldNEQ(FieldExecutionNodeID, v))
}

// ExecutionNodeIDIn applies the In predicate on the "execution_node_id" field.
func ExecutionNodeIDIn(vs ...uuid.UUID) predicate.CodexThreadControl {
	return predicate.CodexThreadControl(sql.FieldIn(FieldExecutionNodeID, vs...))
}

// ExecutionNodeIDNotIn applies the NotIn predicate on the "execution_node_id" field.
func ExecutionNodeIDNotIn(vs ...uuid.UUID) predicate.CodexThreadControl {
	return predicate.CodexThreadControl(sql.FieldNotIn(FieldExecutionNodeID, vs...))
}

// ExecutionNodeIDGT applies the GT predicate on the "execution_node_id" field.
func ExecutionNodeIDGT(v uuid.UUID) predicate.CodexThreadControl {
	return predicate.CodexThreadControl(sql.FieldGT(FieldExecutionNodeID, v))
}

// ExecutionNodeIDGTE applies the GTE predicate on the "execution_node_id" field.
func ExecutionNodeIDGTE(v uuid.UUID) predicate.CodexThreadControl {
	return predicate.CodexThreadControl(sql.FieldGTE(FieldExecutionNodeID, v))
}

// ExecutionNodeIDLT applies the LT predicate on the "execution_node_id" field.
func ExecutionNodeIDLT(v uuid.UUID) predicate.CodexThreadControl {
	return predicate.CodexThreadControl(sql.FieldLT(FieldExecutionNodeID, v))
}

// ExecutionNodeIDLTE applies the LTE predicate on the "execution_node_id" field.
func ExecutionNodeIDLTE(v uuid.UUID) predicate.CodexThreadControl {
	return predicate.CodexThreadControl(sql.FieldLTE(FieldExecutionNodeID, v))
}

// ExecutionNodeIDIsNil applies the IsNil predicate on the "execution_node_id" field.
func ExecutionNodeIDIsNil() predicate.CodexThreadControl {
	return predicate.CodexThreadControl(sql.FieldIsNull(FieldExecutionNodeID))
}

// ExecutionNodeIDNotNil applies the NotNil predicate on the "execution_node_id" field.
func ExecutionNodeIDNotNil() predicate.CodexThreadControl {
	return predicate.CodexThreadControl(sql.FieldNotNull(FieldExecutionNodeID))
}

// ExternalThreadIDEQ applies the EQ predicate on the "external_thread_id" field.
func ExternalThreadIDEQ(v string) predicate.CodexThreadControl {
	return predicate.CodexThreadControl(sql.FieldEQ(FieldExternalThreadID, v))
}

// ExternalThreadIDNEQ applies the NEQ predicate on the "external_thread_id" field.
func ExternalThreadIDNEQ(v string) predicate.CodexThreadControl {
	return predicate.CodexThreadControl(sql.FieldNEQ(FieldExternalThreadID, v))
}

// ExternalThreadIDIn applies the In predicate on the "external_thread_id" field.
func ExternalThreadIDIn(vs ...string) predicate.CodexThreadControl {
	return predicate.CodexThreadControl(sql.FieldIn(FieldExternalThreadID, vs...))
}

// ExternalThreadIDNotIn applies the NotIn predicate on the "external_thread_id" field.
func ExternalThreadIDNotIn(vs ...string) predicate.CodexThreadControl {
	return predicate.CodexThreadControl(sql.FieldNotIn(FieldExternalThreadID, vs...))
}

// ExternalThreadIDGT applies the GT predicate on the "external_thread_id" field.
func ExternalThreadIDGT(v string) predicate.CodexThreadControl {
	return predicate.CodexThreadControl(sql.FieldGT(FieldExternalThreadID, v))
}

// ExternalThreadIDGTE applies the GTE predicate on the "external_thread_id" field.
func ExternalThreadIDGTE(v string) predicate.CodexThreadControl {
	return predicate.CodexThreadControl(sql.FieldGTE(FieldExternalThreadID, v))
}

// ExternalThreadIDLT applies the LT predicate on the "external_thread_id" field.
func ExternalThreadIDLT(v string) predicate.CodexThreadControl {
	return predicate.CodexThreadControl(sql.FieldLT(FieldExternalThreadID, v))
}

// ExternalThreadIDLTE applies the LTE predicate on the "external_thread_id" field.
func ExternalThreadIDLTE(v string) predicate.CodexThreadControl {
	return predicate.CodexThreadControl(sql.FieldLTE(FieldExternalThreadID, v))
}

// ExternalThreadIDContains applies the Contains predicate on the "external_thread_id" field.
func ExternalThreadIDContains(v string) predicate.CodexThreadControl {
	return predicate.CodexThreadControl(sql.FieldContains(FieldExternalThreadID, v))
}

// ExternalThreadIDHasPrefix applies the HasPrefix predicate on the "external_thread_id" field.
func ExternalThreadIDHasPrefix(v string) predicate.CodexThreadControl {
	return predicate.CodexThreadControl(sql.FieldHasPrefix(FieldExternalThreadID, v))
}

// ExternalThreadIDHasSuffix applies the HasSuffix predicate on the "external_thread_id" field.
func ExternalThreadIDHasSuffix(v string) predicate.CodexThreadControl {
	return predicate.CodexThreadControl(sql.FieldHasSuffix(FieldExternalThreadID, v))
}

// ExternalThreadIDIsNil applies the IsNil predicate on the "external_thread_id" field.
func ExternalThreadIDIsNil() predicate.CodexThreadControl {
	return predicate.CodexThreadControl(sql.FieldIsNull(FieldExternalThreadID))
}

// ExternalThreadIDNotNil applies the NotNil predicate on the "external_thread_id" field.
func ExternalThreadIDNotNil() predicate.CodexThreadControl {
	return predicate.CodexThreadControl(sql.FieldNotNull(FieldExternalThreadID))
}

// ExternalThreadIDEqualFold applies the EqualFold predicate on the "external_thread_id" field.
func ExternalThreadIDEqualFold(v string) predicate.CodexThreadControl {
	return predicate.CodexThreadControl(sql.FieldEqualFold(FieldExternalThreadID, v))
}

// ExternalThreadIDContainsFold applies the ContainsFold predicate on the "external_thread_id" field.
func ExternalThreadIDContainsFold(v string) predicate.CodexThreadControl {
	return predicate.CodexThreadControl(sql.FieldContainsFold(FieldExternalThreadID, v))
}

// CodexHomeKeyEQ applies the EQ predicate on the "codex_home_key" field.
func CodexHomeKeyEQ(v string) predicate.CodexThreadControl {
	return predicate.CodexThreadControl(sql.FieldEQ(FieldCodexHomeKey, v))
}

// CodexHomeKeyNEQ applies the NEQ predicate on the "codex_home_key" field.
func CodexHomeKeyNEQ(v string) predicate.CodexThreadControl {
	return predicate.CodexThreadControl(sql.FieldNEQ(FieldCodexHomeKey, v))
}

// CodexHomeKeyIn applies the In predicate on the "codex_home_key" field.
func CodexHomeKeyIn(vs ...string) predicate.CodexThreadControl {
	return predicate.CodexThreadControl(sql.FieldIn(FieldCodexHomeKey, vs...))
}

// CodexHomeKeyNotIn applies the NotIn predicate on the "codex_home_key" field.
func CodexHomeKeyNotIn(vs ...string) predicate.CodexThreadControl {
	return predicate.CodexThreadControl(sql.FieldNotIn(FieldCodexHomeKey, vs...))
}

// CodexHomeKeyGT applies the GT predicate on the "codex_home_key" field.
func CodexHomeKeyGT(v string) predicate.CodexThreadControl {
	return predicate.CodexThreadControl(sql.FieldGT(FieldCodexHomeKey, v))
}

// CodexHomeKeyGTE applies the GTE predicate on the "codex_home_key" field.
func CodexHomeKeyGTE(v string) predicate.CodexThreadControl {
	return predicate.CodexThreadControl(sql.FieldGTE(FieldCodexHomeKey, v))
}

// CodexHomeKeyLT applies the LT predicate on the "codex_home_key" field.
func CodexHomeKeyLT(v string) predicate.CodexThreadControl {
	return predicate.CodexThreadControl(sql.FieldLT(FieldCodexHomeKey, v))
}

// CodexHomeKeyLTE applies the LTE predicate on the "codex_home_key" field.
func CodexHomeKeyLTE(v string) predicate.CodexThreadControl {
	return predicate.CodexThreadControl(sql.FieldLTE(FieldCodexHomeKey, v))
}

// CodexHomeKeyContains applies the Contains predicate on the "codex_home_key" field.
func CodexHomeKeyContains(v string) predicate.CodexThreadControl {
	return predicate.CodexThreadControl(sql.FieldContains(FieldCodexHomeKey, v))
}

// CodexHomeKeyHasPrefix applies the HasPrefix predicate on the "codex_home_key" field.
func CodexHomeKeyHasPrefix(v string) predicate.CodexThreadControl {
	return predicate.CodexThreadControl(sql.FieldHasPrefix(FieldCodexHomeKey, v))
}

// CodexHomeKeyHasSuffix applies the HasSuffix predicate on the "codex_home_key" field.
func CodexHomeKeyHasSuffix(v string) predicate.CodexThreadControl {
	return predicate.CodexThreadControl(sql.FieldHasSuffix(FieldCodexHomeKey, v))
}

// CodexHomeKeyIsNil applies the IsNil predicate on the "codex_home_key" field.
func CodexHomeKeyIsNil() predicate.CodexThreadControl {
	return predicate.CodexThreadControl(sql.FieldIsNull(FieldCodexHomeKey))
}

// CodexHomeKeyNotNil applies the NotNil predicate on the "codex_home_key" field.
func CodexHomeKeyNotNil() predicate.CodexThreadControl {
	return predicate.CodexThreadControl(sql.FieldNotNull(FieldCodexHomeKey))
}

// CodexHomeKeyEqualFold applies the EqualFold predicate on the "codex_home_key" field.
func CodexHomeKeyEqualFold(v string) predicate.CodexThreadControl {
	return predicate.CodexThreadControl(sql.FieldEqualFold(FieldCodexHomeKey, v))
}

// CodexHomeKeyContainsFold applies the ContainsFold predicate on the "codex_home_key" field.
func CodexHomeKeyContainsFold(v string) predicate.CodexThreadControl {
	return predicate.CodexThreadControl(sql.FieldContainsFold(FieldCodexHomeKey, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v string) predicate.CodexThreadControl {
	return predicate.CodexThreadControl(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v string) predicate.CodexThreadControl {
	return predicate.CodexThreadControl(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...string) predicate.CodexThreadControl {
	return predicate.CodexThreadControl(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...string) predicate.CodexThreadControl {
	return predicate.CodexThreadControl(sql.FieldNotIn(FieldStatus, vs...))
}

// StatusGT applies the GT predicate on the "status" field.
func StatusGT(v string) predicate.CodexThreadControl {
	return predicate.CodexThreadControl(sql.FieldGT(FieldStatus, v))
}

// StatusGTE applies the GTE predicate on the "status" field.
func StatusGTE(v string) predicate.CodexThreadControl {
	return predicate.CodexThreadControl(sql.FieldGTE(FieldStatus, v))
}

// StatusLT applies the LT predicate on the "status" field.
func StatusLT(v string) predicate.CodexThreadControl {
	return predicate.CodexThreadControl(sql.FieldLT(FieldStatus, v))
}

// StatusLTE applies the LTE predicate on the "status" field.
func StatusLTE(v string) predicate.CodexThreadControl {
	return predicate.CodexThreadControl(sql.FieldLTE(FieldStatus, v))
}

// StatusContains applies the Contains predicate on the "status" field.
func StatusContains(v string) predicate.CodexThreadControl {
	return predicate.CodexThreadControl(sql.FieldContains(FieldStatus, v))
}

// StatusHasPrefix applies the HasPrefix predicate on the "status" field.
func StatusHasPrefix(v string) predicate.CodexThreadControl {
	return predicate.CodexThreadControl(sql.FieldHasPrefix(FieldStatus, v))
}

// StatusHasSuffix applies the HasSuffix predicate on the "status" field.
func StatusHasSuffix(v string) predicate.CodexThreadControl {
	return predicate.CodexThreadControl(sql.FieldHasSuffix(FieldStatus, v))
}

// StatusEqualFold applies the EqualFold predicate on the "status" field.
func StatusEqualFold(v string) predicate.CodexThreadControl {
	return predicate.CodexThreadControl(sql.FieldEqualFold(FieldStatus, v))
}

// StatusContainsFold applies the ContainsFold predicate on the "status" field.
func StatusContainsFold(v string) predicate.CodexThreadControl {
	return predicate.CodexThreadControl(sql.FieldContainsFold(FieldStatus, v))
}

// NextSequenceNoEQ applies the EQ predicate on the "next_sequence_no" field.
func NextSequenceNoEQ(v int64) predicate.CodexThreadControl {
	return predicate.CodexThreadControl(sql.FieldEQ(FieldNextSequenceNo, v))
}

// NextSequenceNoNEQ applies the NEQ predicate on the "next_sequence_no" field.
func NextSequenceNoNEQ(v int64) predicate.CodexThreadControl {
	return predicate.CodexThreadControl(sql.FieldNEQ(FieldNextSequenceNo, v))
}

// NextSequenceNoIn applies the In predicate on the "next_sequence_no" field.
func NextSequenceNoIn(vs ...int64) predicate.CodexThreadControl {
	return predicate.CodexThreadControl(sql.FieldIn(FieldNextSequenceNo, vs...))
}

// NextSequenceNoNotIn applies the NotIn predicate on the "next_sequence_no" field.
func NextSequenceNoNotIn(vs ...int64) predicate.CodexThreadControl {
	return predicate.CodexThreadControl(sql.FieldNotIn(FieldNextSequenceNo, vs...))
}

// NextSequenceNoGT applies the GT predicate on the "next_sequence_no" field.
func NextSequenceNoGT(v int64) predicate.CodexThreadControl {
	return predicate.CodexThreadControl(sql.FieldGT(FieldNextSequenceNo, v))
}

// NextSequenceNoGTE applies the GTE predicate on the "next_sequence_no" field.
func NextSequenceNoGTE(v int64) predicate.CodexThreadControl {
	return predicate.CodexThreadControl(sql.FieldGTE(FieldNextSequenceNo, v))
}

// NextSequenceNoLT applies the LT predicate on the "next_sequence_no" field.
func NextSequenceNoLT(v int64) predicate.CodexThreadControl {
	return predicate.CodexThreadControl(sql.FieldLT(FieldNextSequenceNo, v))
}

// NextSequenceNoLTE applies the LTE predicate on the "next_sequence_no" field.
func NextSequenceNoLTE(v int64) predicate.CodexThreadControl {
	return predicate.CodexThreadControl(sql.FieldLTE(FieldNextSequenceNo, v))
}

// ActiveIntentIDEQ applies the EQ predicate on the "active_intent_id" field.
func ActiveIntentIDEQ(v uuid.UUID) predicate.CodexThreadControl {
	return predicate.CodexThreadControl(sql.FieldEQ(FieldActiveIntentID, v))
}

// ActiveIntentIDNEQ applies the NEQ predicate on the "active_intent_id" field.
func ActiveIntentIDNEQ(v uuid.UUID) predicate.CodexThreadControl {
	return predicate.CodexThreadControl(sql.FieldNEQ(FieldActiveIntentID, v))
}

// ActiveIntentIDIn applies the In predicate on the "active_intent_id" field.
func ActiveIntentIDIn(vs ...uuid.UUID) predicate.CodexThreadControl {
	return predicate.CodexThreadControl(sql.FieldIn(FieldActiveIntentID, vs...))
}

// ActiveIntentIDNotIn applies the NotIn predicate on the "active_intent_id" field.
func ActiveIntentIDNotIn(vs ...uuid.UUID) predicate.CodexThreadControl {
	return predicate.CodexThreadControl(sql.FieldNotIn(FieldActiveIntentID, vs...))
}

// ActiveIntentIDGT applies the GT predicate on the "active_intent_id" field.
func ActiveIntentIDGT(v uuid.UUID) predicate.CodexThreadControl {
	return predicate.CodexThreadControl(sql.FieldGT(FieldActiveIntentID, v))
}

// ActiveIntentIDGTE applies the GTE predicate on the "active_intent_id" field.
func ActiveIntentIDGTE(v uuid.UUID) predicate.CodexThreadControl {
	return predicate.CodexThreadControl(sql.FieldGTE(FieldActiveIntentID, v))
}

// ActiveIntentIDLT applies the LT predicate on the "active_intent_id" field.
func ActiveIntentIDLT(v uuid.UUID) predicate.CodexThreadControl {
	return predicate.CodexThreadControl(sql.FieldLT(FieldActiveIntentID, v))
}

// ActiveIntentIDLTE applies the LTE predicate on the "active_intent_id" field.
func ActiveIntentIDLTE(v uuid.UUID) predicate.CodexThreadControl {
	return predicate.CodexThreadControl(sql.FieldLTE(FieldActiveIntentID, v))
}

// ActiveIntentIDIsNil applies the IsNil predicate on the "active_intent_id" field.
func ActiveIntentIDIsNil() predicate.CodexThreadControl {
	return predicate.CodexThreadControl(sql.FieldIsNull(FieldActiveIntentID))
}

// ActiveIntentIDNotNil applies the NotNil predicate on the "active_intent_id" field.
func ActiveIntentIDNotNil() predicate.CodexThreadControl {
	return predicate.CodexThreadControl(sql.FieldNotNull(FieldActiveIntentID))
}

// RemoteStatusEQ applies the EQ predicate on the "remote_status" field.
func RemoteStatusEQ(v string) predicate.CodexThreadControl {
	return predicate.CodexThreadControl(sql.FieldEQ(FieldRemoteStatus, v))
}

// RemoteStatusNEQ applies the NEQ predicate on the "remote_status" field.
func RemoteStatusNEQ(v string) predicate.CodexThreadControl {
	return predicate.CodexThreadControl(sql.FieldNEQ(FieldRemoteStatus, v))
}

// RemoteStatusIn applies the In predicate on the "remote_status" field.
func RemoteStatusIn(vs ...string) predicate.CodexThreadControl {
	return predicate.CodexThreadControl(sql.FieldIn(FieldRemoteStatus, vs...))
}

// RemoteStatusNotIn applies the NotIn predicate on the "remote_status" field.
func RemoteStatusNotIn(vs ...string) predicate.CodexThreadControl {
	return predicate.CodexThreadControl(sql.FieldNotIn(FieldRemoteStatus, vs...))
}

// RemoteStatusGT applies the GT predicate on the "remote_status" field.
func RemoteStatusGT(v string) predicate.CodexThreadControl {
	return predicate.CodexThreadControl(sql.FieldGT(FieldRemoteStatus, v))
}

// RemoteStatusGTE applies the GTE predicate on the "remote_status" field.
func RemoteStatusGTE(v string) predicate.CodexThreadControl {
	return predicate.CodexThreadControl(sql.FieldGTE(FieldRemoteStatus, v))
}

// RemoteStatusLT applies the LT predicate on the "remote_status" field.
func RemoteStatusLT(v string) predicate.CodexThreadControl {
	return predicate.CodexThreadControl(sql.FieldLT(FieldRemoteStatus, v))
}

// RemoteStatusLTE applies the LTE predicate on the "remote_status" field.
func RemoteStatusLTE(v string) predicate.CodexThreadControl {
	return predicate.CodexThreadControl(sql.FieldLTE(FieldRemoteStatus, v))
}

// RemoteStatusContains applies the Contains predicate on the "remote_status" field.
func RemoteStatusContains(v string) predicate.CodexThreadControl {
	return predicate.CodexThreadControl(sql.FieldContains(FieldRemoteStatus, v))
}

// RemoteStatusHasPrefix applies the HasPrefix predicate on the "remote_status" field.
func RemoteStatusHasPrefix(v string) predicate.CodexThreadControl {
	return predicate.CodexThreadControl(sql.FieldHasPrefix(FieldRemoteStatus, v))
}

// RemoteStatusHasSuffix applies the HasSuffix predicate on the "remote_status" field.
func RemoteStatusHasSuffix(v string) predicate.CodexThreadControl {
	return predicate.CodexThreadControl(sql.FieldHasSuffix(FieldRemoteStatus, v))
}

// RemoteStatusIsNil applies the IsNil predicate on the "remote_status" field.
func RemoteStatusIsNil() predicate.CodexThreadControl {
	return predicate.CodexThreadControl(sql.FieldIsNull(FieldRemoteStatus))
}

// RemoteStatusNotNil applies the NotNil predicate on the "remote_status" field.
func RemoteStatusNotNil() predicate.CodexThreadControl {
	return predicate.CodexThreadControl(sql.FieldNotNull(FieldRemoteStatus))
}

// RemoteStatusEqualFold applies the EqualFold predicate on the "remote_status" field.
func RemoteStatusEqualFold(v string) predicate.CodexThreadControl {
	return predicate.CodexThreadControl(sql.FieldEqualFold(FieldRemoteStatus, v))
}

// RemoteStatusContainsFold applies the ContainsFold predicate on the "remote_status" field.
func RemoteStatusContainsFold(v string) predicate.CodexThreadControl {
	return predicate.CodexThreadControl(sql.FieldContainsFold(FieldRemoteStatus, v))
}

// ActiveCodexTurnIDEQ applies the EQ predicate on the "active_codex_turn_id" field.
func ActiveCodexTurnIDEQ(v string) predicate.CodexThreadControl {
	return predicate.CodexThreadControl(sql.FieldEQ(FieldActiveCodexTurnID, v))
}

// ActiveCodexTurnIDNEQ applies the NEQ predicate on the "active_codex_turn_id" field.
func ActiveCodexTurnIDNEQ(v string) predicate.CodexThreadControl {
	return predicate.CodexThreadControl(sql.FieldNEQ(FieldActiveCodexTurnID, v))
}

// ActiveCodexTurnIDIn applies the In predicate on the "active_codex_turn_id" field.
func ActiveCodexTurnIDIn(vs ...string) predicate.CodexThreadControl {
	return predicate.CodexThreadControl(sql.FieldIn(FieldActiveCodexTurnID, vs...))
}

// ActiveCodexTurnIDNotIn applies the NotIn predicate on the "active_codex_turn_id" field.
func ActiveCodexTurnIDNotIn(vs ...string) predicate.CodexThreadControl {
	return predicate.CodexThreadControl(sql.FieldNotIn(FieldActiveCodexTurnID, vs...))
}

// ActiveCodexTurnIDGT applies the GT predicate on the "active_codex_turn_id" field.
func ActiveCodexTurnIDGT(v string) predicate.CodexThreadControl {
	return predicate.CodexThreadControl(sql.FieldGT(FieldActiveCodexTurnID, v))
}

// ActiveCodexTurnIDGTE applies the GTE predicate on the "active_codex_turn_id" field.
func ActiveCodexTurnIDGTE(v string) predicate.CodexThreadControl {
	return predicate.CodexThreadControl(sql.FieldGTE(FieldActiveCodexTurnID, v))
}

// ActiveCodexTurnIDLT applies the LT predicate on the "active_codex_turn_id" field.
func ActiveCodexTurnIDLT(v string) predicate.CodexThreadControl {
	return predicate.CodexThreadControl(sql.FieldLT(FieldActiveCodexTurnID, v))
}

// ActiveCodexTurnIDLTE applies the LTE predicate on the "active_codex_turn_id" field.
func ActiveCodexTurnIDLTE(v string) predicate.CodexThreadControl {
	return predicate.CodexThreadControl(sql.FieldLTE(FieldActiveCodexTurnID, v))
}

// ActiveCodexTurnIDContains applies the Contains predicate on the "active_codex_turn_id" field.
func ActiveCodexTurnIDContains(v string) predicate.CodexThreadControl {
	return predicate.CodexThreadControl(sql.FieldContains(FieldActiveCodexTurnID, v))
}

// ActiveCodexTurnIDHasPrefix applies the HasPrefix predicate on the "active_codex_turn_id" field.
func ActiveCodexTurnIDHasPrefix(v string) predicate.CodexThreadControl {
	return predicate.CodexThreadControl(sql.FieldHasPrefix(FieldActiveCodexTurnID, v))
}

// ActiveCodexTurnIDHasSuffix applies the HasSuffix predicate on the "active_codex_turn_id" field.
func ActiveCodexTurnIDHasSuffix(v string) predicate.CodexThreadControl {
	return predicate.CodexThreadControl(sql.FieldHasSuffix(FieldActiveCodexTurnID, v))
}

// ActiveCodexTurnIDIsNil applies the IsNil predicate on the "active_codex_turn_id" field.
func ActiveCodexTurnIDIsNil() predicate.CodexThreadControl {
	return predicate.CodexThreadControl(sql.FieldIsNull(FieldActiveCodexTurnID))
}

// ActiveCodexTurnIDNotNil applies the NotNil predicate on the "active_codex_turn_id" field.
func ActiveCodexTurnIDNotNil() predicate.CodexThreadControl {
	return predicate.CodexThreadControl(sql.FieldNotNull(FieldActiveCodexTurnID))
}

// ActiveCodexTurnIDEqualFold applies the EqualFold predicate on the "active_codex_turn_id" field.
func ActiveCodexTurnIDEqualFold(v string) predicate.CodexThreadControl {
	return predicate.CodexThreadControl(sql.FieldEqualFold(FieldActiveCodexTurnID, v))
}

// ActiveCodexTurnIDContainsFold applies the ContainsFold predicate on the "active_codex_turn_id" field.
func ActiveCodexTurnIDContainsFold(v string) predicate.CodexThreadControl {
	return predicate.CodexThreadControl(sql.FieldContainsFold(FieldActiveCodexTurnID, v))
}

// ActiveClientIDEQ applies the EQ predicate on the "active_client_id" field.
func ActiveClientIDEQ(v string) predicate.CodexThreadControl {
	return predicate.CodexThreadControl(sql.FieldEQ(FieldActiveClientID, v))
}

// ActiveClientIDNEQ applies the NEQ predicate on the "active_client_id" field.
func ActiveClientIDNEQ(v string) predicate.CodexThreadControl {
	return predicate.CodexThreadControl(sql.FieldNEQ(FieldActiveClientID, v))
}

// ActiveClientIDIn applies the In predicate on the "active_client_id" field.
func ActiveClientIDIn(vs ...string) predicate.CodexThreadControl {
	return predicate.CodexThreadControl(sql.FieldIn(FieldActiveClientID, vs...))
}

// ActiveClientIDNotIn applies the NotIn predicate on the "active_client_id" field.
func ActiveClientIDNotIn(vs ...string) predicate.CodexThreadControl {
	return predicate.CodexThreadControl(sql.FieldNotIn(FieldActiveClientID, vs...))
}

// ActiveClientIDGT applies the GT predicate on the "active_client_id" field.
func ActiveClientIDGT(v string) predicate.CodexThreadControl {
	return predicate.CodexThreadControl(sql.FieldGT(FieldActiveClientID, v))
}

// ActiveClientIDGTE applies the GTE predicate on the "active_client_id" field.
func ActiveClientIDGTE(v string) predicate.CodexThreadControl {
	return predicate.CodexThreadControl(sql.FieldGTE(FieldActiveClientID, v))
}

// ActiveClientIDLT applies the LT predicate on the "active_client_id" field.
func ActiveClientIDLT(v string) predicate.CodexThreadControl {
	return predicate.CodexThreadControl(sql.FieldLT(FieldActiveClientID, v))
}

// ActiveClientIDLTE applies the LTE predicate on the "active_client_id" field.
func ActiveClientIDLTE(v string) predicate.CodexThreadControl {
	return predicate.CodexThreadControl(sql.FieldLTE(FieldActiveClientID, v))
}

// ActiveClientIDContains applies the Contains predicate on the "active_client_id" field.
func ActiveClientIDContains(v string) predicate.CodexThreadControl {
	return predicate.CodexThreadControl(sql.FieldContains(FieldActiveClientID, v))
}

// ActiveClientIDHasPrefix applies the HasPrefix predicate on the "active_client_id" field.
func ActiveClientIDHasPrefix(v string) predicate.CodexThreadControl {
	return predicate.CodexThreadControl(sql.FieldHasPrefix(FieldActiveClientID, v))
}

// ActiveClientIDHasSuffix applies the HasSuffix predicate on the "active_client_id" field.
func ActiveClientIDHasSuffix(v string) predicate.CodexThreadControl {
	return predicate.CodexThreadControl(sql.FieldHasSuffix(FieldActiveClientID, v))
}

// ActiveClientIDIsNil applies the IsNil predicate on the "active_client_id" field.
func ActiveClientIDIsNil() predicate.CodexThreadControl {
	return predicate.CodexThreadControl(sql.FieldIsNull(FieldActiveClientID))
}

// ActiveClientIDNotNil applies the NotNil predicate on the "active_client_id" field.
func ActiveClientIDNotNil() predicate.CodexThreadControl {
	return predicate.CodexThreadControl(sql.FieldNotNull(FieldActiveClientID))
}

// ActiveClientIDEqualFold applies the EqualFold predicate on the "active_client_id" field.
func ActiveClientIDEqualFold(v string) predicate.CodexThreadControl {
	return predicate.CodexThreadControl(sql.FieldEqualFold(FieldActiveClientID, v))
}

// ActiveClientIDContainsFold applies the ContainsFold predicate on the "active_client_id" field.
func ActiveClientIDContainsFold(v string) predicate.CodexThreadControl {
	return predicate.CodexThreadControl(sql.FieldContainsFold(FieldActiveClientID, v))
}

// LeaseEpochEQ applies the EQ predicate on the "lease_epoch" field.
func LeaseEpochEQ(v int64) predicate.CodexThreadControl {
	return predicate.CodexThreadControl(sql.FieldEQ(FieldLeaseEpoch, v))
}

// LeaseEpochNEQ applies the NEQ predicate on the "lease_epoch" field.
func LeaseEpochNEQ(v int64) predicate.CodexThreadControl {
	return predicate.CodexThreadControl(sql.FieldNEQ(FieldLeaseEpoch, v))
}

// LeaseEpochIn applies the In predicate on the "lease_epoch" field.
func LeaseEpochIn(vs ...int64) predicate.CodexThreadControl {
	return predicate.CodexThreadControl(sql.FieldIn(FieldLeaseEpoch, vs...))
}

// LeaseEpochNotIn applies the NotIn predicate on the "lease_epoch" field.
func LeaseEpochNotIn(vs ...int64) predicate.CodexThreadControl {
	return predicate.CodexThreadControl(sql.FieldNotIn(FieldLeaseEpoch, vs...))
}

// LeaseEpochGT applies the GT predicate on the "lease_epoch" field.
func LeaseEpochGT(v int64) predicate.CodexThreadControl {
	return predicate.CodexThreadControl(sql.FieldGT(FieldLeaseEpoch, v))
}

// LeaseEpochGTE applies the GTE predicate on the "lease_epoch" field.
func LeaseEpochGTE(v int64) predicate.CodexThreadControl {
	return predicate.CodexThreadControl(sql.FieldGTE(FieldLeaseEpoch, v))
}

// LeaseEpochLT applies the LT predicate on the "lease_epoch" field.
func LeaseEpochLT(v int64) predicate.CodexThreadControl {
	return predicate.CodexThreadControl(sql.FieldLT(FieldLeaseEpoch, v))
}

// LeaseEpochLTE applies the LTE predicate on the "lease_epoch" field.
func LeaseEpochLTE(v int64) predicate.CodexThreadControl {
	return predicate.CodexThreadControl(sql.FieldLTE(FieldLeaseEpoch, v))
}

// LeaseExpiresAtEQ applies the EQ predicate on the "lease_expires_at" field.
func LeaseExpiresAtEQ(v time.Time) predicate.CodexThreadControl {
	return predicate.CodexThreadControl(sql.FieldEQ(FieldLeaseExpiresAt, v))
}

// LeaseExpiresAtNEQ applies the NEQ predicate on the "lease_expires_at" field.
func LeaseExpiresAtNEQ(v time.Time) predicate.CodexThreadControl {
	return predicate.CodexThreadControl(sql.FieldNEQ(FieldLeaseExpiresAt, v))
}

// LeaseExpiresAtIn applies the In predicate on the "lease_expires_at" field.
func LeaseExpiresAtIn(vs ...time.Time) predicate.CodexThreadControl {
	return predicate.CodexThreadControl(sql.FieldIn(FieldLeaseExpiresAt, vs...))
}

// LeaseExpiresAtNotIn applies the NotIn predicate on the "lease_expires_at" field.
func LeaseExpiresAtNotIn(vs ...time.Time) predicate.CodexThreadControl {
	return predicate.CodexThreadControl(sql.FieldNotIn(FieldLeaseExpiresAt, vs...))
}

// LeaseExpiresAtGT applies the GT predicate on the "lease_expires_at" field.
func LeaseExpiresAtGT(v time.Time) predicate.CodexThreadControl {
	return predicate.CodexThreadControl(sql.FieldGT(FieldLeaseExpiresAt, v))
}

// LeaseExpiresAtGTE applies the GTE predicate on the "lease_expires_at" field.
func LeaseExpiresAtGTE(v time.Time) predicate.CodexThreadControl {
	return predicate.CodexThreadControl(sql.FieldGTE(FieldLeaseExpiresAt, v))
}

// LeaseExpiresAtLT applies the LT predicate on the "lease_expires_at" field.
func LeaseExpiresAtLT(v time.Time) predicate.CodexThreadControl {
	return predicate.CodexThreadControl(sql.FieldLT(FieldLeaseExpiresAt, v))
}

// LeaseExpiresAtLTE applies the LTE predicate on the "lease_expires_at" field.
func LeaseExpiresAtLTE(v time.Time) predicate.CodexThreadControl {
	return predicate.CodexThreadControl(sql.FieldLTE(FieldLeaseExpiresAt, v))
}

// LeaseExpiresAtIsNil applies the IsNil predicate on the "lease_expires_at" field.
func LeaseExpiresAtIsNil() predicate.CodexThreadControl {
	return predicate.CodexThreadControl(sql.FieldIsNull(FieldLeaseExpiresAt))
}

// LeaseExpiresAtNotNil applies the NotNil predicate on the "lease_expires_at" field.
func LeaseExpiresAtNotNil() predicate.CodexThreadControl {
	return predicate.CodexThreadControl(sql.FieldNotNull(FieldLeaseExpiresAt))
}

// HeartbeatAtEQ applies the EQ predicate on the "heartbeat_at" field.
func HeartbeatAtEQ(v time.Time) predicate.CodexThreadControl {
	return predicate.CodexThreadControl(sql.FieldEQ(FieldHeartbeatAt, v))
}

// HeartbeatAtNEQ applies the NEQ predicate on the "heartbeat_at" field.
func HeartbeatAtNEQ(v time.Time) predicate.CodexThreadControl {
	return predicate.CodexThreadControl(sql.FieldNEQ(FieldHeartbeatAt, v))
}

// HeartbeatAtIn applies the In predicate on the "heartbeat_at" field.
func HeartbeatAtIn(vs ...time.Time) predicate.CodexThreadControl {
	return predicate.CodexThreadControl(sql.FieldIn(FieldHeartbeatAt, vs...))
}

// HeartbeatAtNotIn applies the NotIn predicate on the "heartbeat_at" field.
func HeartbeatAtNotIn(vs ...time.Time) predicate.CodexThreadControl {
	return predicate.CodexThreadControl(sql.FieldNotIn(FieldHeartbeatAt, vs...))
}

// HeartbeatAtGT applies the GT predicate on the "heartbeat_at" field.
func HeartbeatAtGT(v time.Time) predicate.CodexThreadControl {
	return predicate.CodexThreadControl(sql.FieldGT(FieldHeartbeatAt, v))
}

// HeartbeatAtGTE applies the GTE predicate on the "heartbeat_at" field.
func HeartbeatAtGTE(v time.Time) predicate.CodexThreadControl {
	return predicate.CodexThreadControl(sql.FieldGTE(FieldHeartbeatAt, v))
}

// HeartbeatAtLT applies the LT predicate on the "heartbeat_at" field.
func HeartbeatAtLT(v time.Time) predicate.CodexThreadControl {
	return predicate.CodexThreadControl(sql.FieldLT(FieldHeartbeatAt, v))
}

// HeartbeatAtLTE applies the LTE predicate on the "heartbeat_at" field.
func HeartbeatAtLTE(v time.Time) predicate.CodexThreadControl {
	return predicate.CodexThreadControl(sql.FieldLTE(FieldHeartbeatAt, v))
}

// HeartbeatAtIsNil applies the IsNil predicate on the "heartbeat_at" field.
func HeartbeatAtIsNil() predicate.CodexThreadControl {
	return predicate.CodexThreadControl(sql.FieldIsNull(FieldHeartbeatAt))
}

// HeartbeatAtNotNil applies the NotNil predicate on the "heartbeat_at" field.
func HeartbeatAtNotNil() predicate.CodexThreadControl {
	return predicate.CodexThreadControl(sql.FieldNotNull(FieldHeartbeatAt))
}

// LastReconciledAtEQ applies the EQ predicate on the "last_reconciled_at" field.
func LastReconciledAtEQ(v time.Time) predicate.CodexThreadControl {
	return predicate.CodexThreadControl(sql.FieldEQ(FieldLastReconciledAt, v))
}

// LastReconciledAtNEQ applies the NEQ predicate on the "last_reconciled_at" field.
func LastReconciledAtNEQ(v time.Time) predicate.CodexThreadControl {
	return predicate.CodexThreadControl(sql.FieldNEQ(FieldLastReconciledAt, v))
}

// LastReconciledAtIn applies the In predicate on the "last_reconciled_at" field.
func LastReconciledAtIn(vs ...time.Time) predicate.CodexThreadControl {
	return predicate.CodexThreadControl(sql.FieldIn(FieldLastReconciledAt, vs...))
}

// LastReconciledAtNotIn applies the NotIn predicate on the "last_reconciled_at" field.
func LastReconciledAtNotIn(vs ...time.Time) predicate.CodexThreadControl {
	return predicate.CodexThreadControl(sql.FieldNotIn(FieldLastReconciledAt, vs...))
}

// LastReconciledAtGT applies the GT predicate on the "last_reconciled_at" field.
func LastReconciledAtGT(v time.Time) predicate.CodexThreadControl {
	return predicate.CodexThreadControl(sql.FieldGT(FieldLastReconciledAt, v))
}

// LastReconciledAtGTE applies the GTE predicate on the "last_reconciled_at" field.
func LastReconciledAtGTE(v time.Time) predicate.CodexThreadControl {
	return predicate.CodexThreadControl(sql.FieldGTE(FieldLastReconciledAt, v))
}

// LastReconciledAtLT applies the LT predicate on the "last_reconciled_at" field.
func LastReconciledAtLT(v time.Time) predicate.CodexThreadControl {
	return predicate.CodexThreadControl(sql.FieldLT(FieldLastReconciledAt, v))
}

// LastReconciledAtLTE applies the LTE predicate on the "last_reconciled_at" field.
func LastReconciledAtLTE(v time.Time) predicate.CodexThreadControl {
	return predicate.CodexThreadControl(sql.FieldLTE(FieldLastReconciledAt, v))
}

// LastReconciledAtIsNil applies the IsNil predicate on the "last_reconciled_at" field.
func LastReconciledAtIsNil() predicate.CodexThreadControl {
	return predicate.CodexThreadControl(sql.FieldIsNull(FieldLastReconciledAt))
}

// LastReconciledAtNotNil applies the NotNil predicate on the "last_reconciled_at" field.
func LastReconciledAtNotNil() predicate.CodexThreadControl {
	return predicate.CodexThreadControl(sql.FieldNotNull(FieldLastReconciledAt))
}

// NextWakeupAtEQ applies the EQ predicate on the "next_wakeup_at" field.
func NextWakeupAtEQ(v time.Time) predicate.CodexThreadControl {
	return predicate.CodexThreadControl(sql.FieldEQ(FieldNextWakeupAt, v))
}

// NextWakeupAtNEQ applies the NEQ predicate on the "next_wakeup_at" field.
func NextWakeupAtNEQ(v time.Time) predicate.CodexThreadControl {
	return predicate.CodexThreadControl(sql.FieldNEQ(FieldNextWakeupAt, v))
}

// NextWakeupAtIn applies the In predicate on the "next_wakeup_at" field.
func NextWakeupAtIn(vs ...time.Time) predicate.CodexThreadControl {
	return predicate.CodexThreadControl(sql.FieldIn(FieldNextWakeupAt, vs...))
}

// NextWakeupAtNotIn applies the NotIn predicate on the "next_wakeup_at" field.
func NextWakeupAtNotIn(vs ...time.Time) predicate.CodexThreadControl {
	return predicate.CodexThreadControl(sql.FieldNotIn(FieldNextWakeupAt, vs...))
}

// NextWakeupAtGT applies the GT predicate on the "next_wakeup_at" field.
func NextWakeupAtGT(v time.Time) predicate.CodexThreadControl {
	return predicate.CodexThreadControl(sql.FieldGT(FieldNextWakeupAt, v))
}

// NextWakeupAtGTE applies the GTE predicate on the "next_wakeup_at" field.
func NextWakeupAtGTE(v time.Time) predicate.CodexThreadControl {
	return predicate.CodexThreadControl(sql.FieldGTE(FieldNextWakeupAt, v))
}

// NextWakeupAtLT applies the LT predicate on the "next_wakeup_at" field.
func NextWakeupAtLT(v time.Time) predicate.CodexThreadControl {
	return predicate.CodexThreadControl(sql.FieldLT(FieldNextWakeupAt, v))
}

// NextWakeupAtLTE applies the LTE predicate on the "next_wakeup_at" field.
func NextWakeupAtLTE(v time.Time) predicate.CodexThreadControl {
	return predicate.CodexThreadControl(sql.FieldLTE(FieldNextWakeupAt, v))
}

// NextWakeupAtIsNil applies the IsNil predicate on the "next_wakeup_at" field.
func NextWakeupAtIsNil() predicate.CodexThreadControl {
	return predicate.CodexThreadControl(sql.FieldIsNull(FieldNextWakeupAt))
}

// NextWakeupAtNotNil applies the NotNil predicate on the "next_wakeup_at" field.
func NextWakeupAtNotNil() predicate.CodexThreadControl {
	return predicate.CodexThreadControl(sql.FieldNotNull(FieldNextWakeupAt))
}

// WorkerIDEQ applies the EQ predicate on the "worker_id" field.
func WorkerIDEQ(v string) predicate.CodexThreadControl {
	return predicate.CodexThreadControl(sql.FieldEQ(FieldWorkerID, v))
}

// WorkerIDNEQ applies the NEQ predicate on the "worker_id" field.
func WorkerIDNEQ(v string) predicate.CodexThreadControl {
	return predicate.CodexThreadControl(sql.FieldNEQ(FieldWorkerID, v))
}

// WorkerIDIn applies the In predicate on the "worker_id" field.
func WorkerIDIn(vs ...string) predicate.CodexThreadControl {
	return predicate.CodexThreadControl(sql.FieldIn(FieldWorkerID, vs...))
}

// WorkerIDNotIn applies the NotIn predicate on the "worker_id" field.
func WorkerIDNotIn(vs ...string) predicate.CodexThreadControl {
	return predicate.CodexThreadControl(sql.FieldNotIn(FieldWorkerID, vs...))
}

// WorkerIDGT applies the GT predicate on the "worker_id" field.
func WorkerIDGT(v string) predicate.CodexThreadControl {
	return predicate.CodexThreadControl(sql.FieldGT(FieldWorkerID, v))
}

// WorkerIDGTE applies the GTE predicate on the "worker_id" field.
func WorkerIDGTE(v string) predicate.CodexThreadControl {
	return predicate.CodexThreadControl(sql.FieldGTE(FieldWorkerID, v))
}

// WorkerIDLT applies the LT predicate on the "worker_id" field.
func WorkerIDLT(v string) predicate.CodexThreadControl {
	return predicate.CodexThreadControl(sql.FieldLT(FieldWorkerID, v))
}

// WorkerIDLTE applies the LTE predicate on the "worker_id" field.
func WorkerIDLTE(v string) predicate.CodexThreadControl {
	return predicate.CodexThreadControl(sql.FieldLTE(FieldWorkerID, v))
}

// WorkerIDContains applies the Contains predicate on the "worker_id" field.
func WorkerIDContains(v string) predicate.CodexThreadControl {
	return predicate.CodexThreadControl(sql.FieldContains(FieldWorkerID, v))
}

// WorkerIDHasPrefix applies the HasPrefix predicate on the "worker_id" field.
func WorkerIDHasPrefix(v string) predicate.CodexThreadControl {
	return predicate.CodexThreadControl(sql.FieldHasPrefix(FieldWorkerID, v))
}

// WorkerIDHasSuffix applies the HasSuffix predicate on the "worker_id" field.
func WorkerIDHasSuffix(v string) predicate.CodexThreadControl {
	return predicate.CodexThreadControl(sql.FieldHasSuffix(FieldWorkerID, v))
}

// WorkerIDIsNil applies the IsNil predicate on the "worker_id" field.
func WorkerIDIsNil() predicate.CodexThreadControl {
	return predicate.CodexThreadControl(sql.FieldIsNull(FieldWorkerID))
}

// WorkerIDNotNil applies the NotNil predicate on the "worker_id" field.
func WorkerIDNotNil() predicate.CodexThreadControl {
	return predicate.CodexThreadControl(sql.FieldNotNull(FieldWorkerID))
}

// WorkerIDEqualFold applies the EqualFold predicate on the "worker_id" field.
func WorkerIDEqualFold(v string) predicate.CodexThreadControl {
	return predicate.CodexThreadControl(sql.FieldEqualFold(FieldWorkerID, v))
}

// WorkerIDContainsFold applies the ContainsFold predicate on the "worker_id" field.
func WorkerIDContainsFold(v string) predicate.CodexThreadControl {
	return predicate.CodexThreadControl(sql.FieldContainsFold(FieldWorkerID, v))
}

// LeaseTokenEQ applies the EQ predicate on the "lease_token" field.
func LeaseTokenEQ(v string) predicate.CodexThreadControl {
	return predicate.CodexThreadControl(sql.FieldEQ(FieldLeaseToken, v))
}

// LeaseTokenNEQ applies the NEQ predicate on the "lease_token" field.
func LeaseTokenNEQ(v string) predicate.CodexThreadControl {
	return predicate.CodexThreadControl(sql.FieldNEQ(FieldLeaseToken, v))
}

// LeaseTokenIn applies the In predicate on the "lease_token" field.
func LeaseTokenIn(vs ...string) predicate.CodexThreadControl {
	return predicate.CodexThreadControl(sql.FieldIn(FieldLeaseToken, vs...))
}

// LeaseTokenNotIn applies the NotIn predicate on the "lease_token" field.
func LeaseTokenNotIn(vs ...string) predicate.CodexThreadControl {
	return predicate.CodexThreadControl(sql.FieldNotIn(FieldLeaseToken, vs...))
}

// LeaseTokenGT applies the GT predicate on the "lease_token" field.
func LeaseTokenGT(v string) predicate.CodexThreadControl {
	return predicate.CodexThreadControl(sql.FieldGT(FieldLeaseToken, v))
}

// LeaseTokenGTE applies the GTE predicate on the "lease_token" field.
func LeaseTokenGTE(v string) predicate.CodexThreadControl {
	return predicate.CodexThreadControl(sql.FieldGTE(FieldLeaseToken, v))
}

// LeaseTokenLT applies the LT predicate on the "lease_token" field.
func LeaseTokenLT(v string) predicate.CodexThreadControl {
	return predicate.CodexThreadControl(sql.FieldLT(FieldLeaseToken, v))
}

// LeaseTokenLTE applies the LTE predicate on the "lease_token" field.
func LeaseTokenLTE(v string) predicate.CodexThreadControl {
	return predicate.CodexThreadControl(sql.FieldLTE(FieldLeaseToken, v))
}

// LeaseTokenContains applies the Contains predicate on the "lease_token" field.
func LeaseTokenContains(v string) predicate.CodexThreadControl {
	return predicate.CodexThreadControl(sql.FieldContains(FieldLeaseToken, v))
}

// LeaseTokenHasPrefix applies the HasPrefix predicate on the "lease_token" field.
func LeaseTokenHasPrefix(v string) predicate.CodexThreadControl {
	return predicate.CodexThreadControl(sql.FieldHasPrefix(FieldLeaseToken, v))
}

// LeaseTokenHasSuffix applies the HasSuffix predicate on the "lease_token" field.
func LeaseTokenHasSuffix(v string) predicate.CodexThreadControl {
	return predicate.CodexThreadControl(sql.FieldHasSuffix(FieldLeaseToken, v))
}

// LeaseTokenIsNil applies the IsNil predicate on the "lease_token" field.
func LeaseTokenIsNil() predicate.CodexThreadControl {
	return predicate.CodexThreadControl(sql.FieldIsNull(FieldLeaseToken))
}

// LeaseTokenNotNil applies the NotNil predicate on the "lease_token" field.
func LeaseTokenNotNil() predicate.CodexThreadControl {
	return predicate.CodexThreadControl(sql.FieldNotNull(FieldLeaseToken))
}

// LeaseTokenEqualFold applies the EqualFold predicate on the "lease_token" field.
func LeaseTokenEqualFold(v string) predicate.CodexThreadControl {
	return predicate.CodexThreadControl(sql.FieldEqualFold(FieldLeaseToken, v))
}

// LeaseTokenContainsFold applies the ContainsFold predicate on the "lease_token" field.
func LeaseTokenContainsFold(v string) predicate.CodexThreadControl {
	return predicate.CodexThreadControl(sql.FieldContainsFold(FieldLeaseToken, v))
}

// LastErrorCodeEQ applies the EQ predicate on the "last_error_code" field.
func LastErrorCodeEQ(v string) predicate.CodexThreadControl {
	return predicate.CodexThreadControl(sql.FieldEQ(FieldLastErrorCode, v))
}

// LastErrorCodeNEQ applies the NEQ predicate on the "last_error_code" field.
func LastErrorCodeNEQ(v string) predicate.CodexThreadControl {
	return predicate.CodexThreadControl(sql.FieldNEQ(FieldLastErrorCode, v))
}

// LastErrorCodeIn applies the In predicate on the "last_error_code" field.
func LastErrorCodeIn(vs ...string) predicate.CodexThreadControl {
	return predicate.CodexThreadControl(sql.FieldIn(FieldLastErrorCode, vs...))
}

// LastErrorCodeNotIn applies the NotIn predicate on the "last_error_code" field.
func LastErrorCodeNotIn(vs ...string) predicate.CodexThreadControl {
	return predicate.CodexThreadControl(sql.FieldNotIn(FieldLastErrorCode, vs...))
}

// LastErrorCodeGT applies the GT predicate on the "last_error_code" field.
func LastErrorCodeGT(v string) predicate.CodexThreadControl {
	return predicate.CodexThreadControl(sql.FieldGT(FieldLastErrorCode, v))
}

// LastErrorCodeGTE applies the GTE predicate on the "last_error_code" field.
func LastErrorCodeGTE(v string) predicate.CodexThreadControl {
	return predicate.CodexThreadControl(sql.FieldGTE(FieldLastErrorCode, v))
}

// LastErrorCodeLT applies the LT predicate on the "last_error_code" field.
func LastErrorCodeLT(v string) predicate.CodexThreadControl {
	return predicate.CodexThreadControl(sql.FieldLT(FieldLastErrorCode, v))
}

// LastErrorCodeLTE applies the LTE predicate on the "last_error_code" field.
func LastErrorCodeLTE(v string) predicate.CodexThreadControl {
	return predicate.CodexThreadControl(sql.FieldLTE(FieldLastErrorCode, v))
}

// LastErrorCodeContains applies the Contains predicate on the "last_error_code" field.
func LastErrorCodeContains(v string) predicate.CodexThreadControl {
	return predicate.CodexThreadControl(sql.FieldContains(FieldLastErrorCode, v))
}

// LastErrorCodeHasPrefix applies the HasPrefix predicate on the "last_error_code" field.
func LastErrorCodeHasPrefix(v string) predicate.CodexThreadControl {
	return predicate.CodexThreadControl(sql.FieldHasPrefix(FieldLastErrorCode, v))
}

// LastErrorCodeHasSuffix applies the HasSuffix predicate on the "last_error_code" field.
func LastErrorCodeHasSuffix(v string) predicate.CodexThreadControl {
	return predicate.CodexThreadControl(sql.FieldHasSuffix(FieldLastErrorCode, v))
}

// LastErrorCodeIsNil applies the IsNil predicate on the "last_error_code" field.
func LastErrorCodeIsNil() predicate.CodexThreadControl {
	return predicate.CodexThreadControl(sql.FieldIsNull(FieldLastErrorCode))
}

// LastErrorCodeNotNil applies the NotNil predicate on the "last_error_code" field.
func LastErrorCodeNotNil() predicate.CodexThreadControl {
	return predicate.CodexThreadControl(sql.FieldNotNull(FieldLastErrorCode))
}

// LastErrorCodeEqualFold applies the EqualFold predicate on the "last_error_code" field.
func LastErrorCodeEqualFold(v string) predicate.CodexThreadControl {
	return predicate.CodexThreadControl(sql.FieldEqualFold(FieldLastErrorCode, v))
}

// LastErrorCodeContainsFold applies the ContainsFold predicate on the "last_error_code" field.
func LastErrorCodeContainsFold(v string) predicate.CodexThreadControl {
	return predicate.CodexThreadControl(sql.FieldContainsFold(FieldLastErrorCode, v))
}

// LastErrorMessageEQ applies the EQ predicate on the "last_error_message" field.
func LastErrorMessageEQ(v string) predicate.CodexThreadControl {
	return predicate.CodexThreadControl(sql.FieldEQ(FieldLastErrorMessage, v))
}

// LastErrorMessageNEQ applies the NEQ predicate on the "last_error_message" field.
func LastErrorMessageNEQ(v string) predicate.CodexThreadControl {
	return predicate.CodexThreadControl(sql.FieldNEQ(FieldLastErrorMessage, v))
}

// LastErrorMessageIn applies the In predicate on the "last_error_message" field.
func LastErrorMessageIn(vs ...string) predicate.CodexThreadControl {
	return predicate.CodexThreadControl(sql.FieldIn(FieldLastErrorMessage, vs...))
}

// LastErrorMessageNotIn applies the NotIn predicate on the "last_error_message" field.
func LastErrorMessageNotIn(vs ...string) predicate.CodexThreadControl {
	return predicate.CodexThreadControl(sql.FieldNotIn(FieldLastErrorMessage, vs...))
}

// LastErrorMessageGT applies the GT predicate on the "last_error_message" field.
func LastErrorMessageGT(v string) predicate.CodexThreadControl {
	return predicate.CodexThreadControl(sql.FieldGT(FieldLastErrorMessage, v))
}

// LastErrorMessageGTE applies the GTE predicate on the "last_error_message" field.
func LastErrorMessageGTE(v string) predicate.CodexThreadControl {
	return predicate.CodexThreadControl(sql.FieldGTE(FieldLastErrorMessage, v))
}

// LastErrorMessageLT applies the LT predicate on the "last_error_message" field.
func LastErrorMessageLT(v string) predicate.CodexThreadControl {
	return predicate.CodexThreadControl(sql.FieldLT(FieldLastErrorMessage, v))
}

// LastErrorMessageLTE applies the LTE predicate on the "last_error_message" field.
func LastErrorMessageLTE(v string) predicate.CodexThreadControl {
	return predicate.CodexThreadControl(sql.FieldLTE(FieldLastErrorMessage, v))
}

// LastErrorMessageContains applies the Contains predicate on the "last_error_message" field.
func LastErrorMessageContains(v string) predicate.CodexThreadControl {
	return predicate.CodexThreadControl(sql.FieldContains(FieldLastErrorMessage, v))
}

// LastErrorMessageHasPrefix applies the HasPrefix predicate on the "last_error_message" field.
func LastErrorMessageHasPrefix(v string) predicate.CodexThreadControl {
	return predicate.CodexThreadControl(sql.FieldHasPrefix(FieldLastErrorMessage, v))
}

// LastErrorMessageHasSuffix applies the HasSuffix predicate on the "last_error_message" field.
func LastErrorMessageHasSuffix(v string) predicate.CodexThreadControl {
	return predicate.CodexThreadControl(sql.FieldHasSuffix(FieldLastErrorMessage, v))
}

// LastErrorMessageIsNil applies the IsNil predicate on the "last_error_message" field.
func LastErrorMessageIsNil() predicate.CodexThreadControl {
	return predicate.CodexThreadControl(sql.FieldIsNull(FieldLastErrorMessage))
}

// LastErrorMessageNotNil applies the NotNil predicate on the "last_error_message" field.
func LastErrorMessageNotNil() predicate.CodexThreadControl {
	return predicate.CodexThreadControl(sql.FieldNotNull(FieldLastErrorMessage))
}

// LastErrorMessageEqualFold applies the EqualFold predicate on the "last_error_message" field.
func LastErrorMessageEqualFold(v string) predicate.CodexThreadControl {
	return predicate.CodexThreadControl(sql.FieldEqualFold(FieldLastErrorMessage, v))
}

// LastErrorMessageContainsFold applies the ContainsFold predicate on the "last_error_message" field.
func LastErrorMessageContainsFold(v string) predicate.CodexThreadControl {
	return predicate.CodexThreadControl(sql.FieldContainsFold(FieldLastErrorMessage, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.CodexThreadControl {
	return predicate.CodexThreadControl(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.CodexThreadControl {
	return predicate.CodexThreadControl(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.CodexThreadControl {
	return predicate.CodexThreadControl(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.CodexThreadControl {
	return predicate.CodexThreadControl(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.CodexThreadControl {
	return predicate.CodexThreadControl(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.CodexThreadControl {
	return predicate.CodexThreadControl(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.CodexThreadControl {
	return predicate.CodexThreadControl(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.CodexThreadControl {
	return predicate.CodexThreadControl(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.CodexThreadControl {
	return predicate.CodexThreadControl(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.CodexThreadControl {
	return predicate.CodexThreadControl(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.CodexThreadControl {
	return predicate.CodexThreadControl(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.CodexThreadControl {
	return predicate.CodexThreadControl(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.CodexThreadControl {
	return predicate.CodexThreadControl(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.CodexThreadControl {
	return predicate.CodexThreadControl(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.CodexThreadControl {
	return predicate.CodexThreadControl(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.CodexThreadControl {
	return predicate.CodexThreadControl(sql.FieldLTE(FieldUpdatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.CodexThreadControl) predicate.CodexThreadControl {
	return predicate.CodexThreadControl(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.CodexThreadControl) predicate.CodexThreadControl {
	return predicate.CodexThreadControl(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.CodexThreadControl) predicate.CodexThreadControl {
	return predicate.CodexThreadControl(sql.NotPredicates(p))
}
