// Package openapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package openapi

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/gin-gonic/gin"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	SessionCookieScopes = "sessionCookie.Scopes"
)

// Defines values for AgentProviderSettingsProviderType.
const (
	AgentProviderSettingsProviderTypeApiKey     AgentProviderSettingsProviderType = "api-key"
	AgentProviderSettingsProviderTypeDeviceCode AgentProviderSettingsProviderType = "device-code"
)

// Defines values for AgentProviderSettingsInputProviderType.
const (
	AgentProviderSettingsInputProviderTypeApiKey     AgentProviderSettingsInputProviderType = "api-key"
	AgentProviderSettingsInputProviderTypeDeviceCode AgentProviderSettingsInputProviderType = "device-code"
)

// Defines values for DiscordInitializationInputMode.
const (
	DiscordInitializationInputModeFresh       DiscordInitializationInputMode = "fresh"
	DiscordInitializationInputModeIncremental DiscordInitializationInputMode = "incremental"
)

// Defines values for DiscordPreflightMode.
const (
	DiscordPreflightModeFresh       DiscordPreflightMode = "fresh"
	DiscordPreflightModeIncremental DiscordPreflightMode = "incremental"
)

// Defines values for TriggerRuleInputActorMinPermission.
const (
	Admin    TriggerRuleInputActorMinPermission = "admin"
	Maintain TriggerRuleInputActorMinPermission = "maintain"
	Read     TriggerRuleInputActorMinPermission = "read"
	Triage   TriggerRuleInputActorMinPermission = "triage"
	Write    TriggerRuleInputActorMinPermission = "write"
)

// Defines values for TriggerRuleInputTriggerKind.
const (
	Event          TriggerRuleInputTriggerKind = "event"
	Label          TriggerRuleInputTriggerKind = "label"
	LegacyMention  TriggerRuleInputTriggerKind = "legacy_mention"
	MentionCommand TriggerRuleInputTriggerKind = "mention_command"
	SlashCommand   TriggerRuleInputTriggerKind = "slash_command"
)

// Defines values for PutDiscordForumAccessJSONBodyAccessLevel.
const (
	Operator PutDiscordForumAccessJSONBodyAccessLevel = "operator"
	Readonly PutDiscordForumAccessJSONBodyAccessLevel = "readonly"
)

// Administrator defines model for Administrator.
type Administrator struct {
	CsrfToken string             `json:"csrfToken"`
	ExpiresAt time.Time          `json:"expiresAt"`
	Id        openapi_types.UUID `json:"id"`
	Username  string             `json:"username"`
}

// AgentProviderSettings defines model for AgentProviderSettings.
type AgentProviderSettings struct {
	BaseUrl         *string                           `json:"baseUrl,omitempty"`
	ConfigSignature *string                           `json:"configSignature,omitempty"`
	Configured      bool                              `json:"configured"`
	Model           *string                           `json:"model,omitempty"`
	ProviderType    AgentProviderSettingsProviderType `json:"providerType"`
	ProxyUrl        *string                           `json:"proxyUrl,omitempty"`
	ReasoningEffort *string                           `json:"reasoningEffort,omitempty"`
	ServiceTier     *string                           `json:"serviceTier,omitempty"`
}

// AgentProviderSettingsProviderType defines model for AgentProviderSettings.ProviderType.
type AgentProviderSettingsProviderType string

// AgentProviderSettingsInput defines model for AgentProviderSettingsInput.
type AgentProviderSettingsInput struct {
	ApiKey          *string                                `json:"apiKey,omitempty"`
	BaseUrl         *string                                `json:"baseUrl,omitempty"`
	ConfigSignature *string                                `json:"configSignature,omitempty"`
	Configured      bool                                   `json:"configured"`
	Model           *string                                `json:"model,omitempty"`
	ProviderType    AgentProviderSettingsInputProviderType `json:"providerType"`
	ProxyUrl        *string                                `json:"proxyUrl,omitempty"`
	ReasoningEffort *string                                `json:"reasoningEffort,omitempty"`
	ServiceTier     *string                                `json:"serviceTier,omitempty"`
}

// AgentProviderSettingsInputProviderType defines model for AgentProviderSettingsInput.ProviderType.
type AgentProviderSettingsInputProviderType string

// DiscordConflict defines model for DiscordConflict.
type DiscordConflict struct {
	Name   string `json:"name"`
	Reason string `json:"reason"`
}

// DiscordDevelopmentDeletePreflight defines model for DiscordDevelopmentDeletePreflight.
type DiscordDevelopmentDeletePreflight struct {
	Active             bool               `json:"active"`
	Confirmation       string             `json:"confirmation"`
	DeletesEnvironment bool               `json:"deletesEnvironment"`
	Dirty              bool               `json:"dirty"`
	ForumId            openapi_types.UUID `json:"forumId"`
	Unpushed           bool               `json:"unpushed"`
}

// DiscordDevelopmentEnvironment defines model for DiscordDevelopmentEnvironment.
type DiscordDevelopmentEnvironment struct {
	BuildRepository    string                    `json:"buildRepository"`
	BuildRepositoryId  openapi_types.UUID        `json:"buildRepositoryId"`
	BuildSourceSha     *string                   `json:"buildSourceSha,omitempty"`
	Error              *string                   `json:"error,omitempty"`
	Forums             []DiscordDevelopmentForum `json:"forums"`
	Id                 openapi_types.UUID        `json:"id"`
	ImageId            *string                   `json:"imageId,omitempty"`
	LastUsedAt         time.Time                 `json:"lastUsedAt"`
	OwnerDiscordUserId string                    `json:"ownerDiscordUserId"`
	OwnerName          string                    `json:"ownerName"`
	RuntimeUser        *string                   `json:"runtimeUser,omitempty"`
	Status             string                    `json:"status"`
}

// DiscordDevelopmentForum defines model for DiscordDevelopmentForum.
type DiscordDevelopmentForum struct {
	Branch       string             `json:"branch"`
	Dirty        bool               `json:"dirty"`
	DiscordId    string             `json:"discordId"`
	Error        *string            `json:"error,omitempty"`
	Id           openapi_types.UUID `json:"id"`
	Name         string             `json:"name"`
	Repository   string             `json:"repository"`
	RepositoryId openapi_types.UUID `json:"repositoryId"`
	Status       string             `json:"status"`
}

// DiscordInitialization defines model for DiscordInitialization.
type DiscordInitialization struct {
	CreatedAt time.Time          `json:"createdAt"`
	Error     *string            `json:"error,omitempty"`
	GuildId   string             `json:"guildId"`
	Id        openapi_types.UUID `json:"id"`
	Mode      string             `json:"mode"`
	Preflight DiscordPreflight   `json:"preflight"`
	Status    string             `json:"status"`
	UpdatedAt time.Time          `json:"updatedAt"`
}

// DiscordInitializationInput defines model for DiscordInitializationInput.
type DiscordInitializationInput struct {
	Confirmation *string                        `json:"confirmation,omitempty"`
	Mode         DiscordInitializationInputMode `json:"mode"`
}

// DiscordInitializationInputMode defines model for DiscordInitializationInput.Mode.
type DiscordInitializationInputMode string

// DiscordMember defines model for DiscordMember.
type DiscordMember struct {
	Bound         bool    `json:"bound"`
	DiscordUserId string  `json:"discordUserId"`
	DisplayName   string  `json:"displayName"`
	GithubLogin   *string `json:"githubLogin,omitempty"`
	GuildId       string  `json:"guildId"`
	Username      string  `json:"username"`
}

// DiscordPreflight defines model for DiscordPreflight.
type DiscordPreflight struct {
	ChannelCount       int                  `json:"channelCount"`
	Conflicts          []DiscordConflict    `json:"conflicts"`
	Creates            []string             `json:"creates"`
	Deletes            []string             `json:"deletes"`
	GuildId            string               `json:"guildId"`
	MissingPermissions []string             `json:"missingPermissions"`
	Mode               DiscordPreflightMode `json:"mode"`
	Safe               bool                 `json:"safe"`
	Updates            []string             `json:"updates"`
}

// DiscordPreflightMode defines model for DiscordPreflight.Mode.
type DiscordPreflightMode string

// DiscordSettings defines model for DiscordSettings.
type DiscordSettings struct {
	ApplicationId    *string `json:"applicationId,omitempty"`
	BotUserId        *string `json:"botUserId,omitempty"`
	CommunityEnabled bool    `json:"communityEnabled"`
	Enabled          bool    `json:"enabled"`
	GuildId          string  `json:"guildId"`
	TokenConfigured  bool    `json:"tokenConfigured"`
}

// DiscordSettingsInput defines model for DiscordSettingsInput.
type DiscordSettingsInput struct {
	ApplicationId *string `json:"applicationId,omitempty"`
	BotToken      *string `json:"botToken,omitempty"`
	BotUserId     *string `json:"botUserId,omitempty"`
	Enabled       bool    `json:"enabled"`
	GuildId       string  `json:"guildId"`
}

// DiscordStatus defines model for DiscordStatus.
type DiscordStatus struct {
	Configured                      bool       `json:"configured"`
	Enabled                         bool       `json:"enabled"`
	FailedOutbox                    int64      `json:"failedOutbox"`
	GatewayError                    *string    `json:"gatewayError,omitempty"`
	GatewayStatus                   string     `json:"gatewayStatus"`
	LastGatewayAt                   *time.Time `json:"lastGatewayAt,omitempty"`
	PendingInitializationOperations int64      `json:"pendingInitializationOperations"`
	PendingOutbox                   int64      `json:"pendingOutbox"`
}

// GitHubAppInput defines model for GitHubAppInput.
type GitHubAppInput struct {
	AppId         int64   `json:"appId"`
	AppSlug       string  `json:"appSlug"`
	ClientId      *string `json:"clientId,omitempty"`
	ClientSecret  *string `json:"clientSecret,omitempty"`
	PrivateKey    *string `json:"privateKey,omitempty"`
	WebhookSecret *string `json:"webhookSecret,omitempty"`
}

// GitHubAppStatus defines model for GitHubAppStatus.
type GitHubAppStatus struct {
	AppId      *int64  `json:"appId,omitempty"`
	AppSlug    *string `json:"appSlug,omitempty"`
	ClientId   *string `json:"clientId,omitempty"`
	Configured bool    `json:"configured"`
}

// IDResource defines model for IDResource.
type IDResource struct {
	Id openapi_types.UUID `json:"id"`
}

// LoginRequest defines model for LoginRequest.
type LoginRequest struct {
	Password string `json:"password"`
	Totp     string `json:"totp"`
	Username string `json:"username"`
}

// LoginResult defines model for LoginResult.
type LoginResult struct {
	CsrfToken string    `json:"csrfToken"`
	ExpiresAt time.Time `json:"expiresAt"`
	Username  string    `json:"username"`
}

// ProblemDetails defines model for ProblemDetails.
type ProblemDetails struct {
	Detail    *string `json:"detail,omitempty"`
	Instance  *string `json:"instance,omitempty"`
	RequestId *string `json:"requestId,omitempty"`
	Status    int     `json:"status"`
	Title     string  `json:"title"`
	Type      string  `json:"type"`
}

// RepositoryInput defines model for RepositoryInput.
type RepositoryInput struct {
	AccountLogin           string  `json:"accountLogin"`
	AccountType            *string `json:"accountType,omitempty"`
	CloneUrl               string  `json:"cloneUrl"`
	DefaultBranch          string  `json:"defaultBranch"`
	InstallationExternalId int64   `json:"installationExternalId"`
	Name                   string  `json:"name"`
	Owner                  string  `json:"owner"`
	RepositoryExternalId   int64   `json:"repositoryExternalId"`
}

// SetupRequest defines model for SetupRequest.
type SetupRequest struct {
	Password   string `json:"password"`
	SetupToken string `json:"setupToken"`
	Username   string `json:"username"`
}

// SetupResult defines model for SetupResult.
type SetupResult struct {
	ProvisioningUri string   `json:"provisioningUri"`
	RecoveryCodes   []string `json:"recoveryCodes"`
	TotpSecret      string   `json:"totpSecret"`
}

// SetupStatus defines model for SetupStatus.
type SetupStatus struct {
	GithubConfigured bool `json:"githubConfigured"`
	SetupRequired    bool `json:"setupRequired"`
}

// TriggerRuleInput defines model for TriggerRuleInput.
type TriggerRuleInput struct {
	Action             *string                             `json:"action,omitempty"`
	ActorMinPermission *TriggerRuleInputActorMinPermission `json:"actorMinPermission,omitempty"`
	AgentProfileId     openapi_types.UUID                  `json:"agentProfileId"`
	AllowedTools       *[]string                           `json:"allowedTools,omitempty"`
	DangerousActions   *[]string                           `json:"dangerousActions,omitempty"`
	Enabled            *bool                               `json:"enabled,omitempty"`
	EventName          string                              `json:"eventName"`
	Filters            *map[string]interface{}             `json:"filters,omitempty"`
	Instruction        string                              `json:"instruction"`
	Name               string                              `json:"name"`
	Priority           *int                                `json:"priority,omitempty"`
	RepositoryId       openapi_types.UUID                  `json:"repositoryId"`
	Skills             *[]string                           `json:"skills,omitempty"`
	TriggerKind        TriggerRuleInputTriggerKind         `json:"triggerKind"`

	// TriggerValue Label 名或不带斜杠的命令名；event、mention_command 与 legacy_mention 留空。
	TriggerValue *string `json:"triggerValue,omitempty"`
}

// TriggerRuleInputActorMinPermission defines model for TriggerRuleInput.ActorMinPermission.
type TriggerRuleInputActorMinPermission string

// TriggerRuleInputTriggerKind defines model for TriggerRuleInput.TriggerKind.
type TriggerRuleInputTriggerKind string

// CSRFToken defines model for CSRFToken.
type CSRFToken = string

// Problem defines model for Problem.
type Problem = ProblemDetails

// LogoutParams defines parameters for Logout.
type LogoutParams struct {
	XCSRFToken CSRFToken `json:"X-CSRF-Token"`
}

// RebuildDiscordDevelopmentEnvironmentParams defines parameters for RebuildDiscordDevelopmentEnvironment.
type RebuildDiscordDevelopmentEnvironmentParams struct {
	XCSRFToken CSRFToken `json:"X-CSRF-Token"`
}

// DeleteDiscordDevelopmentForumJSONBody defines parameters for DeleteDiscordDevelopmentForum.
type DeleteDiscordDevelopmentForumJSONBody struct {
	Confirmation string `json:"confirmation"`
}

// DeleteDiscordDevelopmentForumParams defines parameters for DeleteDiscordDevelopmentForum.
type DeleteDiscordDevelopmentForumParams struct {
	XCSRFToken CSRFToken `json:"X-CSRF-Token"`
}

// DeleteDiscordForumAccessParams defines parameters for DeleteDiscordForumAccess.
type DeleteDiscordForumAccessParams struct {
	XCSRFToken CSRFToken `json:"X-CSRF-Token"`
}

// PutDiscordForumAccessJSONBody defines parameters for PutDiscordForumAccess.
type PutDiscordForumAccessJSONBody struct {
	AccessLevel PutDiscordForumAccessJSONBodyAccessLevel `json:"accessLevel"`
}

// PutDiscordForumAccessParams defines parameters for PutDiscordForumAccess.
type PutDiscordForumAccessParams struct {
	XCSRFToken CSRFToken `json:"X-CSRF-Token"`
}

// PutDiscordForumAccessJSONBodyAccessLevel defines parameters for PutDiscordForumAccess.
type PutDiscordForumAccessJSONBodyAccessLevel string

// StartDiscordGitHubBindJSONBody defines parameters for StartDiscordGitHubBind.
type StartDiscordGitHubBindJSONBody struct {
	DiscordUserId string `json:"discordUserId"`
	GuildId       string `json:"guildId"`
}

// StartDiscordGitHubBindParams defines parameters for StartDiscordGitHubBind.
type StartDiscordGitHubBindParams struct {
	XCSRFToken CSRFToken `json:"X-CSRF-Token"`
}

// CompleteDiscordGitHubBindParams defines parameters for CompleteDiscordGitHubBind.
type CompleteDiscordGitHubBindParams struct {
	State string `form:"state" json:"state"`
	Code  string `form:"code" json:"code"`
}

// UnbindDiscordGitHubJSONBody defines parameters for UnbindDiscordGitHub.
type UnbindDiscordGitHubJSONBody struct {
	Confirmed     bool   `json:"confirmed"`
	DiscordUserId string `json:"discordUserId"`
	GuildId       string `json:"guildId"`
}

// UnbindDiscordGitHubParams defines parameters for UnbindDiscordGitHub.
type UnbindDiscordGitHubParams struct {
	XCSRFToken CSRFToken `json:"X-CSRF-Token"`
}

// CreateDiscordInitializationParams defines parameters for CreateDiscordInitialization.
type CreateDiscordInitializationParams struct {
	XCSRFToken CSRFToken `json:"X-CSRF-Token"`
}

// PreflightDiscordInitializationParams defines parameters for PreflightDiscordInitialization.
type PreflightDiscordInitializationParams struct {
	XCSRFToken CSRFToken `json:"X-CSRF-Token"`
}

// CreateDiscordMemberForumJSONBody defines parameters for CreateDiscordMemberForum.
type CreateDiscordMemberForumJSONBody struct {
	Name         *string            `json:"name,omitempty"`
	RepositoryId openapi_types.UUID `json:"repositoryId"`
}

// CreateDiscordMemberForumParams defines parameters for CreateDiscordMemberForum.
type CreateDiscordMemberForumParams struct {
	XCSRFToken CSRFToken `json:"X-CSRF-Token"`
}

// PutGitHubAppParams defines parameters for PutGitHubApp.
type PutGitHubAppParams struct {
	XCSRFToken CSRFToken `json:"X-CSRF-Token"`
}

// GithubAppManifestCallbackParams defines parameters for GithubAppManifestCallback.
type GithubAppManifestCallbackParams struct {
	Code string `form:"code" json:"code"`
}

// CallInternalToolJSONBody defines parameters for CallInternalTool.
type CallInternalToolJSONBody map[string]interface{}

// CreateRepositoryParams defines parameters for CreateRepository.
type CreateRepositoryParams struct {
	XCSRFToken CSRFToken `json:"X-CSRF-Token"`
}

// PutAgentProviderSettingsParams defines parameters for PutAgentProviderSettings.
type PutAgentProviderSettingsParams struct {
	XCSRFToken CSRFToken `json:"X-CSRF-Token"`
}

// PutDiscordSettingsParams defines parameters for PutDiscordSettings.
type PutDiscordSettingsParams struct {
	XCSRFToken CSRFToken `json:"X-CSRF-Token"`
}

// CreateTriggerRuleParams defines parameters for CreateTriggerRule.
type CreateTriggerRuleParams struct {
	XCSRFToken CSRFToken `json:"X-CSRF-Token"`
}

// ReceiveGitHubWebhookJSONBody defines parameters for ReceiveGitHubWebhook.
type ReceiveGitHubWebhookJSONBody map[string]interface{}

// ReceiveGitHubWebhookParams defines parameters for ReceiveGitHubWebhook.
type ReceiveGitHubWebhookParams struct {
	XHubSignature256 string `json:"X-Hub-Signature-256"`
	XGitHubDelivery  string `json:"X-GitHub-Delivery"`
	XGitHubEvent     string `json:"X-GitHub-Event"`
}

// LoginJSONRequestBody defines body for Login for application/json ContentType.
type LoginJSONRequestBody = LoginRequest

// DeleteDiscordDevelopmentForumJSONRequestBody defines body for DeleteDiscordDevelopmentForum for application/json ContentType.
type DeleteDiscordDevelopmentForumJSONRequestBody DeleteDiscordDevelopmentForumJSONBody

// PutDiscordForumAccessJSONRequestBody defines body for PutDiscordForumAccess for application/json ContentType.
type PutDiscordForumAccessJSONRequestBody PutDiscordForumAccessJSONBody

// StartDiscordGitHubBindJSONRequestBody defines body for StartDiscordGitHubBind for application/json ContentType.
type StartDiscordGitHubBindJSONRequestBody StartDiscordGitHubBindJSONBody

// UnbindDiscordGitHubJSONRequestBody defines body for UnbindDiscordGitHub for application/json ContentType.
type UnbindDiscordGitHubJSONRequestBody UnbindDiscordGitHubJSONBody

// CreateDiscordInitializationJSONRequestBody defines body for CreateDiscordInitialization for application/json ContentType.
type CreateDiscordInitializationJSONRequestBody = DiscordInitializationInput

// PreflightDiscordInitializationJSONRequestBody defines body for PreflightDiscordInitialization for application/json ContentType.
type PreflightDiscordInitializationJSONRequestBody = DiscordInitializationInput

// CreateDiscordMemberForumJSONRequestBody defines body for CreateDiscordMemberForum for application/json ContentType.
type CreateDiscordMemberForumJSONRequestBody CreateDiscordMemberForumJSONBody

// PutGitHubAppJSONRequestBody defines body for PutGitHubApp for application/json ContentType.
type PutGitHubAppJSONRequestBody = GitHubAppInput

// CallInternalToolJSONRequestBody defines body for CallInternalTool for application/json ContentType.
type CallInternalToolJSONRequestBody CallInternalToolJSONBody

// CreateRepositoryJSONRequestBody defines body for CreateRepository for application/json ContentType.
type CreateRepositoryJSONRequestBody = RepositoryInput

// PutAgentProviderSettingsJSONRequestBody defines body for PutAgentProviderSettings for application/json ContentType.
type PutAgentProviderSettingsJSONRequestBody = AgentProviderSettingsInput

// PutDiscordSettingsJSONRequestBody defines body for PutDiscordSettings for application/json ContentType.
type PutDiscordSettingsJSONRequestBody = DiscordSettingsInput

// SetupAdministratorJSONRequestBody defines body for SetupAdministrator for application/json ContentType.
type SetupAdministratorJSONRequestBody = SetupRequest

// CreateTriggerRuleJSONRequestBody defines body for CreateTriggerRule for application/json ContentType.
type CreateTriggerRuleJSONRequestBody = TriggerRuleInput

// ReceiveGitHubWebhookJSONRequestBody defines body for ReceiveGitHubWebhook for application/json ContentType.
type ReceiveGitHubWebhookJSONRequestBody ReceiveGitHubWebhookJSONBody

// ServerInterface represents all server handlers.
type ServerInterface interface {

	// (GET /agent-profiles)
	GetAgentProfiles(c *gin.Context)

	// (POST /agent-profiles)
	PostAgentProfiles(c *gin.Context)

	// (GET /audit-logs)
	GetAuditLogs(c *gin.Context)

	// (POST /auth/login)
	Login(c *gin.Context)

	// (POST /auth/logout)
	Logout(c *gin.Context, params LogoutParams)

	// (GET /auth/me)
	GetCurrentAdministrator(c *gin.Context)

	// (GET /discord/development-environments)
	ListDiscordDevelopmentEnvironments(c *gin.Context)

	// (POST /discord/development-environments/{id}/rebuild)
	RebuildDiscordDevelopmentEnvironment(c *gin.Context, id openapi_types.UUID, params RebuildDiscordDevelopmentEnvironmentParams)

	// (POST /discord/development-forums/{id}/delete)
	DeleteDiscordDevelopmentForum(c *gin.Context, id openapi_types.UUID, params DeleteDiscordDevelopmentForumParams)

	// (GET /discord/development-forums/{id}/delete-preflight)
	PreflightDiscordDevelopmentForumDeletion(c *gin.Context, id openapi_types.UUID)

	// (DELETE /discord/forums/{forumId}/access/{memberId})
	DeleteDiscordForumAccess(c *gin.Context, forumId openapi_types.UUID, memberId string, params DeleteDiscordForumAccessParams)

	// (PUT /discord/forums/{forumId}/access/{memberId})
	PutDiscordForumAccess(c *gin.Context, forumId openapi_types.UUID, memberId string, params PutDiscordForumAccessParams)

	// (POST /discord/github/bind)
	StartDiscordGitHubBind(c *gin.Context, params StartDiscordGitHubBindParams)

	// (GET /discord/github/bind/callback)
	CompleteDiscordGitHubBind(c *gin.Context, params CompleteDiscordGitHubBindParams)

	// (POST /discord/github/unbind)
	UnbindDiscordGitHub(c *gin.Context, params UnbindDiscordGitHubParams)

	// (POST /discord/initializations)
	CreateDiscordInitialization(c *gin.Context, params CreateDiscordInitializationParams)

	// (POST /discord/initializations/preflight)
	PreflightDiscordInitialization(c *gin.Context, params PreflightDiscordInitializationParams)

	// (GET /discord/initializations/{id})
	GetDiscordInitialization(c *gin.Context, id openapi_types.UUID)

	// (GET /discord/members)
	ListDiscordMembers(c *gin.Context)

	// (POST /discord/members/{id}/forum)
	CreateDiscordMemberForum(c *gin.Context, id string, params CreateDiscordMemberForumParams)

	// (GET /discord/status)
	GetDiscordStatus(c *gin.Context)

	// (GET /events/stream)
	StreamEvents(c *gin.Context)

	// (GET /github/app)
	GetGitHubApp(c *gin.Context)

	// (PUT /github/app)
	PutGitHubApp(c *gin.Context, params PutGitHubAppParams)

	// (GET /github/app/manifest)
	GetGitHubAppManifest(c *gin.Context)

	// (GET /github/app/manifest/callback)
	GithubAppManifestCallback(c *gin.Context, params GithubAppManifestCallbackParams)

	// (GET /installations)
	GetInstallations(c *gin.Context)

	// (POST /internal/v1/tools/call)
	CallInternalTool(c *gin.Context)

	// (GET /jobs)
	GetJobs(c *gin.Context)

	// (GET /repo-caches)
	GetRepoCaches(c *gin.Context)

	// (GET /repositories)
	GetRepositories(c *gin.Context)

	// (POST /repositories)
	CreateRepository(c *gin.Context, params CreateRepositoryParams)

	// (GET /settings/agent-provider)
	GetAgentProviderSettings(c *gin.Context)

	// (PUT /settings/agent-provider)
	PutAgentProviderSettings(c *gin.Context, params PutAgentProviderSettingsParams)

	// (GET /settings/discord)
	GetDiscordSettings(c *gin.Context)

	// (PUT /settings/discord)
	PutDiscordSettings(c *gin.Context, params PutDiscordSettingsParams)

	// (POST /setup/admin)
	SetupAdministrator(c *gin.Context)

	// (GET /setup/status)
	GetSetupStatus(c *gin.Context)

	// (GET /system/status)
	GetSystemStatus(c *gin.Context)

	// (GET /threads)
	GetThreads(c *gin.Context)

	// (GET /trigger-rules)
	GetTriggerRules(c *gin.Context)

	// (POST /trigger-rules)
	CreateTriggerRule(c *gin.Context, params CreateTriggerRuleParams)

	// (POST /webhooks/github)
	ReceiveGitHubWebhook(c *gin.Context, params ReceiveGitHubWebhookParams)

	// (GET /work-items)
	GetWorkItems(c *gin.Context)

	// (GET /workers)
	GetWorkers(c *gin.Context)

	// (GET /worktrees)
	GetWorktrees(c *gin.Context)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandler       func(*gin.Context, error, int)
}

type MiddlewareFunc func(c *gin.Context)

// GetAgentProfiles operation middleware
func (siw *ServerInterfaceWrapper) GetAgentProfiles(c *gin.Context) {

	c.Set(SessionCookieScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetAgentProfiles(c)
}

// PostAgentProfiles operation middleware
func (siw *ServerInterfaceWrapper) PostAgentProfiles(c *gin.Context) {

	c.Set(SessionCookieScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PostAgentProfiles(c)
}

// GetAuditLogs operation middleware
func (siw *ServerInterfaceWrapper) GetAuditLogs(c *gin.Context) {

	c.Set(SessionCookieScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetAuditLogs(c)
}

// Login operation middleware
func (siw *ServerInterfaceWrapper) Login(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.Login(c)
}

// Logout operation middleware
func (siw *ServerInterfaceWrapper) Logout(c *gin.Context) {

	var err error

	c.Set(SessionCookieScopes, []string{})

	// Parameter object where we will unmarshal all parameters from the context
	var params LogoutParams

	headers := c.Request.Header

	// ------------- Required header parameter "X-CSRF-Token" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-CSRF-Token")]; found {
		var XCSRFToken CSRFToken
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandler(c, fmt.Errorf("Expected one value for X-CSRF-Token, got %d", n), http.StatusBadRequest)
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "X-CSRF-Token", valueList[0], &XCSRFToken, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true})
		if err != nil {
			siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter X-CSRF-Token: %w", err), http.StatusBadRequest)
			return
		}

		params.XCSRFToken = XCSRFToken

	} else {
		siw.ErrorHandler(c, fmt.Errorf("Header parameter X-CSRF-Token is required, but not found"), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.Logout(c, params)
}

// GetCurrentAdministrator operation middleware
func (siw *ServerInterfaceWrapper) GetCurrentAdministrator(c *gin.Context) {

	c.Set(SessionCookieScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetCurrentAdministrator(c)
}

// ListDiscordDevelopmentEnvironments operation middleware
func (siw *ServerInterfaceWrapper) ListDiscordDevelopmentEnvironments(c *gin.Context) {

	c.Set(SessionCookieScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ListDiscordDevelopmentEnvironments(c)
}

// RebuildDiscordDevelopmentEnvironment operation middleware
func (siw *ServerInterfaceWrapper) RebuildDiscordDevelopmentEnvironment(c *gin.Context) {

	var err error

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(SessionCookieScopes, []string{})

	// Parameter object where we will unmarshal all parameters from the context
	var params RebuildDiscordDevelopmentEnvironmentParams

	headers := c.Request.Header

	// ------------- Required header parameter "X-CSRF-Token" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-CSRF-Token")]; found {
		var XCSRFToken CSRFToken
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandler(c, fmt.Errorf("Expected one value for X-CSRF-Token, got %d", n), http.StatusBadRequest)
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "X-CSRF-Token", valueList[0], &XCSRFToken, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true})
		if err != nil {
			siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter X-CSRF-Token: %w", err), http.StatusBadRequest)
			return
		}

		params.XCSRFToken = XCSRFToken

	} else {
		siw.ErrorHandler(c, fmt.Errorf("Header parameter X-CSRF-Token is required, but not found"), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.RebuildDiscordDevelopmentEnvironment(c, id, params)
}

// DeleteDiscordDevelopmentForum operation middleware
func (siw *ServerInterfaceWrapper) DeleteDiscordDevelopmentForum(c *gin.Context) {

	var err error

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(SessionCookieScopes, []string{})

	// Parameter object where we will unmarshal all parameters from the context
	var params DeleteDiscordDevelopmentForumParams

	headers := c.Request.Header

	// ------------- Required header parameter "X-CSRF-Token" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-CSRF-Token")]; found {
		var XCSRFToken CSRFToken
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandler(c, fmt.Errorf("Expected one value for X-CSRF-Token, got %d", n), http.StatusBadRequest)
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "X-CSRF-Token", valueList[0], &XCSRFToken, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true})
		if err != nil {
			siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter X-CSRF-Token: %w", err), http.StatusBadRequest)
			return
		}

		params.XCSRFToken = XCSRFToken

	} else {
		siw.ErrorHandler(c, fmt.Errorf("Header parameter X-CSRF-Token is required, but not found"), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.DeleteDiscordDevelopmentForum(c, id, params)
}

// PreflightDiscordDevelopmentForumDeletion operation middleware
func (siw *ServerInterfaceWrapper) PreflightDiscordDevelopmentForumDeletion(c *gin.Context) {

	var err error

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(SessionCookieScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PreflightDiscordDevelopmentForumDeletion(c, id)
}

// DeleteDiscordForumAccess operation middleware
func (siw *ServerInterfaceWrapper) DeleteDiscordForumAccess(c *gin.Context) {

	var err error

	// ------------- Path parameter "forumId" -------------
	var forumId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "forumId", c.Param("forumId"), &forumId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter forumId: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Path parameter "memberId" -------------
	var memberId string

	err = runtime.BindStyledParameterWithOptions("simple", "memberId", c.Param("memberId"), &memberId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter memberId: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(SessionCookieScopes, []string{})

	// Parameter object where we will unmarshal all parameters from the context
	var params DeleteDiscordForumAccessParams

	headers := c.Request.Header

	// ------------- Required header parameter "X-CSRF-Token" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-CSRF-Token")]; found {
		var XCSRFToken CSRFToken
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandler(c, fmt.Errorf("Expected one value for X-CSRF-Token, got %d", n), http.StatusBadRequest)
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "X-CSRF-Token", valueList[0], &XCSRFToken, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true})
		if err != nil {
			siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter X-CSRF-Token: %w", err), http.StatusBadRequest)
			return
		}

		params.XCSRFToken = XCSRFToken

	} else {
		siw.ErrorHandler(c, fmt.Errorf("Header parameter X-CSRF-Token is required, but not found"), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.DeleteDiscordForumAccess(c, forumId, memberId, params)
}

// PutDiscordForumAccess operation middleware
func (siw *ServerInterfaceWrapper) PutDiscordForumAccess(c *gin.Context) {

	var err error

	// ------------- Path parameter "forumId" -------------
	var forumId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "forumId", c.Param("forumId"), &forumId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter forumId: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Path parameter "memberId" -------------
	var memberId string

	err = runtime.BindStyledParameterWithOptions("simple", "memberId", c.Param("memberId"), &memberId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter memberId: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(SessionCookieScopes, []string{})

	// Parameter object where we will unmarshal all parameters from the context
	var params PutDiscordForumAccessParams

	headers := c.Request.Header

	// ------------- Required header parameter "X-CSRF-Token" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-CSRF-Token")]; found {
		var XCSRFToken CSRFToken
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandler(c, fmt.Errorf("Expected one value for X-CSRF-Token, got %d", n), http.StatusBadRequest)
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "X-CSRF-Token", valueList[0], &XCSRFToken, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true})
		if err != nil {
			siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter X-CSRF-Token: %w", err), http.StatusBadRequest)
			return
		}

		params.XCSRFToken = XCSRFToken

	} else {
		siw.ErrorHandler(c, fmt.Errorf("Header parameter X-CSRF-Token is required, but not found"), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PutDiscordForumAccess(c, forumId, memberId, params)
}

// StartDiscordGitHubBind operation middleware
func (siw *ServerInterfaceWrapper) StartDiscordGitHubBind(c *gin.Context) {

	var err error

	c.Set(SessionCookieScopes, []string{})

	// Parameter object where we will unmarshal all parameters from the context
	var params StartDiscordGitHubBindParams

	headers := c.Request.Header

	// ------------- Required header parameter "X-CSRF-Token" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-CSRF-Token")]; found {
		var XCSRFToken CSRFToken
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandler(c, fmt.Errorf("Expected one value for X-CSRF-Token, got %d", n), http.StatusBadRequest)
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "X-CSRF-Token", valueList[0], &XCSRFToken, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true})
		if err != nil {
			siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter X-CSRF-Token: %w", err), http.StatusBadRequest)
			return
		}

		params.XCSRFToken = XCSRFToken

	} else {
		siw.ErrorHandler(c, fmt.Errorf("Header parameter X-CSRF-Token is required, but not found"), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.StartDiscordGitHubBind(c, params)
}

// CompleteDiscordGitHubBind operation middleware
func (siw *ServerInterfaceWrapper) CompleteDiscordGitHubBind(c *gin.Context) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params CompleteDiscordGitHubBindParams

	// ------------- Required query parameter "state" -------------

	if paramValue := c.Query("state"); paramValue != "" {

	} else {
		siw.ErrorHandler(c, fmt.Errorf("Query argument state is required, but not found"), http.StatusBadRequest)
		return
	}

	err = runtime.BindQueryParameter("form", true, true, "state", c.Request.URL.Query(), &params.State)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter state: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Required query parameter "code" -------------

	if paramValue := c.Query("code"); paramValue != "" {

	} else {
		siw.ErrorHandler(c, fmt.Errorf("Query argument code is required, but not found"), http.StatusBadRequest)
		return
	}

	err = runtime.BindQueryParameter("form", true, true, "code", c.Request.URL.Query(), &params.Code)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter code: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.CompleteDiscordGitHubBind(c, params)
}

// UnbindDiscordGitHub operation middleware
func (siw *ServerInterfaceWrapper) UnbindDiscordGitHub(c *gin.Context) {

	var err error

	c.Set(SessionCookieScopes, []string{})

	// Parameter object where we will unmarshal all parameters from the context
	var params UnbindDiscordGitHubParams

	headers := c.Request.Header

	// ------------- Required header parameter "X-CSRF-Token" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-CSRF-Token")]; found {
		var XCSRFToken CSRFToken
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandler(c, fmt.Errorf("Expected one value for X-CSRF-Token, got %d", n), http.StatusBadRequest)
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "X-CSRF-Token", valueList[0], &XCSRFToken, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true})
		if err != nil {
			siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter X-CSRF-Token: %w", err), http.StatusBadRequest)
			return
		}

		params.XCSRFToken = XCSRFToken

	} else {
		siw.ErrorHandler(c, fmt.Errorf("Header parameter X-CSRF-Token is required, but not found"), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.UnbindDiscordGitHub(c, params)
}

// CreateDiscordInitialization operation middleware
func (siw *ServerInterfaceWrapper) CreateDiscordInitialization(c *gin.Context) {

	var err error

	c.Set(SessionCookieScopes, []string{})

	// Parameter object where we will unmarshal all parameters from the context
	var params CreateDiscordInitializationParams

	headers := c.Request.Header

	// ------------- Required header parameter "X-CSRF-Token" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-CSRF-Token")]; found {
		var XCSRFToken CSRFToken
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandler(c, fmt.Errorf("Expected one value for X-CSRF-Token, got %d", n), http.StatusBadRequest)
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "X-CSRF-Token", valueList[0], &XCSRFToken, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true})
		if err != nil {
			siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter X-CSRF-Token: %w", err), http.StatusBadRequest)
			return
		}

		params.XCSRFToken = XCSRFToken

	} else {
		siw.ErrorHandler(c, fmt.Errorf("Header parameter X-CSRF-Token is required, but not found"), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.CreateDiscordInitialization(c, params)
}

// PreflightDiscordInitialization operation middleware
func (siw *ServerInterfaceWrapper) PreflightDiscordInitialization(c *gin.Context) {

	var err error

	c.Set(SessionCookieScopes, []string{})

	// Parameter object where we will unmarshal all parameters from the context
	var params PreflightDiscordInitializationParams

	headers := c.Request.Header

	// ------------- Required header parameter "X-CSRF-Token" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-CSRF-Token")]; found {
		var XCSRFToken CSRFToken
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandler(c, fmt.Errorf("Expected one value for X-CSRF-Token, got %d", n), http.StatusBadRequest)
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "X-CSRF-Token", valueList[0], &XCSRFToken, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true})
		if err != nil {
			siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter X-CSRF-Token: %w", err), http.StatusBadRequest)
			return
		}

		params.XCSRFToken = XCSRFToken

	} else {
		siw.ErrorHandler(c, fmt.Errorf("Header parameter X-CSRF-Token is required, but not found"), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PreflightDiscordInitialization(c, params)
}

// GetDiscordInitialization operation middleware
func (siw *ServerInterfaceWrapper) GetDiscordInitialization(c *gin.Context) {

	var err error

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(SessionCookieScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetDiscordInitialization(c, id)
}

// ListDiscordMembers operation middleware
func (siw *ServerInterfaceWrapper) ListDiscordMembers(c *gin.Context) {

	c.Set(SessionCookieScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ListDiscordMembers(c)
}

// CreateDiscordMemberForum operation middleware
func (siw *ServerInterfaceWrapper) CreateDiscordMemberForum(c *gin.Context) {

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(SessionCookieScopes, []string{})

	// Parameter object where we will unmarshal all parameters from the context
	var params CreateDiscordMemberForumParams

	headers := c.Request.Header

	// ------------- Required header parameter "X-CSRF-Token" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-CSRF-Token")]; found {
		var XCSRFToken CSRFToken
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandler(c, fmt.Errorf("Expected one value for X-CSRF-Token, got %d", n), http.StatusBadRequest)
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "X-CSRF-Token", valueList[0], &XCSRFToken, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true})
		if err != nil {
			siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter X-CSRF-Token: %w", err), http.StatusBadRequest)
			return
		}

		params.XCSRFToken = XCSRFToken

	} else {
		siw.ErrorHandler(c, fmt.Errorf("Header parameter X-CSRF-Token is required, but not found"), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.CreateDiscordMemberForum(c, id, params)
}

// GetDiscordStatus operation middleware
func (siw *ServerInterfaceWrapper) GetDiscordStatus(c *gin.Context) {

	c.Set(SessionCookieScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetDiscordStatus(c)
}

// StreamEvents operation middleware
func (siw *ServerInterfaceWrapper) StreamEvents(c *gin.Context) {

	c.Set(SessionCookieScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.StreamEvents(c)
}

// GetGitHubApp operation middleware
func (siw *ServerInterfaceWrapper) GetGitHubApp(c *gin.Context) {

	c.Set(SessionCookieScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetGitHubApp(c)
}

// PutGitHubApp operation middleware
func (siw *ServerInterfaceWrapper) PutGitHubApp(c *gin.Context) {

	var err error

	c.Set(SessionCookieScopes, []string{})

	// Parameter object where we will unmarshal all parameters from the context
	var params PutGitHubAppParams

	headers := c.Request.Header

	// ------------- Required header parameter "X-CSRF-Token" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-CSRF-Token")]; found {
		var XCSRFToken CSRFToken
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandler(c, fmt.Errorf("Expected one value for X-CSRF-Token, got %d", n), http.StatusBadRequest)
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "X-CSRF-Token", valueList[0], &XCSRFToken, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true})
		if err != nil {
			siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter X-CSRF-Token: %w", err), http.StatusBadRequest)
			return
		}

		params.XCSRFToken = XCSRFToken

	} else {
		siw.ErrorHandler(c, fmt.Errorf("Header parameter X-CSRF-Token is required, but not found"), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PutGitHubApp(c, params)
}

// GetGitHubAppManifest operation middleware
func (siw *ServerInterfaceWrapper) GetGitHubAppManifest(c *gin.Context) {

	c.Set(SessionCookieScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetGitHubAppManifest(c)
}

// GithubAppManifestCallback operation middleware
func (siw *ServerInterfaceWrapper) GithubAppManifestCallback(c *gin.Context) {

	var err error

	c.Set(SessionCookieScopes, []string{})

	// Parameter object where we will unmarshal all parameters from the context
	var params GithubAppManifestCallbackParams

	// ------------- Required query parameter "code" -------------

	if paramValue := c.Query("code"); paramValue != "" {

	} else {
		siw.ErrorHandler(c, fmt.Errorf("Query argument code is required, but not found"), http.StatusBadRequest)
		return
	}

	err = runtime.BindQueryParameter("form", true, true, "code", c.Request.URL.Query(), &params.Code)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter code: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GithubAppManifestCallback(c, params)
}

// GetInstallations operation middleware
func (siw *ServerInterfaceWrapper) GetInstallations(c *gin.Context) {

	c.Set(SessionCookieScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetInstallations(c)
}

// CallInternalTool operation middleware
func (siw *ServerInterfaceWrapper) CallInternalTool(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.CallInternalTool(c)
}

// GetJobs operation middleware
func (siw *ServerInterfaceWrapper) GetJobs(c *gin.Context) {

	c.Set(SessionCookieScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetJobs(c)
}

// GetRepoCaches operation middleware
func (siw *ServerInterfaceWrapper) GetRepoCaches(c *gin.Context) {

	c.Set(SessionCookieScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetRepoCaches(c)
}

// GetRepositories operation middleware
func (siw *ServerInterfaceWrapper) GetRepositories(c *gin.Context) {

	c.Set(SessionCookieScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetRepositories(c)
}

// CreateRepository operation middleware
func (siw *ServerInterfaceWrapper) CreateRepository(c *gin.Context) {

	var err error

	c.Set(SessionCookieScopes, []string{})

	// Parameter object where we will unmarshal all parameters from the context
	var params CreateRepositoryParams

	headers := c.Request.Header

	// ------------- Required header parameter "X-CSRF-Token" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-CSRF-Token")]; found {
		var XCSRFToken CSRFToken
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandler(c, fmt.Errorf("Expected one value for X-CSRF-Token, got %d", n), http.StatusBadRequest)
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "X-CSRF-Token", valueList[0], &XCSRFToken, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true})
		if err != nil {
			siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter X-CSRF-Token: %w", err), http.StatusBadRequest)
			return
		}

		params.XCSRFToken = XCSRFToken

	} else {
		siw.ErrorHandler(c, fmt.Errorf("Header parameter X-CSRF-Token is required, but not found"), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.CreateRepository(c, params)
}

// GetAgentProviderSettings operation middleware
func (siw *ServerInterfaceWrapper) GetAgentProviderSettings(c *gin.Context) {

	c.Set(SessionCookieScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetAgentProviderSettings(c)
}

// PutAgentProviderSettings operation middleware
func (siw *ServerInterfaceWrapper) PutAgentProviderSettings(c *gin.Context) {

	var err error

	c.Set(SessionCookieScopes, []string{})

	// Parameter object where we will unmarshal all parameters from the context
	var params PutAgentProviderSettingsParams

	headers := c.Request.Header

	// ------------- Required header parameter "X-CSRF-Token" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-CSRF-Token")]; found {
		var XCSRFToken CSRFToken
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandler(c, fmt.Errorf("Expected one value for X-CSRF-Token, got %d", n), http.StatusBadRequest)
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "X-CSRF-Token", valueList[0], &XCSRFToken, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true})
		if err != nil {
			siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter X-CSRF-Token: %w", err), http.StatusBadRequest)
			return
		}

		params.XCSRFToken = XCSRFToken

	} else {
		siw.ErrorHandler(c, fmt.Errorf("Header parameter X-CSRF-Token is required, but not found"), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PutAgentProviderSettings(c, params)
}

// GetDiscordSettings operation middleware
func (siw *ServerInterfaceWrapper) GetDiscordSettings(c *gin.Context) {

	c.Set(SessionCookieScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetDiscordSettings(c)
}

// PutDiscordSettings operation middleware
func (siw *ServerInterfaceWrapper) PutDiscordSettings(c *gin.Context) {

	var err error

	c.Set(SessionCookieScopes, []string{})

	// Parameter object where we will unmarshal all parameters from the context
	var params PutDiscordSettingsParams

	headers := c.Request.Header

	// ------------- Required header parameter "X-CSRF-Token" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-CSRF-Token")]; found {
		var XCSRFToken CSRFToken
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandler(c, fmt.Errorf("Expected one value for X-CSRF-Token, got %d", n), http.StatusBadRequest)
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "X-CSRF-Token", valueList[0], &XCSRFToken, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true})
		if err != nil {
			siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter X-CSRF-Token: %w", err), http.StatusBadRequest)
			return
		}

		params.XCSRFToken = XCSRFToken

	} else {
		siw.ErrorHandler(c, fmt.Errorf("Header parameter X-CSRF-Token is required, but not found"), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PutDiscordSettings(c, params)
}

// SetupAdministrator operation middleware
func (siw *ServerInterfaceWrapper) SetupAdministrator(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.SetupAdministrator(c)
}

// GetSetupStatus operation middleware
func (siw *ServerInterfaceWrapper) GetSetupStatus(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetSetupStatus(c)
}

// GetSystemStatus operation middleware
func (siw *ServerInterfaceWrapper) GetSystemStatus(c *gin.Context) {

	c.Set(SessionCookieScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetSystemStatus(c)
}

// GetThreads operation middleware
func (siw *ServerInterfaceWrapper) GetThreads(c *gin.Context) {

	c.Set(SessionCookieScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetThreads(c)
}

// GetTriggerRules operation middleware
func (siw *ServerInterfaceWrapper) GetTriggerRules(c *gin.Context) {

	c.Set(SessionCookieScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetTriggerRules(c)
}

// CreateTriggerRule operation middleware
func (siw *ServerInterfaceWrapper) CreateTriggerRule(c *gin.Context) {

	var err error

	c.Set(SessionCookieScopes, []string{})

	// Parameter object where we will unmarshal all parameters from the context
	var params CreateTriggerRuleParams

	headers := c.Request.Header

	// ------------- Required header parameter "X-CSRF-Token" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-CSRF-Token")]; found {
		var XCSRFToken CSRFToken
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandler(c, fmt.Errorf("Expected one value for X-CSRF-Token, got %d", n), http.StatusBadRequest)
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "X-CSRF-Token", valueList[0], &XCSRFToken, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true})
		if err != nil {
			siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter X-CSRF-Token: %w", err), http.StatusBadRequest)
			return
		}

		params.XCSRFToken = XCSRFToken

	} else {
		siw.ErrorHandler(c, fmt.Errorf("Header parameter X-CSRF-Token is required, but not found"), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.CreateTriggerRule(c, params)
}

// ReceiveGitHubWebhook operation middleware
func (siw *ServerInterfaceWrapper) ReceiveGitHubWebhook(c *gin.Context) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params ReceiveGitHubWebhookParams

	headers := c.Request.Header

	// ------------- Required header parameter "X-Hub-Signature-256" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-Hub-Signature-256")]; found {
		var XHubSignature256 string
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandler(c, fmt.Errorf("Expected one value for X-Hub-Signature-256, got %d", n), http.StatusBadRequest)
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "X-Hub-Signature-256", valueList[0], &XHubSignature256, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true})
		if err != nil {
			siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter X-Hub-Signature-256: %w", err), http.StatusBadRequest)
			return
		}

		params.XHubSignature256 = XHubSignature256

	} else {
		siw.ErrorHandler(c, fmt.Errorf("Header parameter X-Hub-Signature-256 is required, but not found"), http.StatusBadRequest)
		return
	}

	// ------------- Required header parameter "X-GitHub-Delivery" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-GitHub-Delivery")]; found {
		var XGitHubDelivery string
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandler(c, fmt.Errorf("Expected one value for X-GitHub-Delivery, got %d", n), http.StatusBadRequest)
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "X-GitHub-Delivery", valueList[0], &XGitHubDelivery, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true})
		if err != nil {
			siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter X-GitHub-Delivery: %w", err), http.StatusBadRequest)
			return
		}

		params.XGitHubDelivery = XGitHubDelivery

	} else {
		siw.ErrorHandler(c, fmt.Errorf("Header parameter X-GitHub-Delivery is required, but not found"), http.StatusBadRequest)
		return
	}

	// ------------- Required header parameter "X-GitHub-Event" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-GitHub-Event")]; found {
		var XGitHubEvent string
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandler(c, fmt.Errorf("Expected one value for X-GitHub-Event, got %d", n), http.StatusBadRequest)
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "X-GitHub-Event", valueList[0], &XGitHubEvent, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true})
		if err != nil {
			siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter X-GitHub-Event: %w", err), http.StatusBadRequest)
			return
		}

		params.XGitHubEvent = XGitHubEvent

	} else {
		siw.ErrorHandler(c, fmt.Errorf("Header parameter X-GitHub-Event is required, but not found"), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ReceiveGitHubWebhook(c, params)
}

// GetWorkItems operation middleware
func (siw *ServerInterfaceWrapper) GetWorkItems(c *gin.Context) {

	c.Set(SessionCookieScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetWorkItems(c)
}

// GetWorkers operation middleware
func (siw *ServerInterfaceWrapper) GetWorkers(c *gin.Context) {

	c.Set(SessionCookieScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetWorkers(c)
}

// GetWorktrees operation middleware
func (siw *ServerInterfaceWrapper) GetWorktrees(c *gin.Context) {

	c.Set(SessionCookieScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetWorktrees(c)
}

// GinServerOptions provides options for the Gin server.
type GinServerOptions struct {
	BaseURL      string
	Middlewares  []MiddlewareFunc
	ErrorHandler func(*gin.Context, error, int)
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router gin.IRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, GinServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router gin.IRouter, si ServerInterface, options GinServerOptions) {
	errorHandler := options.ErrorHandler
	if errorHandler == nil {
		errorHandler = func(c *gin.Context, err error, statusCode int) {
			c.JSON(statusCode, gin.H{"msg": err.Error()})
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandler:       errorHandler,
	}

	router.GET(options.BaseURL+"/agent-profiles", wrapper.GetAgentProfiles)
	router.POST(options.BaseURL+"/agent-profiles", wrapper.PostAgentProfiles)
	router.GET(options.BaseURL+"/audit-logs", wrapper.GetAuditLogs)
	router.POST(options.BaseURL+"/auth/login", wrapper.Login)
	router.POST(options.BaseURL+"/auth/logout", wrapper.Logout)
	router.GET(options.BaseURL+"/auth/me", wrapper.GetCurrentAdministrator)
	router.GET(options.BaseURL+"/discord/development-environments", wrapper.ListDiscordDevelopmentEnvironments)
	router.POST(options.BaseURL+"/discord/development-environments/:id/rebuild", wrapper.RebuildDiscordDevelopmentEnvironment)
	router.POST(options.BaseURL+"/discord/development-forums/:id/delete", wrapper.DeleteDiscordDevelopmentForum)
	router.GET(options.BaseURL+"/discord/development-forums/:id/delete-preflight", wrapper.PreflightDiscordDevelopmentForumDeletion)
	router.DELETE(options.BaseURL+"/discord/forums/:forumId/access/:memberId", wrapper.DeleteDiscordForumAccess)
	router.PUT(options.BaseURL+"/discord/forums/:forumId/access/:memberId", wrapper.PutDiscordForumAccess)
	router.POST(options.BaseURL+"/discord/github/bind", wrapper.StartDiscordGitHubBind)
	router.GET(options.BaseURL+"/discord/github/bind/callback", wrapper.CompleteDiscordGitHubBind)
	router.POST(options.BaseURL+"/discord/github/unbind", wrapper.UnbindDiscordGitHub)
	router.POST(options.BaseURL+"/discord/initializations", wrapper.CreateDiscordInitialization)
	router.POST(options.BaseURL+"/discord/initializations/preflight", wrapper.PreflightDiscordInitialization)
	router.GET(options.BaseURL+"/discord/initializations/:id", wrapper.GetDiscordInitialization)
	router.GET(options.BaseURL+"/discord/members", wrapper.ListDiscordMembers)
	router.POST(options.BaseURL+"/discord/members/:id/forum", wrapper.CreateDiscordMemberForum)
	router.GET(options.BaseURL+"/discord/status", wrapper.GetDiscordStatus)
	router.GET(options.BaseURL+"/events/stream", wrapper.StreamEvents)
	router.GET(options.BaseURL+"/github/app", wrapper.GetGitHubApp)
	router.PUT(options.BaseURL+"/github/app", wrapper.PutGitHubApp)
	router.GET(options.BaseURL+"/github/app/manifest", wrapper.GetGitHubAppManifest)
	router.GET(options.BaseURL+"/github/app/manifest/callback", wrapper.GithubAppManifestCallback)
	router.GET(options.BaseURL+"/installations", wrapper.GetInstallations)
	router.POST(options.BaseURL+"/internal/v1/tools/call", wrapper.CallInternalTool)
	router.GET(options.BaseURL+"/jobs", wrapper.GetJobs)
	router.GET(options.BaseURL+"/repo-caches", wrapper.GetRepoCaches)
	router.GET(options.BaseURL+"/repositories", wrapper.GetRepositories)
	router.POST(options.BaseURL+"/repositories", wrapper.CreateRepository)
	router.GET(options.BaseURL+"/settings/agent-provider", wrapper.GetAgentProviderSettings)
	router.PUT(options.BaseURL+"/settings/agent-provider", wrapper.PutAgentProviderSettings)
	router.GET(options.BaseURL+"/settings/discord", wrapper.GetDiscordSettings)
	router.PUT(options.BaseURL+"/settings/discord", wrapper.PutDiscordSettings)
	router.POST(options.BaseURL+"/setup/admin", wrapper.SetupAdministrator)
	router.GET(options.BaseURL+"/setup/status", wrapper.GetSetupStatus)
	router.GET(options.BaseURL+"/system/status", wrapper.GetSystemStatus)
	router.GET(options.BaseURL+"/threads", wrapper.GetThreads)
	router.GET(options.BaseURL+"/trigger-rules", wrapper.GetTriggerRules)
	router.POST(options.BaseURL+"/trigger-rules", wrapper.CreateTriggerRule)
	router.POST(options.BaseURL+"/webhooks/github", wrapper.ReceiveGitHubWebhook)
	router.GET(options.BaseURL+"/work-items", wrapper.GetWorkItems)
	router.GET(options.BaseURL+"/workers", wrapper.GetWorkers)
	router.GET(options.BaseURL+"/worktrees", wrapper.GetWorktrees)
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+RdX3MctZb/KlO9eVpmGNsk2Y3fjBOCF2eTipNlq1LelKZbMyPcLTVqtZ1Zl6scll3C",
	"EodkISlCCBBgl90qNlDcCwRMyIfBM7af7le41ZL6v9TTbc84vtdv8Uito/M7R0fnHB0pq4ZJHJdgiJln",
	"TK8aLqDAgQxS/tfswsVXLpEliIM/EDamjS4EFqRG3cDAgca08c+NoE9DdKobFL7pIwotY5pRH9YNz+xC",
	"BwRfs54b9PcYRbhjrK2t1Q0XsO4cg44gRSFg8CzEkCIzO5Mrq8YxCtvGtPE3zXi+zbhLM57p2qKYBvTY",
	"y8TqBUOZBDOIWfBP4Lo2MgFDBDff8AhnLJ4ksCwUNAH7AiUupAxBL2RFMkBab0CTCQbS3PIfPJdgD3KO",
	"piYmKxFXcShavebc6YvQIz41oaBsQc+kyA1GMqaN/k/f92886G/+YvCmNvBtphsxmmLzAiUtGzpGMB4D",
	"nQBmI6TiGYtrdWMeeWymAzG7QEkb2YKtABfOwpxlTBt2rku9quR86hFqrNWH9pxHDmJSvimcJ4YzGzIW",
	"sDQOlHwLsXnS0SEUNR9JdOawx4Btc0w0CKW7HEmU/oG0NODwliOJyUXokllgdnWmJ9F+ZPHxECMUFSEU",
	"9TiSGF3qUggsDTxh49FEhqJOB9KLvnZrT/U4khi9TuhS5KTmAYqbjyw6MlZQYxM0HllkGIWwABvRfMTQ",
	"yUZJYX99pOSKHi9Ui5jkuKchA8j2VFHTxVdma6eOn/i7muxai/uGgSuf4YzlIIw8RgEjlEemidhw1TA9",
	"2o5i5EyUWzfgNRdR6M1wrtqEOoAZ04YFGGww5ECjnv8EWam+vo8sVTffg1QE4fngOhmaXjH491H3emLG",
	"yfkt5kLcuhFGdsvIgnQBMoawCHHSELSABy9TOz1tilSzNgluo84C6mDAfMonH2zA57HdywTa2W98zk3E",
	"a4sQGwIctDvEgrYSfVdO/RJvWDUg9p0AEQsuIxM2TGIFeAAXNZZgL4FAaoRrvZK8UQg8ghHunGm3CWXK",
	"GXmQBqQvIUiHCy41/RQOpYU1h11frCjbPt/W2pdw1agFHtiatMSBi16DvTwHdWOFIgZjcXIzkJ5pYCFP",
	"I88k1JoluG0jk+VVSqPZIcjDsZO6Lrur8JJzOA2XoU1cB2J2GtqQwQsUtm3U6SpmBUyGlqFaC7l0AgVB",
	"RG0KLD66dwYvI0qwIy1dfiALUdZTN7UJ9Z25kvYBu77XVa+ZDFbhsCHtxMf1kGfl/DNcl0M5A0DGlPjI",
	"tqKYpacEMtOnJB78qwW+Dy10gdpYU0qosoUjxCeIQl+waBnlmX4lGMCIFwOgFPQqWHvkgA6cs5STs4HH",
	"LnvQqrLJkBUMqZzmZQ9SzdC82z9q16KPg/GD79XGjgHmeyU3KMWMkvRVYs/9ZkQ0U6hE8iunoEJWedWk",
	"AJtd9dLWL1lLDK/BV69xJfWiwE4WriFadflUkqU0vjHvGYKp6SVkJiEOAS0Q1xxGDAEb/WtkbzNeGT9O",
	"qLQk9LLoBFqmkWBJOQU+isZFSew2JWxKvDsVCaVu+K5VDQCVHEPG5fwTkoqnXU9gnSRbWniRi5KR4LD9",
	"NIQ0dOoQNikM1i+wgxVPoddVuHQZNvkgBVM9B50WVHj9LeJjq3DFF1hVC3muDXpau9pBrOu35kkH4cr6",
	"WD4siIVrZaxuIlZITrUuuS6Aq8B3MrsAY2jPEj/l+CDMYAfS0IMKvMHK+2zkRir2V6Gc6SFzoGU/kq5O",
	"tY+KpOIgz0O4cwFS/i95DFJ+7L3pet3wQFvjroqFWmkaWv2RxiGEOh48RjIpXSUc9bSCyKkXqJo+HE0k",
	"DzTiaBFWsDxN4jg+Rqx3BoOWrYs6YVFjkS6wIPSeLYxptUiHRBWTzA9cAjyN7c0h6ALGIMXGtPEvVyYa",
	"pxb/9pjSxSZMkwnJx4UZIZQjUBbz7GgvHBu63+UxLoIv2ncVe1ZBpqJw/m2AbGid91mLXEtt2gizk8dj",
	"BhIWswMYXAG9M3rPRXRY0PsJgZt8VvSq4iy5EFsId9I7+fkwzemVnL8cpQLPGaklAE8ujjTbWToZqIcz",
	"o9KEs4i96rdmXFe/hDKedciSgzByAjM+qYIEuO6C7XfUhslGEDOd1eKNC9CkkJVbgC5Fy4DBkomcurEC",
	"W11ClsqTyAhLQBKzmJpBdvhCzHXrTw/6KIGuYrqH5OwSdT05ZkpFFnmvXUWGu5IXRVFUnpALPG+FUN1u",
	"xVyVSV09uXZsf2nphJcZzUDSK+DBk6cQY07C74mN8on1zOlEjh+LN6gDTuwxgIXCJDPSDQrbkMKgRZmb",
	"5sLXqHQcRzrgmjBOJ06dSpiq4xMTqjXEELNhgedYfoYZUJnIeIvxo/mpkEwkhDSG2DQDj1IfTckO4RlB",
	"dNJlnKcdgMMMg+pcwia47LmHHPVlfQ4JJSqgzlwL1hqwSxszbRqIJ9CGZIAqUsuaHPW862ngNfTCCcYp",
	"oxROCYxVsl+AzHdLmTUHXJuHuMO6xvTUiZNcscO/J6dUcVMwcmRQkr1PDjEWCUonj6cIvTRM6RNE60rr",
	"WICB2izyA6QgvkK4c5micodYJlmGtDdLrKoBcGC6dc5BboHHfeu5aWZnoeVb5weIBMrsEG/cC9UHldvL",
	"0/3reSqqeSYqaLQGSpviAiYj9BzCcaCctlCMItCB3PUVeQEKAd9Ew9+5Rxb4nABhBvg6BJaDsDJZABJ1",
	"vCWzwsC2yQq0LhFiV02xANyBlPjejMmq50MKAym4DDELk2vJtatgoI3ssNi9QvG3sNbUjyQ3hIrCOExO",
	"/X192GcuRYQicbIQCX1SvRVXT+gvIbuq0JhQ5teQyH2GWscB50cuLWgH27UNvO5VkzgOwDw/BHEAVOIX",
	"G3aA2bsqG5TaKGn9E7B9uS8nizfmA1K1/u2NwY17W082+k/+Z3Dvk8HDz7c/frt/5+nW5lf92xt/+vUB",
	"n9nv69czM6htPblVS8+htn33/vb//fL7+ltDnZPMUUZm2URbWayGaeDSypO3GdwymX4g+AWzCx1hJTzI",
	"1/8sIUsIRtcxTPFndB2D9ah3tQuwdVX2j5mRR/a8EAbhNgnGsJEJsSeGswIc2rwuwTg3dykeM/gj9vU4",
	"iUZAonYOYNDhWcjazIU5o24sQypslDHx4uSLE9z/cCEGLjKmjZf4T+LWB+eoyYFruIm7BR2oPQaJLos0",
	"5xVXDtIFVmdhrkOi5gj7th0sLuKVIJa+lpIldIF4Qymt1Y0m8C3EGra8H1Cey8S1gTyHiUY1TdZt2qHX",
	"G3KbHib2zfZ2X6YoN5+KOUtdl5kYNW3uFCkqv7bvb/af3t369eOdbx/uubgtXKPG9JXFuNRtxmddUeUW",
	"CYDITV8ngaC9vs/rTikcj+fNZf+n73fX1/vv7P+GUJZBsbFJlc4p6axPKcQsXUI3RsGnCamuSj39oP/u",
	"xvbjR9u3/6N/56NRwiFP0ZpWXEnQgHGti6fFKVjqhWUy3n4h22PRSrJSJ38alMN29+6zwSef9X9d779/",
	"Z/vWt/0v/m3f8Mo5lUS4uYqstSaFvCpEv+Yuig7F/OZWJN9vA/sc74zIKrzyODR1t79lPqVc5oPP39l5",
	"/N3Wk1+2nrw3+ObRzrPbO49u9t/d2H1nYxQXBIcLRJTaCFGI0z+9JETBna4C51CKYG8bZaXSBlUKWV9i",
	"V2ZnnTqoi6g3Pt+9/1Wghbf+a/ejz56LtjVSFTVKgxtVKWg0j6ulcJ7HroGLY9wNh1e4amW4+8Xbgy/X",
	"xyTAUGiy7nStCUwTel5z1eHVNnPWmjBtofEoMBpcXjP884NwogQ4I4SljIbF5bn7MnSKkUO8K93cX6wb",
	"Mo+VWVU+G4NQRmFvhXrNB8sgmbagEFgE270ouiJ0eMFYcqy9GWO1Zg0e/HFw77sxLTiRqWy2ZN5GvRkv",
	"MEBDCYqT1pdFuuL5C3B4SZ2+4KZk1dveZDmxD6b8MidH2cNGqtO6tEJtPVkffPNosP719uad/uOPdz/4",
	"bXDrv8evXE0T2HYLmEvarXeWOG7CfBfpGbdXb/qQlwhLg+UxwGAla1VXDySv/lSyeirZZxILHO3+45uD",
	"G7dHnFgoxN7HxUv7Mm9PYX4o1rV0beGeK2n3vezriTmM0pzvfP3l9uadMa04lCpU8vRyF9lLdcn885F/",
	"CXdVVR1+yKKch/2v3+vfvDfuQCcj52YqslFLPBva/NULfeTRUmFwtPvgx61njwcf/izio+3NDwaffnJA",
	"0g9i3KJca0mJ/0WGsBmmihbl9n/+OFi/PiaZiICpVCr3nOx6gKlbeVmlRKpWflAb3Lg9iix4IVgiOdOO",
	"LtUN36kEHyNLAh6OpF+Jm3pze6j4TH19uLODXKA18VLduLfOuKJxiLmMasTHbcIkoYLFKHL1Y7FfvBbB",
	"a3qMQuBoUVngzWeWyx05MXiNiYEb8biFDz6m2V6AdBnSxgLErCZpFjwaEoY6wHWLpBqViI9Totk6dAVz",
	"okttxnVroUATvMkQjKf/NKm0JCOHzWfL3H3YR5i09exh///3v/9EeKYVpekAjNqyOHSoxpwLO480y5Oc",
	"Qr5wdI8poHo8bJlsUMhZbefR//Y37vbff2tw97tKAA5P7JzlHyVgnA2/KJXY2Xc+5iXVeejOsw/7Dz6t",
	"ycW48/i37aePdx/9MFp9Q9nXLUvX92QfvczpZraDqs4HYVFN3VyebDJCbI/LqsDTArY9J7+5RIhtHJrn",
	"cifGSTytGAHjtQCJ2j5DuHSyzuNbmtByvraNJjfCuj3tDfnkZ2mNkS+B5hRF/q7Sj8BBbJjRG5qlSaWe",
	"1swRTLXqyCZfpqxEN/FgpZJyol1f2KcKMFJPhRy2bTV7leUIvDEdaIon7yLH9aD89amiPVv9TNU468rU",
	"72LlYeIda2FPueWk2I++LvL+dAweNpUteHPs+XuFCaRTeiZjxDLB4QGoVpZUUYAotWmU1QfFJ/mHWPWU",
	"Lxk8f6VLx938ylBTXLnRH7wHnfIlsqOHLHVf7oB3l+Q9NVVJdliRu/Xk1uD6F/2vNnZ+eHtw7/74yrOF",
	"aIbniZIXzcZoBpJklMkS5qdSCcP563kMOmUY5B1Hw6HaKS91hXWoz779h83tzc9GlB7LOiEsfiS8tKca",
	"vx2ewzRuUvnG8jZQg/pV771k3uPO0023V3OOEx8fQnufu0h5RNxj+SyGJ9MyRWXtJkTLUOQmXhdfaZIv",
	"+f/F51W/1Yhe5W1MnTi5pyKb/LhiNo3T0EbLIuEzwlHPyHuHFbNGhyLZMXVwyY7+T98Pbl7f+vnf+zfv",
	"HVCiI5UgWyF0qRGdY5a2dcmn9XOGLtmoMrEr8cP0lQiKE1sludxhbopY9NZ7JXLhE/BKgmFjjmRaHLm7",
	"oVcW19QiAi5qLk8mBRUeSwrHIVhx8m8pwMQvsV1K/Jh6Ilr+FnrAa4trfw4AAP//h1Z6KF5sAAA=",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
