// Code generated by ent, DO NOT EDIT.

package platformsetting

import (
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the platformsetting type in the database.
	Label = "platform_setting"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldSettingKey holds the string denoting the setting_key field in the database.
	FieldSettingKey = "setting_key"
	// FieldValue holds the string denoting the value field in the database.
	FieldValue = "value"
	// FieldVersion holds the string denoting the version field in the database.
	FieldVersion = "version"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// Table holds the table name of the platformsetting in the database.
	Table = "platform_settings"
)

// Columns holds all SQL columns for platformsetting fields.
var Columns = []string{
	FieldID,
	FieldSettingKey,
	FieldValue,
	FieldVersion,
	FieldUpdatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultVersion holds the default value on creation for the "version" field.
	DefaultVersion int64
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
)

// OrderOption defines the ordering options for the PlatformSetting queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// BySettingKey orders the results by the setting_key field.
func BySettingKey(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSettingKey, opts...).ToFunc()
}

// ByVersion orders the results by the version field.
func ByVersion(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldVersion, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}
