// Code generated by ent, DO NOT EDIT.

package sshcredential

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
	"github.com/slovx2/tyrs-hand/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.SSHCredential {
	return predicate.SSHCredential(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.SSHCredential {
	return predicate.SSHCredential(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.SSHCredential {
	return predicate.SSHCredential(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.SSHCredential {
	return predicate.SSHCredential(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.SSHCredential {
	return predicate.SSHCredential(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.SSHCredential {
	return predicate.SSHCredential(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.SSHCredential {
	return predicate.SSHCredential(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.SSHCredential {
	return predicate.SSHCredential(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.SSHCredential {
	return predicate.SSHCredential(sql.FieldLTE(FieldID, id))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.SSHCredential {
	return predicate.SSHCredential(sql.FieldEQ(FieldName, v))
}

// SecretID applies equality check predicate on the "secret_id" field. It's identical to SecretIDEQ.
func SecretID(v uuid.UUID) predicate.SSHCredential {
	return predicate.SSHCredential(sql.FieldEQ(FieldSecretID, v))
}

// PublicKey applies equality check predicate on the "public_key" field. It's identical to PublicKeyEQ.
func PublicKey(v string) predicate.SSHCredential {
	return predicate.SSHCredential(sql.FieldEQ(FieldPublicKey, v))
}

// Fingerprint applies equality check predicate on the "fingerprint" field. It's identical to FingerprintEQ.
func Fingerprint(v string) predicate.SSHCredential {
	return predicate.SSHCredential(sql.FieldEQ(FieldFingerprint, v))
}

// Enabled applies equality check predicate on the "enabled" field. It's identical to EnabledEQ.
func Enabled(v bool) predicate.SSHCredential {
	return predicate.SSHCredential(sql.FieldEQ(FieldEnabled, v))
}

// Version applies equality check predicate on the "version" field. It's identical to VersionEQ.
func Version(v int64) predicate.SSHCredential {
	return predicate.SSHCredential(sql.FieldEQ(FieldVersion, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.SSHCredential {
	return predicate.SSHCredential(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.SSHCredential {
	return predicate.SSHCredential(sql.FieldEQ(FieldUpdatedAt, v))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.SSHCredential {
	return predicate.SSHCredential(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.SSHCredential {
	return predicate.SSHCredential(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.SSHCredential {
	return predicate.SSHCredential(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.SSHCredential {
	return predicate.SSHCredential(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.SSHCredential {
	return predicate.SSHCredential(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.SSHCredential {
	return predicate.SSHCredential(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.SSHCredential {
	return predicate.SSHCredential(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.SSHCredential {
	return predicate.SSHCredential(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.SSHCredential {
	return predicate.SSHCredential(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.SSHCredential {
	return predicate.SSHCredential(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.SSHCredential {
	return predicate.SSHCredential(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.SSHCredential {
	return predicate.SSHCredential(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.SSHCredential {
	return predicate.SSHCredential(sql.FieldContainsFold(FieldName, v))
}

// SecretIDEQ applies the EQ predicate on the "secret_id" field.
func SecretIDEQ(v uuid.UUID) predicate.SSHCredential {
	return predicate.SSHCredential(sql.FieldEQ(FieldSecretID, v))
}

// SecretIDNEQ applies the NEQ predicate on the "secret_id" field.
func SecretIDNEQ(v uuid.UUID) predicate.SSHCredential {
	return predicate.SSHCredential(sql.FieldNEQ(FieldSecretID, v))
}

// SecretIDIn applies the In predicate on the "secret_id" field.
func SecretIDIn(vs ...uuid.UUID) predicate.SSHCredential {
	return predicate.SSHCredential(sql.FieldIn(FieldSecretID, vs...))
}

// SecretIDNotIn applies the NotIn predicate on the "secret_id" field.
func SecretIDNotIn(vs ...uuid.UUID) predicate.SSHCredential {
	return predicate.SSHCredential(sql.FieldNotIn(FieldSecretID, vs...))
}

// SecretIDGT applies the GT predicate on the "secret_id" field.
func SecretIDGT(v uuid.UUID) predicate.SSHCredential {
	return predicate.SSHCredential(sql.FieldGT(FieldSecretID, v))
}

// SecretIDGTE applies the GTE predicate on the "secret_id" field.
func SecretIDGTE(v uuid.UUID) predicate.SSHCredential {
	return predicate.SSHCredential(sql.FieldGTE(FieldSecretID, v))
}

// SecretIDLT applies the LT predicate on the "secret_id" field.
func SecretIDLT(v uuid.UUID) predicate.SSHCredential {
	return predicate.SSHCredential(sql.FieldLT(FieldSecretID, v))
}

// SecretIDLTE applies the LTE predicate on the "secret_id" field.
func SecretIDLTE(v uuid.UUID) predicate.SSHCredential {
	return predicate.SSHCredential(sql.FieldLTE(FieldSecretID, v))
}

// PublicKeyEQ applies the EQ predicate on the "public_key" field.
func PublicKeyEQ(v string) predicate.SSHCredential {
	return predicate.SSHCredential(sql.FieldEQ(FieldPublicKey, v))
}

// PublicKeyNEQ applies the NEQ predicate on the "public_key" field.
func PublicKeyNEQ(v string) predicate.SSHCredential {
	return predicate.SSHCredential(sql.FieldNEQ(FieldPublicKey, v))
}

// PublicKeyIn applies the In predicate on the "public_key" field.
func PublicKeyIn(vs ...string) predicate.SSHCredential {
	return predicate.SSHCredential(sql.FieldIn(FieldPublicKey, vs...))
}

// PublicKeyNotIn applies the NotIn predicate on the "public_key" field.
func PublicKeyNotIn(vs ...string) predicate.SSHCredential {
	return predicate.SSHCredential(sql.FieldNotIn(FieldPublicKey, vs...))
}

// PublicKeyGT applies the GT predicate on the "public_key" field.
func PublicKeyGT(v string) predicate.SSHCredential {
	return predicate.SSHCredential(sql.FieldGT(FieldPublicKey, v))
}

// PublicKeyGTE applies the GTE predicate on the "public_key" field.
func PublicKeyGTE(v string) predicate.SSHCredential {
	return predicate.SSHCredential(sql.FieldGTE(FieldPublicKey, v))
}

// PublicKeyLT applies the LT predicate on the "public_key" field.
func PublicKeyLT(v string) predicate.SSHCredential {
	return predicate.SSHCredential(sql.FieldLT(FieldPublicKey, v))
}

// PublicKeyLTE applies the LTE predicate on the "public_key" field.
func PublicKeyLTE(v string) predicate.SSHCredential {
	return predicate.SSHCredential(sql.FieldLTE(FieldPublicKey, v))
}

// PublicKeyContains applies the Contains predicate on the "public_key" field.
func PublicKeyContains(v string) predicate.SSHCredential {
	return predicate.SSHCredential(sql.FieldContains(FieldPublicKey, v))
}

// PublicKeyHasPrefix applies the HasPrefix predicate on the "public_key" field.
func PublicKeyHasPrefix(v string) predicate.SSHCredential {
	return predicate.SSHCredential(sql.FieldHasPrefix(FieldPublicKey, v))
}

// PublicKeyHasSuffix applies the HasSuffix predicate on the "public_key" field.
func PublicKeyHasSuffix(v string) predicate.SSHCredential {
	return predicate.SSHCredential(sql.FieldHasSuffix(FieldPublicKey, v))
}

// PublicKeyEqualFold applies the EqualFold predicate on the "public_key" field.
func PublicKeyEqualFold(v string) predicate.SSHCredential {
	return predicate.SSHCredential(sql.FieldEqualFold(FieldPublicKey, v))
}

// PublicKeyContainsFold applies the ContainsFold predicate on the "public_key" field.
func PublicKeyContainsFold(v string) predicate.SSHCredential {
	return predicate.SSHCredential(sql.FieldContainsFold(FieldPublicKey, v))
}

// FingerprintEQ applies the EQ predicate on the "fingerprint" field.
func FingerprintEQ(v string) predicate.SSHCredential {
	return predicate.SSHCredential(sql.FieldEQ(FieldFingerprint, v))
}

// FingerprintNEQ applies the NEQ predicate on the "fingerprint" field.
func FingerprintNEQ(v string) predicate.SSHCredential {
	return predicate.SSHCredential(sql.FieldNEQ(FieldFingerprint, v))
}

// FingerprintIn applies the In predicate on the "fingerprint" field.
func FingerprintIn(vs ...string) predicate.SSHCredential {
	return predicate.SSHCredential(sql.FieldIn(FieldFingerprint, vs...))
}

// FingerprintNotIn applies the NotIn predicate on the "fingerprint" field.
func FingerprintNotIn(vs ...string) predicate.SSHCredential {
	return predicate.SSHCredential(sql.FieldNotIn(FieldFingerprint, vs...))
}

// FingerprintGT applies the GT predicate on the "fingerprint" field.
func FingerprintGT(v string) predicate.SSHCredential {
	return predicate.SSHCredential(sql.FieldGT(FieldFingerprint, v))
}

// FingerprintGTE applies the GTE predicate on the "fingerprint" field.
func FingerprintGTE(v string) predicate.SSHCredential {
	return predicate.SSHCredential(sql.FieldGTE(FieldFingerprint, v))
}

// FingerprintLT applies the LT predicate on the "fingerprint" field.
func FingerprintLT(v string) predicate.SSHCredential {
	return predicate.SSHCredential(sql.FieldLT(FieldFingerprint, v))
}

// FingerprintLTE applies the LTE predicate on the "fingerprint" field.
func FingerprintLTE(v string) predicate.SSHCredential {
	return predicate.SSHCredential(sql.FieldLTE(FieldFingerprint, v))
}

// FingerprintContains applies the Contains predicate on the "fingerprint" field.
func FingerprintContains(v string) predicate.SSHCredential {
	return predicate.SSHCredential(sql.FieldContains(FieldFingerprint, v))
}

// FingerprintHasPrefix applies the HasPrefix predicate on the "fingerprint" field.
func FingerprintHasPrefix(v string) predicate.SSHCredential {
	return predicate.SSHCredential(sql.FieldHasPrefix(FieldFingerprint, v))
}

// FingerprintHasSuffix applies the HasSuffix predicate on the "fingerprint" field.
func FingerprintHasSuffix(v string) predicate.SSHCredential {
	return predicate.SSHCredential(sql.FieldHasSuffix(FieldFingerprint, v))
}

// FingerprintEqualFold applies the EqualFold predicate on the "fingerprint" field.
func FingerprintEqualFold(v string) predicate.SSHCredential {
	return predicate.SSHCredential(sql.FieldEqualFold(FieldFingerprint, v))
}

// FingerprintContainsFold applies the ContainsFold predicate on the "fingerprint" field.
func FingerprintContainsFold(v string) predicate.SSHCredential {
	return predicate.SSHCredential(sql.FieldContainsFold(FieldFingerprint, v))
}

// EnabledEQ applies the EQ predicate on the "enabled" field.
func EnabledEQ(v bool) predicate.SSHCredential {
	return predicate.SSHCredential(sql.FieldEQ(FieldEnabled, v))
}

// EnabledNEQ applies the NEQ predicate on the "enabled" field.
func EnabledNEQ(v bool) predicate.SSHCredential {
	return predicate.SSHCredential(sql.FieldNEQ(FieldEnabled, v))
}

// VersionEQ applies the EQ predicate on the "version" field.
func VersionEQ(v int64) predicate.SSHCredential {
	return predicate.SSHCredential(sql.FieldEQ(FieldVersion, v))
}

// VersionNEQ applies the NEQ predicate on the "version" field.
func VersionNEQ(v int64) predicate.SSHCredential {
	return predicate.SSHCredential(sql.FieldNEQ(FieldVersion, v))
}

// VersionIn applies the In predicate on the "version" field.
func VersionIn(vs ...int64) predicate.SSHCredential {
	return predicate.SSHCredential(sql.FieldIn(FieldVersion, vs...))
}

// VersionNotIn applies the NotIn predicate on the "version" field.
func VersionNotIn(vs ...int64) predicate.SSHCredential {
	return predicate.SSHCredential(sql.FieldNotIn(FieldVersion, vs...))
}

// VersionGT applies the GT predicate on the "version" field.
func VersionGT(v int64) predicate.SSHCredential {
	return predicate.SSHCredential(sql.FieldGT(FieldVersion, v))
}

// VersionGTE applies the GTE predicate on the "version" field.
func VersionGTE(v int64) predicate.SSHCredential {
	return predicate.SSHCredential(sql.FieldGTE(FieldVersion, v))
}

// VersionLT applies the LT predicate on the "version" field.
func VersionLT(v int64) predicate.SSHCredential {
	return predicate.SSHCredential(sql.FieldLT(FieldVersion, v))
}

// VersionLTE applies the LTE predicate on the "version" field.
func VersionLTE(v int64) predicate.SSHCredential {
	return predicate.SSHCredential(sql.FieldLTE(FieldVersion, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.SSHCredential {
	return predicate.SSHCredential(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.SSHCredential {
	return predicate.SSHCredential(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.SSHCredential {
	return predicate.SSHCredential(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.SSHCredential {
	return predicate.SSHCredential(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.SSHCredential {
	return predicate.SSHCredential(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.SSHCredential {
	return predicate.SSHCredential(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.SSHCredential {
	return predicate.SSHCredential(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.SSHCredential {
	return predicate.SSHCredential(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.SSHCredential {
	return predicate.SSHCredential(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.SSHCredential {
	return predicate.SSHCredential(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.SSHCredential {
	return predicate.SSHCredential(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.SSHCredential {
	return predicate.SSHCredential(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.SSHCredential {
	return predicate.SSHCredential(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.SSHCredential {
	return predicate.SSHCredential(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.SSHCredential {
	return predicate.SSHCredential(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.SSHCredential {
	return predicate.SSHCredential(sql.FieldLTE(FieldUpdatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.SSHCredential) predicate.SSHCredential {
	return predicate.SSHCredential(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.SSHCredential) predicate.SSHCredential {
	return predicate.SSHCredential(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.SSHCredential) predicate.SSHCredential {
	return predicate.SSHCredential(sql.NotPredicates(p))
}
