// Code generated by ent, DO NOT EDIT.

package toolcall

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the toolcall type in the database.
	Label = "tool_call"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldRunID holds the string denoting the run_id field in the database.
	FieldRunID = "run_id"
	// FieldIntentID holds the string denoting the intent_id field in the database.
	FieldIntentID = "intent_id"
	// FieldThreadID holds the string denoting the thread_id field in the database.
	FieldThreadID = "thread_id"
	// FieldTurnID holds the string denoting the turn_id field in the database.
	FieldTurnID = "turn_id"
	// FieldCallID holds the string denoting the call_id field in the database.
	FieldCallID = "call_id"
	// FieldNamespace holds the string denoting the namespace field in the database.
	FieldNamespace = "namespace"
	// FieldTool holds the string denoting the tool field in the database.
	FieldTool = "tool"
	// FieldArguments holds the string denoting the arguments field in the database.
	FieldArguments = "arguments"
	// FieldResult holds the string denoting the result field in the database.
	FieldResult = "result"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldError holds the string denoting the error field in the database.
	FieldError = "error"
	// FieldStartedAt holds the string denoting the started_at field in the database.
	FieldStartedAt = "started_at"
	// FieldFinishedAt holds the string denoting the finished_at field in the database.
	FieldFinishedAt = "finished_at"
	// Table holds the table name of the toolcall in the database.
	Table = "tool_calls"
)

// Columns holds all SQL columns for toolcall fields.
var Columns = []string{
	FieldID,
	FieldRunID,
	FieldIntentID,
	FieldThreadID,
	FieldTurnID,
	FieldCallID,
	FieldNamespace,
	FieldTool,
	FieldArguments,
	FieldResult,
	FieldStatus,
	FieldError,
	FieldStartedAt,
	FieldFinishedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultStatus holds the default value on creation for the "status" field.
	DefaultStatus string
	// DefaultStartedAt holds the default value on creation for the "started_at" field.
	DefaultStartedAt func() time.Time
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)

// OrderOption defines the ordering options for the ToolCall queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByRunID orders the results by the run_id field.
func ByRunID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRunID, opts...).ToFunc()
}

// ByIntentID orders the results by the intent_id field.
func ByIntentID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldIntentID, opts...).ToFunc()
}

// ByThreadID orders the results by the thread_id field.
func ByThreadID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldThreadID, opts...).ToFunc()
}

// ByTurnID orders the results by the turn_id field.
func ByTurnID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTurnID, opts...).ToFunc()
}

// ByCallID orders the results by the call_id field.
func ByCallID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCallID, opts...).ToFunc()
}

// ByNamespace orders the results by the namespace field.
func ByNamespace(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldNamespace, opts...).ToFunc()
}

// ByTool orders the results by the tool field.
func ByTool(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTool, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// ByError orders the results by the error field.
func ByError(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldError, opts...).ToFunc()
}

// ByStartedAt orders the results by the started_at field.
func ByStartedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStartedAt, opts...).ToFunc()
}

// ByFinishedAt orders the results by the finished_at field.
func ByFinishedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFinishedAt, opts...).ToFunc()
}
