// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
	"github.com/slovx2/tyrs-hand/ent/administrator"
)

// Administrator is the model entity for the Administrator schema.
type Administrator struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// Username holds the value of the "username" field.
	Username string `json:"username,omitempty"`
	// PasswordHash holds the value of the "password_hash" field.
	PasswordHash string `json:"-"`
	// TotpSecretCiphertext holds the value of the "totp_secret_ciphertext" field.
	TotpSecretCiphertext []byte `json:"-"`
	// RecoveryCodesHash holds the value of the "recovery_codes_hash" field.
	RecoveryCodesHash []string `json:"recovery_codes_hash,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt    time.Time `json:"updated_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Administrator) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case administrator.FieldTotpSecretCiphertext, administrator.FieldRecoveryCodesHash:
			values[i] = new([]byte)
		case administrator.FieldUsername, administrator.FieldPasswordHash:
			values[i] = new(sql.NullString)
		case administrator.FieldCreatedAt, administrator.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		case administrator.FieldID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Administrator fields.
func (_m *Administrator) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case administrator.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case administrator.FieldUsername:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field username", values[i])
			} else if value.Valid {
				_m.Username = value.String
			}
		case administrator.FieldPasswordHash:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field password_hash", values[i])
			} else if value.Valid {
				_m.PasswordHash = value.String
			}
		case administrator.FieldTotpSecretCiphertext:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field totp_secret_ciphertext", values[i])
			} else if value != nil {
				_m.TotpSecretCiphertext = *value
			}
		case administrator.FieldRecoveryCodesHash:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field recovery_codes_hash", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.RecoveryCodesHash); err != nil {
					return fmt.Errorf("unmarshal field recovery_codes_hash: %w", err)
				}
			}
		case administrator.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case administrator.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Administrator.
// This includes values selected through modifiers, order, etc.
func (_m *Administrator) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this Administrator.
// Note that you need to call Administrator.Unwrap() before calling this method if this Administrator
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Administrator) Update() *AdministratorUpdateOne {
	return NewAdministratorClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Administrator entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Administrator) Unwrap() *Administrator {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Administrator is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Administrator) String() string {
	var builder strings.Builder
	builder.WriteString("Administrator(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("username=")
	builder.WriteString(_m.Username)
	builder.WriteString(", ")
	builder.WriteString("password_hash=<sensitive>")
	builder.WriteString(", ")
	builder.WriteString("totp_secret_ciphertext=<sensitive>")
	builder.WriteString(", ")
	builder.WriteString("recovery_codes_hash=")
	builder.WriteString(fmt.Sprintf("%v", _m.RecoveryCodesHash))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// Administrators is a parsable slice of Administrator.
type Administrators []*Administrator
