// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/slovx2/tyrs-hand/ent/codexturnrun"
	"github.com/slovx2/tyrs-hand/ent/predicate"
)

// CodexTurnRunUpdate is the builder for updating CodexTurnRun entities.
type CodexTurnRunUpdate struct {
	config
	hooks    []Hook
	mutation *CodexTurnRunMutation
}

// Where appends a list predicates to the CodexTurnRunUpdate builder.
func (_u *CodexTurnRunUpdate) Where(ps ...predicate.CodexTurnRun) *CodexTurnRunUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetControlID sets the "control_id" field.
func (_u *CodexTurnRunUpdate) SetControlID(v uuid.UUID) *CodexTurnRunUpdate {
	_u.mutation.SetControlID(v)
	return _u
}

// SetNillableControlID sets the "control_id" field if the given value is not nil.
func (_u *CodexTurnRunUpdate) SetNillableControlID(v *uuid.UUID) *CodexTurnRunUpdate {
	if v != nil {
		_u.SetControlID(*v)
	}
	return _u
}

// SetPrimaryIntentID sets the "primary_intent_id" field.
func (_u *CodexTurnRunUpdate) SetPrimaryIntentID(v uuid.UUID) *CodexTurnRunUpdate {
	_u.mutation.SetPrimaryIntentID(v)
	return _u
}

// SetNillablePrimaryIntentID sets the "primary_intent_id" field if the given value is not nil.
func (_u *CodexTurnRunUpdate) SetNillablePrimaryIntentID(v *uuid.UUID) *CodexTurnRunUpdate {
	if v != nil {
		_u.SetPrimaryIntentID(*v)
	}
	return _u
}

// SetAttempt sets the "attempt" field.
func (_u *CodexTurnRunUpdate) SetAttempt(v int) *CodexTurnRunUpdate {
	_u.mutation.ResetAttempt()
	_u.mutation.SetAttempt(v)
	return _u
}

// SetNillableAttempt sets the "attempt" field if the given value is not nil.
func (_u *CodexTurnRunUpdate) SetNillableAttempt(v *int) *CodexTurnRunUpdate {
	if v != nil {
		_u.SetAttempt(*v)
	}
	return _u
}

// AddAttempt adds value to the "attempt" field.
func (_u *CodexTurnRunUpdate) AddAttempt(v int) *CodexTurnRunUpdate {
	_u.mutation.AddAttempt(v)
	return _u
}

// SetWorkerID sets the "worker_id" field.
func (_u *CodexTurnRunUpdate) SetWorkerID(v string) *CodexTurnRunUpdate {
	_u.mutation.SetWorkerID(v)
	return _u
}

// SetNillableWorkerID sets the "worker_id" field if the given value is not nil.
func (_u *CodexTurnRunUpdate) SetNillableWorkerID(v *string) *CodexTurnRunUpdate {
	if v != nil {
		_u.SetWorkerID(*v)
	}
	return _u
}

// SetLeaseEpoch sets the "lease_epoch" field.
func (_u *CodexTurnRunUpdate) SetLeaseEpoch(v int64) *CodexTurnRunUpdate {
	_u.mutation.ResetLeaseEpoch()
	_u.mutation.SetLeaseEpoch(v)
	return _u
}

// SetNillableLeaseEpoch sets the "lease_epoch" field if the given value is not nil.
func (_u *CodexTurnRunUpdate) SetNillableLeaseEpoch(v *int64) *CodexTurnRunUpdate {
	if v != nil {
		_u.SetLeaseEpoch(*v)
	}
	return _u
}

// AddLeaseEpoch adds value to the "lease_epoch" field.
func (_u *CodexTurnRunUpdate) AddLeaseEpoch(v int64) *CodexTurnRunUpdate {
	_u.mutation.AddLeaseEpoch(v)
	return _u
}

// SetCapabilityHash sets the "capability_hash" field.
func (_u *CodexTurnRunUpdate) SetCapabilityHash(v string) *CodexTurnRunUpdate {
	_u.mutation.SetCapabilityHash(v)
	return _u
}

// SetNillableCapabilityHash sets the "capability_hash" field if the given value is not nil.
func (_u *CodexTurnRunUpdate) SetNillableCapabilityHash(v *string) *CodexTurnRunUpdate {
	if v != nil {
		_u.SetCapabilityHash(*v)
	}
	return _u
}

// SetExecutionNodeID sets the "execution_node_id" field.
func (_u *CodexTurnRunUpdate) SetExecutionNodeID(v uuid.UUID) *CodexTurnRunUpdate {
	_u.mutation.SetExecutionNodeID(v)
	return _u
}

// SetNillableExecutionNodeID sets the "execution_node_id" field if the given value is not nil.
func (_u *CodexTurnRunUpdate) SetNillableExecutionNodeID(v *uuid.UUID) *CodexTurnRunUpdate {
	if v != nil {
		_u.SetExecutionNodeID(*v)
	}
	return _u
}

// ClearExecutionNodeID clears the value of the "execution_node_id" field.
func (_u *CodexTurnRunUpdate) ClearExecutionNodeID() *CodexTurnRunUpdate {
	_u.mutation.ClearExecutionNodeID()
	return _u
}

// SetWorkerEventSequence sets the "worker_event_sequence" field.
func (_u *CodexTurnRunUpdate) SetWorkerEventSequence(v int64) *CodexTurnRunUpdate {
	_u.mutation.ResetWorkerEventSequence()
	_u.mutation.SetWorkerEventSequence(v)
	return _u
}

// SetNillableWorkerEventSequence sets the "worker_event_sequence" field if the given value is not nil.
func (_u *CodexTurnRunUpdate) SetNillableWorkerEventSequence(v *int64) *CodexTurnRunUpdate {
	if v != nil {
		_u.SetWorkerEventSequence(*v)
	}
	return _u
}

// AddWorkerEventSequence adds value to the "worker_event_sequence" field.
func (_u *CodexTurnRunUpdate) AddWorkerEventSequence(v int64) *CodexTurnRunUpdate {
	_u.mutation.AddWorkerEventSequence(v)
	return _u
}

// SetWorkerTerminalKey sets the "worker_terminal_key" field.
func (_u *CodexTurnRunUpdate) SetWorkerTerminalKey(v string) *CodexTurnRunUpdate {
	_u.mutation.SetWorkerTerminalKey(v)
	return _u
}

// SetNillableWorkerTerminalKey sets the "worker_terminal_key" field if the given value is not nil.
func (_u *CodexTurnRunUpdate) SetNillableWorkerTerminalKey(v *string) *CodexTurnRunUpdate {
	if v != nil {
		_u.SetWorkerTerminalKey(*v)
	}
	return _u
}

// ClearWorkerTerminalKey clears the value of the "worker_terminal_key" field.
func (_u *CodexTurnRunUpdate) ClearWorkerTerminalKey() *CodexTurnRunUpdate {
	_u.mutation.ClearWorkerTerminalKey()
	return _u
}

// SetActiveSlot sets the "active_slot" field.
func (_u *CodexTurnRunUpdate) SetActiveSlot(v int) *CodexTurnRunUpdate {
	_u.mutation.ResetActiveSlot()
	_u.mutation.SetActiveSlot(v)
	return _u
}

// SetNillableActiveSlot sets the "active_slot" field if the given value is not nil.
func (_u *CodexTurnRunUpdate) SetNillableActiveSlot(v *int) *CodexTurnRunUpdate {
	if v != nil {
		_u.SetActiveSlot(*v)
	}
	return _u
}

// AddActiveSlot adds value to the "active_slot" field.
func (_u *CodexTurnRunUpdate) AddActiveSlot(v int) *CodexTurnRunUpdate {
	_u.mutation.AddActiveSlot(v)
	return _u
}

// ClearActiveSlot clears the value of the "active_slot" field.
func (_u *CodexTurnRunUpdate) ClearActiveSlot() *CodexTurnRunUpdate {
	_u.mutation.ClearActiveSlot()
	return _u
}

// SetStatus sets the "status" field.
func (_u *CodexTurnRunUpdate) SetStatus(v string) *CodexTurnRunUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *CodexTurnRunUpdate) SetNillableStatus(v *string) *CodexTurnRunUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetCodexSubmissionID sets the "codex_submission_id" field.
func (_u *CodexTurnRunUpdate) SetCodexSubmissionID(v string) *CodexTurnRunUpdate {
	_u.mutation.SetCodexSubmissionID(v)
	return _u
}

// SetNillableCodexSubmissionID sets the "codex_submission_id" field if the given value is not nil.
func (_u *CodexTurnRunUpdate) SetNillableCodexSubmissionID(v *string) *CodexTurnRunUpdate {
	if v != nil {
		_u.SetCodexSubmissionID(*v)
	}
	return _u
}

// ClearCodexSubmissionID clears the value of the "codex_submission_id" field.
func (_u *CodexTurnRunUpdate) ClearCodexSubmissionID() *CodexTurnRunUpdate {
	_u.mutation.ClearCodexSubmissionID()
	return _u
}

// SetConfirmedCodexTurnID sets the "confirmed_codex_turn_id" field.
func (_u *CodexTurnRunUpdate) SetConfirmedCodexTurnID(v string) *CodexTurnRunUpdate {
	_u.mutation.SetConfirmedCodexTurnID(v)
	return _u
}

// SetNillableConfirmedCodexTurnID sets the "confirmed_codex_turn_id" field if the given value is not nil.
func (_u *CodexTurnRunUpdate) SetNillableConfirmedCodexTurnID(v *string) *CodexTurnRunUpdate {
	if v != nil {
		_u.SetConfirmedCodexTurnID(*v)
	}
	return _u
}

// ClearConfirmedCodexTurnID clears the value of the "confirmed_codex_turn_id" field.
func (_u *CodexTurnRunUpdate) ClearConfirmedCodexTurnID() *CodexTurnRunUpdate {
	_u.mutation.ClearConfirmedCodexTurnID()
	return _u
}

// SetAppendCount sets the "append_count" field.
func (_u *CodexTurnRunUpdate) SetAppendCount(v int) *CodexTurnRunUpdate {
	_u.mutation.ResetAppendCount()
	_u.mutation.SetAppendCount(v)
	return _u
}

// SetNillableAppendCount sets the "append_count" field if the given value is not nil.
func (_u *CodexTurnRunUpdate) SetNillableAppendCount(v *int) *CodexTurnRunUpdate {
	if v != nil {
		_u.SetAppendCount(*v)
	}
	return _u
}

// AddAppendCount adds value to the "append_count" field.
func (_u *CodexTurnRunUpdate) AddAppendCount(v int) *CodexTurnRunUpdate {
	_u.mutation.AddAppendCount(v)
	return _u
}

// SetMaxAppendCount sets the "max_append_count" field.
func (_u *CodexTurnRunUpdate) SetMaxAppendCount(v int) *CodexTurnRunUpdate {
	_u.mutation.ResetMaxAppendCount()
	_u.mutation.SetMaxAppendCount(v)
	return _u
}

// SetNillableMaxAppendCount sets the "max_append_count" field if the given value is not nil.
func (_u *CodexTurnRunUpdate) SetNillableMaxAppendCount(v *int) *CodexTurnRunUpdate {
	if v != nil {
		_u.SetMaxAppendCount(*v)
	}
	return _u
}

// AddMaxAppendCount adds value to the "max_append_count" field.
func (_u *CodexTurnRunUpdate) AddMaxAppendCount(v int) *CodexTurnRunUpdate {
	_u.mutation.AddMaxAppendCount(v)
	return _u
}

// SetStartedAt sets the "started_at" field.
func (_u *CodexTurnRunUpdate) SetStartedAt(v time.Time) *CodexTurnRunUpdate {
	_u.mutation.SetStartedAt(v)
	return _u
}

// SetNillableStartedAt sets the "started_at" field if the given value is not nil.
func (_u *CodexTurnRunUpdate) SetNillableStartedAt(v *time.Time) *CodexTurnRunUpdate {
	if v != nil {
		_u.SetStartedAt(*v)
	}
	return _u
}

// SetHeartbeatAt sets the "heartbeat_at" field.
func (_u *CodexTurnRunUpdate) SetHeartbeatAt(v time.Time) *CodexTurnRunUpdate {
	_u.mutation.SetHeartbeatAt(v)
	return _u
}

// SetNillableHeartbeatAt sets the "heartbeat_at" field if the given value is not nil.
func (_u *CodexTurnRunUpdate) SetNillableHeartbeatAt(v *time.Time) *CodexTurnRunUpdate {
	if v != nil {
		_u.SetHeartbeatAt(*v)
	}
	return _u
}

// SetFinishedAt sets the "finished_at" field.
func (_u *CodexTurnRunUpdate) SetFinishedAt(v time.Time) *CodexTurnRunUpdate {
	_u.mutation.SetFinishedAt(v)
	return _u
}

// SetNillableFinishedAt sets the "finished_at" field if the given value is not nil.
func (_u *CodexTurnRunUpdate) SetNillableFinishedAt(v *time.Time) *CodexTurnRunUpdate {
	if v != nil {
		_u.SetFinishedAt(*v)
	}
	return _u
}

// ClearFinishedAt clears the value of the "finished_at" field.
func (_u *CodexTurnRunUpdate) ClearFinishedAt() *CodexTurnRunUpdate {
	_u.mutation.ClearFinishedAt()
	return _u
}

// SetErrorCode sets the "error_code" field.
func (_u *CodexTurnRunUpdate) SetErrorCode(v string) *CodexTurnRunUpdate {
	_u.mutation.SetErrorCode(v)
	return _u
}

// SetNillableErrorCode sets the "error_code" field if the given value is not nil.
func (_u *CodexTurnRunUpdate) SetNillableErrorCode(v *string) *CodexTurnRunUpdate {
	if v != nil {
		_u.SetErrorCode(*v)
	}
	return _u
}

// ClearErrorCode clears the value of the "error_code" field.
func (_u *CodexTurnRunUpdate) ClearErrorCode() *CodexTurnRunUpdate {
	_u.mutation.ClearErrorCode()
	return _u
}

// SetErrorMessage sets the "error_message" field.
func (_u *CodexTurnRunUpdate) SetErrorMessage(v string) *CodexTurnRunUpdate {
	_u.mutation.SetErrorMessage(v)
	return _u
}

// SetNillableErrorMessage sets the "error_message" field if the given value is not nil.
func (_u *CodexTurnRunUpdate) SetNillableErrorMessage(v *string) *CodexTurnRunUpdate {
	if v != nil {
		_u.SetErrorMessage(*v)
	}
	return _u
}

// ClearErrorMessage clears the value of the "error_message" field.
func (_u *CodexTurnRunUpdate) ClearErrorMessage() *CodexTurnRunUpdate {
	_u.mutation.ClearErrorMessage()
	return _u
}

// Mutation returns the CodexTurnRunMutation object of the builder.
func (_u *CodexTurnRunUpdate) Mutation() *CodexTurnRunMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *CodexTurnRunUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *CodexTurnRunUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *CodexTurnRunUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *CodexTurnRunUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *CodexTurnRunUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(codexturnrun.Table, codexturnrun.Columns, sqlgraph.NewFieldSpec(codexturnrun.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.ControlID(); ok {
		_spec.SetField(codexturnrun.FieldControlID, field.TypeUUID, value)
	}
	if value, ok := _u.mutation.PrimaryIntentID(); ok {
		_spec.SetField(codexturnrun.FieldPrimaryIntentID, field.TypeUUID, value)
	}
	if value, ok := _u.mutation.Attempt(); ok {
		_spec.SetField(codexturnrun.FieldAttempt, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedAttempt(); ok {
		_spec.AddField(codexturnrun.FieldAttempt, field.TypeInt, value)
	}
	if value, ok := _u.mutation.WorkerID(); ok {
		_spec.SetField(codexturnrun.FieldWorkerID, field.TypeString, value)
	}
	if value, ok := _u.mutation.LeaseEpoch(); ok {
		_spec.SetField(codexturnrun.FieldLeaseEpoch, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedLeaseEpoch(); ok {
		_spec.AddField(codexturnrun.FieldLeaseEpoch, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.CapabilityHash(); ok {
		_spec.SetField(codexturnrun.FieldCapabilityHash, field.TypeString, value)
	}
	if value, ok := _u.mutation.ExecutionNodeID(); ok {
		_spec.SetField(codexturnrun.FieldExecutionNodeID, field.TypeUUID, value)
	}
	if _u.mutation.ExecutionNodeIDCleared() {
		_spec.ClearField(codexturnrun.FieldExecutionNodeID, field.TypeUUID)
	}
	if value, ok := _u.mutation.WorkerEventSequence(); ok {
		_spec.SetField(codexturnrun.FieldWorkerEventSequence, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedWorkerEventSequence(); ok {
		_spec.AddField(codexturnrun.FieldWorkerEventSequence, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.WorkerTerminalKey(); ok {
		_spec.SetField(codexturnrun.FieldWorkerTerminalKey, field.TypeString, value)
	}
	if _u.mutation.WorkerTerminalKeyCleared() {
		_spec.ClearField(codexturnrun.FieldWorkerTerminalKey, field.TypeString)
	}
	if value, ok := _u.mutation.ActiveSlot(); ok {
		_spec.SetField(codexturnrun.FieldActiveSlot, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedActiveSlot(); ok {
		_spec.AddField(codexturnrun.FieldActiveSlot, field.TypeInt, value)
	}
	if _u.mutation.ActiveSlotCleared() {
		_spec.ClearField(codexturnrun.FieldActiveSlot, field.TypeInt)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(codexturnrun.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.CodexSubmissionID(); ok {
		_spec.SetField(codexturnrun.FieldCodexSubmissionID, field.TypeString, value)
	}
	if _u.mutation.CodexSubmissionIDCleared() {
		_spec.ClearField(codexturnrun.FieldCodexSubmissionID, field.TypeString)
	}
	if value, ok := _u.mutation.ConfirmedCodexTurnID(); ok {
		_spec.SetField(codexturnrun.FieldConfirmedCodexTurnID, field.TypeString, value)
	}
	if _u.mutation.ConfirmedCodexTurnIDCleared() {
		_spec.ClearField(codexturnrun.FieldConfirmedCodexTurnID, field.TypeString)
	}
	if value, ok := _u.mutation.AppendCount(); ok {
		_spec.SetField(codexturnrun.FieldAppendCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedAppendCount(); ok {
		_spec.AddField(codexturnrun.FieldAppendCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.MaxAppendCount(); ok {
		_spec.SetField(codexturnrun.FieldMaxAppendCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedMaxAppendCount(); ok {
		_spec.AddField(codexturnrun.FieldMaxAppendCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.StartedAt(); ok {
		_spec.SetField(codexturnrun.FieldStartedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.HeartbeatAt(); ok {
		_spec.SetField(codexturnrun.FieldHeartbeatAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.FinishedAt(); ok {
		_spec.SetField(codexturnrun.FieldFinishedAt, field.TypeTime, value)
	}
	if _u.mutation.FinishedAtCleared() {
		_spec.ClearField(codexturnrun.FieldFinishedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.ErrorCode(); ok {
		_spec.SetField(codexturnrun.FieldErrorCode, field.TypeString, value)
	}
	if _u.mutation.ErrorCodeCleared() {
		_spec.ClearField(codexturnrun.FieldErrorCode, field.TypeString)
	}
	if value, ok := _u.mutation.ErrorMessage(); ok {
		_spec.SetField(codexturnrun.FieldErrorMessage, field.TypeString, value)
	}
	if _u.mutation.ErrorMessageCleared() {
		_spec.ClearField(codexturnrun.FieldErrorMessage, field.TypeString)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{codexturnrun.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// CodexTurnRunUpdateOne is the builder for updating a single CodexTurnRun entity.
type CodexTurnRunUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *CodexTurnRunMutation
}

// SetControlID sets the "control_id" field.
func (_u *CodexTurnRunUpdateOne) SetControlID(v uuid.UUID) *CodexTurnRunUpdateOne {
	_u.mutation.SetControlID(v)
	return _u
}

// SetNillableControlID sets the "control_id" field if the given value is not nil.
func (_u *CodexTurnRunUpdateOne) SetNillableControlID(v *uuid.UUID) *CodexTurnRunUpdateOne {
	if v != nil {
		_u.SetControlID(*v)
	}
	return _u
}

// SetPrimaryIntentID sets the "primary_intent_id" field.
func (_u *CodexTurnRunUpdateOne) SetPrimaryIntentID(v uuid.UUID) *CodexTurnRunUpdateOne {
	_u.mutation.SetPrimaryIntentID(v)
	return _u
}

// SetNillablePrimaryIntentID sets the "primary_intent_id" field if the given value is not nil.
func (_u *CodexTurnRunUpdateOne) SetNillablePrimaryIntentID(v *uuid.UUID) *CodexTurnRunUpdateOne {
	if v != nil {
		_u.SetPrimaryIntentID(*v)
	}
	return _u
}

// SetAttempt sets the "attempt" field.
func (_u *CodexTurnRunUpdateOne) SetAttempt(v int) *CodexTurnRunUpdateOne {
	_u.mutation.ResetAttempt()
	_u.mutation.SetAttempt(v)
	return _u
}

// SetNillableAttempt sets the "attempt" field if the given value is not nil.
func (_u *CodexTurnRunUpdateOne) SetNillableAttempt(v *int) *CodexTurnRunUpdateOne {
	if v != nil {
		_u.SetAttempt(*v)
	}
	return _u
}

// AddAttempt adds value to the "attempt" field.
func (_u *CodexTurnRunUpdateOne) AddAttempt(v int) *CodexTurnRunUpdateOne {
	_u.mutation.AddAttempt(v)
	return _u
}

// SetWorkerID sets the "worker_id" field.
func (_u *CodexTurnRunUpdateOne) SetWorkerID(v string) *CodexTurnRunUpdateOne {
	_u.mutation.SetWorkerID(v)
	return _u
}

// SetNillableWorkerID sets the "worker_id" field if the given value is not nil.
func (_u *CodexTurnRunUpdateOne) SetNillableWorkerID(v *string) *CodexTurnRunUpdateOne {
	if v != nil {
		_u.SetWorkerID(*v)
	}
	return _u
}

// SetLeaseEpoch sets the "lease_epoch" field.
func (_u *CodexTurnRunUpdateOne) SetLeaseEpoch(v int64) *CodexTurnRunUpdateOne {
	_u.mutation.ResetLeaseEpoch()
	_u.mutation.SetLeaseEpoch(v)
	return _u
}

// SetNillableLeaseEpoch sets the "lease_epoch" field if the given value is not nil.
func (_u *CodexTurnRunUpdateOne) SetNillableLeaseEpoch(v *int64) *CodexTurnRunUpdateOne {
	if v != nil {
		_u.SetLeaseEpoch(*v)
	}
	return _u
}

// AddLeaseEpoch adds value to the "lease_epoch" field.
func (_u *CodexTurnRunUpdateOne) AddLeaseEpoch(v int64) *CodexTurnRunUpdateOne {
	_u.mutation.AddLeaseEpoch(v)
	return _u
}

// SetCapabilityHash sets the "capability_hash" field.
func (_u *CodexTurnRunUpdateOne) SetCapabilityHash(v string) *CodexTurnRunUpdateOne {
	_u.mutation.SetCapabilityHash(v)
	return _u
}

// SetNillableCapabilityHash sets the "capability_hash" field if the given value is not nil.
func (_u *CodexTurnRunUpdateOne) SetNillableCapabilityHash(v *string) *CodexTurnRunUpdateOne {
	if v != nil {
		_u.SetCapabilityHash(*v)
	}
	return _u
}

// SetExecutionNodeID sets the "execution_node_id" field.
func (_u *CodexTurnRunUpdateOne) SetExecutionNodeID(v uuid.UUID) *CodexTurnRunUpdateOne {
	_u.mutation.SetExecutionNodeID(v)
	return _u
}

// SetNillableExecutionNodeID sets the "execution_node_id" field if the given value is not nil.
func (_u *CodexTurnRunUpdateOne) SetNillableExecutionNodeID(v *uuid.UUID) *CodexTurnRunUpdateOne {
	if v != nil {
		_u.SetExecutionNodeID(*v)
	}
	return _u
}

// ClearExecutionNodeID clears the value of the "execution_node_id" field.
func (_u *CodexTurnRunUpdateOne) ClearExecutionNodeID() *CodexTurnRunUpdateOne {
	_u.mutation.ClearExecutionNodeID()
	return _u
}

// SetWorkerEventSequence sets the "worker_event_sequence" field.
func (_u *CodexTurnRunUpdateOne) SetWorkerEventSequence(v int64) *CodexTurnRunUpdateOne {
	_u.mutation.ResetWorkerEventSequence()
	_u.mutation.SetWorkerEventSequence(v)
	return _u
}

// SetNillableWorkerEventSequence sets the "worker_event_sequence" field if the given value is not nil.
func (_u *CodexTurnRunUpdateOne) SetNillableWorkerEventSequence(v *int64) *CodexTurnRunUpdateOne {
	if v != nil {
		_u.SetWorkerEventSequence(*v)
	}
	return _u
}

// AddWorkerEventSequence adds value to the "worker_event_sequence" field.
func (_u *CodexTurnRunUpdateOne) AddWorkerEventSequence(v int64) *CodexTurnRunUpdateOne {
	_u.mutation.AddWorkerEventSequence(v)
	return _u
}

// SetWorkerTerminalKey sets the "worker_terminal_key" field.
func (_u *CodexTurnRunUpdateOne) SetWorkerTerminalKey(v string) *CodexTurnRunUpdateOne {
	_u.mutation.SetWorkerTerminalKey(v)
	return _u
}

// SetNillableWorkerTerminalKey sets the "worker_terminal_key" field if the given value is not nil.
func (_u *CodexTurnRunUpdateOne) SetNillableWorkerTerminalKey(v *string) *CodexTurnRunUpdateOne {
	if v != nil {
		_u.SetWorkerTerminalKey(*v)
	}
	return _u
}

// ClearWorkerTerminalKey clears the value of the "worker_terminal_key" field.
func (_u *CodexTurnRunUpdateOne) ClearWorkerTerminalKey() *CodexTurnRunUpdateOne {
	_u.mutation.ClearWorkerTerminalKey()
	return _u
}

// SetActiveSlot sets the "active_slot" field.
func (_u *CodexTurnRunUpdateOne) SetActiveSlot(v int) *CodexTurnRunUpdateOne {
	_u.mutation.ResetActiveSlot()
	_u.mutation.SetActiveSlot(v)
	return _u
}

// SetNillableActiveSlot sets the "active_slot" field if the given value is not nil.
func (_u *CodexTurnRunUpdateOne) SetNillableActiveSlot(v *int) *CodexTurnRunUpdateOne {
	if v != nil {
		_u.SetActiveSlot(*v)
	}
	return _u
}

// AddActiveSlot adds value to the "active_slot" field.
func (_u *CodexTurnRunUpdateOne) AddActiveSlot(v int) *CodexTurnRunUpdateOne {
	_u.mutation.AddActiveSlot(v)
	return _u
}

// ClearActiveSlot clears the value of the "active_slot" field.
func (_u *CodexTurnRunUpdateOne) ClearActiveSlot() *CodexTurnRunUpdateOne {
	_u.mutation.ClearActiveSlot()
	return _u
}

// SetStatus sets the "status" field.
func (_u *CodexTurnRunUpdateOne) SetStatus(v string) *CodexTurnRunUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *CodexTurnRunUpdateOne) SetNillableStatus(v *string) *CodexTurnRunUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetCodexSubmissionID sets the "codex_submission_id" field.
func (_u *CodexTurnRunUpdateOne) SetCodexSubmissionID(v string) *CodexTurnRunUpdateOne {
	_u.mutation.SetCodexSubmissionID(v)
	return _u
}

// SetNillableCodexSubmissionID sets the "codex_submission_id" field if the given value is not nil.
func (_u *CodexTurnRunUpdateOne) SetNillableCodexSubmissionID(v *string) *CodexTurnRunUpdateOne {
	if v != nil {
		_u.SetCodexSubmissionID(*v)
	}
	return _u
}

// ClearCodexSubmissionID clears the value of the "codex_submission_id" field.
func (_u *CodexTurnRunUpdateOne) ClearCodexSubmissionID() *CodexTurnRunUpdateOne {
	_u.mutation.ClearCodexSubmissionID()
	return _u
}

// SetConfirmedCodexTurnID sets the "confirmed_codex_turn_id" field.
func (_u *CodexTurnRunUpdateOne) SetConfirmedCodexTurnID(v string) *CodexTurnRunUpdateOne {
	_u.mutation.SetConfirmedCodexTurnID(v)
	return _u
}

// SetNillableConfirmedCodexTurnID sets the "confirmed_codex_turn_id" field if the given value is not nil.
func (_u *CodexTurnRunUpdateOne) SetNillableConfirmedCodexTurnID(v *string) *CodexTurnRunUpdateOne {
	if v != nil {
		_u.SetConfirmedCodexTurnID(*v)
	}
	return _u
}

// ClearConfirmedCodexTurnID clears the value of the "confirmed_codex_turn_id" field.
func (_u *CodexTurnRunUpdateOne) ClearConfirmedCodexTurnID() *CodexTurnRunUpdateOne {
	_u.mutation.ClearConfirmedCodexTurnID()
	return _u
}

// SetAppendCount sets the "append_count" field.
func (_u *CodexTurnRunUpdateOne) SetAppendCount(v int) *CodexTurnRunUpdateOne {
	_u.mutation.ResetAppendCount()
	_u.mutation.SetAppendCount(v)
	return _u
}

// SetNillableAppendCount sets the "append_count" field if the given value is not nil.
func (_u *CodexTurnRunUpdateOne) SetNillableAppendCount(v *int) *CodexTurnRunUpdateOne {
	if v != nil {
		_u.SetAppendCount(*v)
	}
	return _u
}

// AddAppendCount adds value to the "append_count" field.
func (_u *CodexTurnRunUpdateOne) AddAppendCount(v int) *CodexTurnRunUpdateOne {
	_u.mutation.AddAppendCount(v)
	return _u
}

// SetMaxAppendCount sets the "max_append_count" field.
func (_u *CodexTurnRunUpdateOne) SetMaxAppendCount(v int) *CodexTurnRunUpdateOne {
	_u.mutation.ResetMaxAppendCount()
	_u.mutation.SetMaxAppendCount(v)
	return _u
}

// SetNillableMaxAppendCount sets the "max_append_count" field if the given value is not nil.
func (_u *CodexTurnRunUpdateOne) SetNillableMaxAppendCount(v *int) *CodexTurnRunUpdateOne {
	if v != nil {
		_u.SetMaxAppendCount(*v)
	}
	return _u
}

// AddMaxAppendCount adds value to the "max_append_count" field.
func (_u *CodexTurnRunUpdateOne) AddMaxAppendCount(v int) *CodexTurnRunUpdateOne {
	_u.mutation.AddMaxAppendCount(v)
	return _u
}

// SetStartedAt sets the "started_at" field.
func (_u *CodexTurnRunUpdateOne) SetStartedAt(v time.Time) *CodexTurnRunUpdateOne {
	_u.mutation.SetStartedAt(v)
	return _u
}

// SetNillableStartedAt sets the "started_at" field if the given value is not nil.
func (_u *CodexTurnRunUpdateOne) SetNillableStartedAt(v *time.Time) *CodexTurnRunUpdateOne {
	if v != nil {
		_u.SetStartedAt(*v)
	}
	return _u
}

// SetHeartbeatAt sets the "heartbeat_at" field.
func (_u *CodexTurnRunUpdateOne) SetHeartbeatAt(v time.Time) *CodexTurnRunUpdateOne {
	_u.mutation.SetHeartbeatAt(v)
	return _u
}

// SetNillableHeartbeatAt sets the "heartbeat_at" field if the given value is not nil.
func (_u *CodexTurnRunUpdateOne) SetNillableHeartbeatAt(v *time.Time) *CodexTurnRunUpdateOne {
	if v != nil {
		_u.SetHeartbeatAt(*v)
	}
	return _u
}

// SetFinishedAt sets the "finished_at" field.
func (_u *CodexTurnRunUpdateOne) SetFinishedAt(v time.Time) *CodexTurnRunUpdateOne {
	_u.mutation.SetFinishedAt(v)
	return _u
}

// SetNillableFinishedAt sets the "finished_at" field if the given value is not nil.
func (_u *CodexTurnRunUpdateOne) SetNillableFinishedAt(v *time.Time) *CodexTurnRunUpdateOne {
	if v != nil {
		_u.SetFinishedAt(*v)
	}
	return _u
}

// ClearFinishedAt clears the value of the "finished_at" field.
func (_u *CodexTurnRunUpdateOne) ClearFinishedAt() *CodexTurnRunUpdateOne {
	_u.mutation.ClearFinishedAt()
	return _u
}

// SetErrorCode sets the "error_code" field.
func (_u *CodexTurnRunUpdateOne) SetErrorCode(v string) *CodexTurnRunUpdateOne {
	_u.mutation.SetErrorCode(v)
	return _u
}

// SetNillableErrorCode sets the "error_code" field if the given value is not nil.
func (_u *CodexTurnRunUpdateOne) SetNillableErrorCode(v *string) *CodexTurnRunUpdateOne {
	if v != nil {
		_u.SetErrorCode(*v)
	}
	return _u
}

// ClearErrorCode clears the value of the "error_code" field.
func (_u *CodexTurnRunUpdateOne) ClearErrorCode() *CodexTurnRunUpdateOne {
	_u.mutation.ClearErrorCode()
	return _u
}

// SetErrorMessage sets the "error_message" field.
func (_u *CodexTurnRunUpdateOne) SetErrorMessage(v string) *CodexTurnRunUpdateOne {
	_u.mutation.SetErrorMessage(v)
	return _u
}

// SetNillableErrorMessage sets the "error_message" field if the given value is not nil.
func (_u *CodexTurnRunUpdateOne) SetNillableErrorMessage(v *string) *CodexTurnRunUpdateOne {
	if v != nil {
		_u.SetErrorMessage(*v)
	}
	return _u
}

// ClearErrorMessage clears the value of the "error_message" field.
func (_u *CodexTurnRunUpdateOne) ClearErrorMessage() *CodexTurnRunUpdateOne {
	_u.mutation.ClearErrorMessage()
	return _u
}

// Mutation returns the CodexTurnRunMutation object of the builder.
func (_u *CodexTurnRunUpdateOne) Mutation() *CodexTurnRunMutation {
	return _u.mutation
}

// Where appends a list predicates to the CodexTurnRunUpdate builder.
func (_u *CodexTurnRunUpdateOne) Where(ps ...predicate.CodexTurnRun) *CodexTurnRunUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *CodexTurnRunUpdateOne) Select(field string, fields ...string) *CodexTurnRunUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated CodexTurnRun entity.
func (_u *CodexTurnRunUpdateOne) Save(ctx context.Context) (*CodexTurnRun, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *CodexTurnRunUpdateOne) SaveX(ctx context.Context) *CodexTurnRun {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *CodexTurnRunUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *CodexTurnRunUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *CodexTurnRunUpdateOne) sqlSave(ctx context.Context) (_node *CodexTurnRun, err error) {
	_spec := sqlgraph.NewUpdateSpec(codexturnrun.Table, codexturnrun.Columns, sqlgraph.NewFieldSpec(codexturnrun.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "CodexTurnRun.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, codexturnrun.FieldID)
		for _, f := range fields {
			if !codexturnrun.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != codexturnrun.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.ControlID(); ok {
		_spec.SetField(codexturnrun.FieldControlID, field.TypeUUID, value)
	}
	if value, ok := _u.mutation.PrimaryIntentID(); ok {
		_spec.SetField(codexturnrun.FieldPrimaryIntentID, field.TypeUUID, value)
	}
	if value, ok := _u.mutation.Attempt(); ok {
		_spec.SetField(codexturnrun.FieldAttempt, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedAttempt(); ok {
		_spec.AddField(codexturnrun.FieldAttempt, field.TypeInt, value)
	}
	if value, ok := _u.mutation.WorkerID(); ok {
		_spec.SetField(codexturnrun.FieldWorkerID, field.TypeString, value)
	}
	if value, ok := _u.mutation.LeaseEpoch(); ok {
		_spec.SetField(codexturnrun.FieldLeaseEpoch, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedLeaseEpoch(); ok {
		_spec.AddField(codexturnrun.FieldLeaseEpoch, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.CapabilityHash(); ok {
		_spec.SetField(codexturnrun.FieldCapabilityHash, field.TypeString, value)
	}
	if value, ok := _u.mutation.ExecutionNodeID(); ok {
		_spec.SetField(codexturnrun.FieldExecutionNodeID, field.TypeUUID, value)
	}
	if _u.mutation.ExecutionNodeIDCleared() {
		_spec.ClearField(codexturnrun.FieldExecutionNodeID, field.TypeUUID)
	}
	if value, ok := _u.mutation.WorkerEventSequence(); ok {
		_spec.SetField(codexturnrun.FieldWorkerEventSequence, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedWorkerEventSequence(); ok {
		_spec.AddField(codexturnrun.FieldWorkerEventSequence, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.WorkerTerminalKey(); ok {
		_spec.SetField(codexturnrun.FieldWorkerTerminalKey, field.TypeString, value)
	}
	if _u.mutation.WorkerTerminalKeyCleared() {
		_spec.ClearField(codexturnrun.FieldWorkerTerminalKey, field.TypeString)
	}
	if value, ok := _u.mutation.ActiveSlot(); ok {
		_spec.SetField(codexturnrun.FieldActiveSlot, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedActiveSlot(); ok {
		_spec.AddField(codexturnrun.FieldActiveSlot, field.TypeInt, value)
	}
	if _u.mutation.ActiveSlotCleared() {
		_spec.ClearField(codexturnrun.FieldActiveSlot, field.TypeInt)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(codexturnrun.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.CodexSubmissionID(); ok {
		_spec.SetField(codexturnrun.FieldCodexSubmissionID, field.TypeString, value)
	}
	if _u.mutation.CodexSubmissionIDCleared() {
		_spec.ClearField(codexturnrun.FieldCodexSubmissionID, field.TypeString)
	}
	if value, ok := _u.mutation.ConfirmedCodexTurnID(); ok {
		_spec.SetField(codexturnrun.FieldConfirmedCodexTurnID, field.TypeString, value)
	}
	if _u.mutation.ConfirmedCodexTurnIDCleared() {
		_spec.ClearField(codexturnrun.FieldConfirmedCodexTurnID, field.TypeString)
	}
	if value, ok := _u.mutation.AppendCount(); ok {
		_spec.SetField(codexturnrun.FieldAppendCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedAppendCount(); ok {
		_spec.AddField(codexturnrun.FieldAppendCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.MaxAppendCount(); ok {
		_spec.SetField(codexturnrun.FieldMaxAppendCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedMaxAppendCount(); ok {
		_spec.AddField(codexturnrun.FieldMaxAppendCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.StartedAt(); ok {
		_spec.SetField(codexturnrun.FieldStartedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.HeartbeatAt(); ok {
		_spec.SetField(codexturnrun.FieldHeartbeatAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.FinishedAt(); ok {
		_spec.SetField(codexturnrun.FieldFinishedAt, field.TypeTime, value)
	}
	if _u.mutation.FinishedAtCleared() {
		_spec.ClearField(codexturnrun.FieldFinishedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.ErrorCode(); ok {
		_spec.SetField(codexturnrun.FieldErrorCode, field.TypeString, value)
	}
	if _u.mutation.ErrorCodeCleared() {
		_spec.ClearField(codexturnrun.FieldErrorCode, field.TypeString)
	}
	if value, ok := _u.mutation.ErrorMessage(); ok {
		_spec.SetField(codexturnrun.FieldErrorMessage, field.TypeString, value)
	}
	if _u.mutation.ErrorMessageCleared() {
		_spec.ClearField(codexturnrun.FieldErrorMessage, field.TypeString)
	}
	_node = &CodexTurnRun{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{codexturnrun.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
