// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/slovx2/tyrs-hand/ent/executionnode"
)

// ExecutionNodeCreate is the builder for creating a ExecutionNode entity.
type ExecutionNodeCreate struct {
	config
	mutation *ExecutionNodeMutation
	hooks    []Hook
}

// SetName sets the "name" field.
func (_c *ExecutionNodeCreate) SetName(v string) *ExecutionNodeCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetRoles sets the "roles" field.
func (_c *ExecutionNodeCreate) SetRoles(v []string) *ExecutionNodeCreate {
	_c.mutation.SetRoles(v)
	return _c
}

// SetEnabled sets the "enabled" field.
func (_c *ExecutionNodeCreate) SetEnabled(v bool) *ExecutionNodeCreate {
	_c.mutation.SetEnabled(v)
	return _c
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_c *ExecutionNodeCreate) SetNillableEnabled(v *bool) *ExecutionNodeCreate {
	if v != nil {
		_c.SetEnabled(*v)
	}
	return _c
}

// SetMaxConcurrentJobs sets the "max_concurrent_jobs" field.
func (_c *ExecutionNodeCreate) SetMaxConcurrentJobs(v int) *ExecutionNodeCreate {
	_c.mutation.SetMaxConcurrentJobs(v)
	return _c
}

// SetNillableMaxConcurrentJobs sets the "max_concurrent_jobs" field if the given value is not nil.
func (_c *ExecutionNodeCreate) SetNillableMaxConcurrentJobs(v *int) *ExecutionNodeCreate {
	if v != nil {
		_c.SetMaxConcurrentJobs(*v)
	}
	return _c
}

// SetCredentialHash sets the "credential_hash" field.
func (_c *ExecutionNodeCreate) SetCredentialHash(v string) *ExecutionNodeCreate {
	_c.mutation.SetCredentialHash(v)
	return _c
}

// SetNillableCredentialHash sets the "credential_hash" field if the given value is not nil.
func (_c *ExecutionNodeCreate) SetNillableCredentialHash(v *string) *ExecutionNodeCreate {
	if v != nil {
		_c.SetCredentialHash(*v)
	}
	return _c
}

// SetCredentialVersion sets the "credential_version" field.
func (_c *ExecutionNodeCreate) SetCredentialVersion(v int64) *ExecutionNodeCreate {
	_c.mutation.SetCredentialVersion(v)
	return _c
}

// SetNillableCredentialVersion sets the "credential_version" field if the given value is not nil.
func (_c *ExecutionNodeCreate) SetNillableCredentialVersion(v *int64) *ExecutionNodeCreate {
	if v != nil {
		_c.SetCredentialVersion(*v)
	}
	return _c
}

// SetProtocolVersion sets the "protocol_version" field.
func (_c *ExecutionNodeCreate) SetProtocolVersion(v int) *ExecutionNodeCreate {
	_c.mutation.SetProtocolVersion(v)
	return _c
}

// SetNillableProtocolVersion sets the "protocol_version" field if the given value is not nil.
func (_c *ExecutionNodeCreate) SetNillableProtocolVersion(v *int) *ExecutionNodeCreate {
	if v != nil {
		_c.SetProtocolVersion(*v)
	}
	return _c
}

// SetWorkerVersion sets the "worker_version" field.
func (_c *ExecutionNodeCreate) SetWorkerVersion(v string) *ExecutionNodeCreate {
	_c.mutation.SetWorkerVersion(v)
	return _c
}

// SetNillableWorkerVersion sets the "worker_version" field if the given value is not nil.
func (_c *ExecutionNodeCreate) SetNillableWorkerVersion(v *string) *ExecutionNodeCreate {
	if v != nil {
		_c.SetWorkerVersion(*v)
	}
	return _c
}

// SetStatus sets the "status" field.
func (_c *ExecutionNodeCreate) SetStatus(v string) *ExecutionNodeCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *ExecutionNodeCreate) SetNillableStatus(v *string) *ExecutionNodeCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetHeartbeatAt sets the "heartbeat_at" field.
func (_c *ExecutionNodeCreate) SetHeartbeatAt(v time.Time) *ExecutionNodeCreate {
	_c.mutation.SetHeartbeatAt(v)
	return _c
}

// SetNillableHeartbeatAt sets the "heartbeat_at" field if the given value is not nil.
func (_c *ExecutionNodeCreate) SetNillableHeartbeatAt(v *time.Time) *ExecutionNodeCreate {
	if v != nil {
		_c.SetHeartbeatAt(*v)
	}
	return _c
}

// SetLastError sets the "last_error" field.
func (_c *ExecutionNodeCreate) SetLastError(v string) *ExecutionNodeCreate {
	_c.mutation.SetLastError(v)
	return _c
}

// SetNillableLastError sets the "last_error" field if the given value is not nil.
func (_c *ExecutionNodeCreate) SetNillableLastError(v *string) *ExecutionNodeCreate {
	if v != nil {
		_c.SetLastError(*v)
	}
	return _c
}

// SetMetadata sets the "metadata" field.
func (_c *ExecutionNodeCreate) SetMetadata(v map[string]interface{}) *ExecutionNodeCreate {
	_c.mutation.SetMetadata(v)
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *ExecutionNodeCreate) SetCreatedAt(v time.Time) *ExecutionNodeCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *ExecutionNodeCreate) SetNillableCreatedAt(v *time.Time) *ExecutionNodeCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *ExecutionNodeCreate) SetUpdatedAt(v time.Time) *ExecutionNodeCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *ExecutionNodeCreate) SetNillableUpdatedAt(v *time.Time) *ExecutionNodeCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *ExecutionNodeCreate) SetID(v uuid.UUID) *ExecutionNodeCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *ExecutionNodeCreate) SetNillableID(v *uuid.UUID) *ExecutionNodeCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// Mutation returns the ExecutionNodeMutation object of the builder.
func (_c *ExecutionNodeCreate) Mutation() *ExecutionNodeMutation {
	return _c.mutation
}

// Save creates the ExecutionNode in the database.
func (_c *ExecutionNodeCreate) Save(ctx context.Context) (*ExecutionNode, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *ExecutionNodeCreate) SaveX(ctx context.Context) *ExecutionNode {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ExecutionNodeCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ExecutionNodeCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *ExecutionNodeCreate) defaults() {
	if _, ok := _c.mutation.Roles(); !ok {
		v := executionnode.DefaultRoles
		_c.mutation.SetRoles(v)
	}
	if _, ok := _c.mutation.Enabled(); !ok {
		v := executionnode.DefaultEnabled
		_c.mutation.SetEnabled(v)
	}
	if _, ok := _c.mutation.MaxConcurrentJobs(); !ok {
		v := executionnode.DefaultMaxConcurrentJobs
		_c.mutation.SetMaxConcurrentJobs(v)
	}
	if _, ok := _c.mutation.CredentialVersion(); !ok {
		v := executionnode.DefaultCredentialVersion
		_c.mutation.SetCredentialVersion(v)
	}
	if _, ok := _c.mutation.ProtocolVersion(); !ok {
		v := executionnode.DefaultProtocolVersion
		_c.mutation.SetProtocolVersion(v)
	}
	if _, ok := _c.mutation.Status(); !ok {
		v := executionnode.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.Metadata(); !ok {
		v := executionnode.DefaultMetadata
		_c.mutation.SetMetadata(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := executionnode.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := executionnode.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := executionnode.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *ExecutionNodeCreate) check() error {
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "ExecutionNode.name"`)}
	}
	if _, ok := _c.mutation.Roles(); !ok {
		return &ValidationError{Name: "roles", err: errors.New(`ent: missing required field "ExecutionNode.roles"`)}
	}
	if _, ok := _c.mutation.Enabled(); !ok {
		return &ValidationError{Name: "enabled", err: errors.New(`ent: missing required field "ExecutionNode.enabled"`)}
	}
	if _, ok := _c.mutation.MaxConcurrentJobs(); !ok {
		return &ValidationError{Name: "max_concurrent_jobs", err: errors.New(`ent: missing required field "ExecutionNode.max_concurrent_jobs"`)}
	}
	if _, ok := _c.mutation.CredentialVersion(); !ok {
		return &ValidationError{Name: "credential_version", err: errors.New(`ent: missing required field "ExecutionNode.credential_version"`)}
	}
	if _, ok := _c.mutation.ProtocolVersion(); !ok {
		return &ValidationError{Name: "protocol_version", err: errors.New(`ent: missing required field "ExecutionNode.protocol_version"`)}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "ExecutionNode.status"`)}
	}
	if _, ok := _c.mutation.Metadata(); !ok {
		return &ValidationError{Name: "metadata", err: errors.New(`ent: missing required field "ExecutionNode.metadata"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "ExecutionNode.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "ExecutionNode.updated_at"`)}
	}
	return nil
}

func (_c *ExecutionNodeCreate) sqlSave(ctx context.Context) (*ExecutionNode, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *ExecutionNodeCreate) createSpec() (*ExecutionNode, *sqlgraph.CreateSpec) {
	var (
		_node = &ExecutionNode{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(executionnode.Table, sqlgraph.NewFieldSpec(executionnode.FieldID, field.TypeUUID))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(executionnode.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.Roles(); ok {
		_spec.SetField(executionnode.FieldRoles, field.TypeJSON, value)
		_node.Roles = value
	}
	if value, ok := _c.mutation.Enabled(); ok {
		_spec.SetField(executionnode.FieldEnabled, field.TypeBool, value)
		_node.Enabled = value
	}
	if value, ok := _c.mutation.MaxConcurrentJobs(); ok {
		_spec.SetField(executionnode.FieldMaxConcurrentJobs, field.TypeInt, value)
		_node.MaxConcurrentJobs = value
	}
	if value, ok := _c.mutation.CredentialHash(); ok {
		_spec.SetField(executionnode.FieldCredentialHash, field.TypeString, value)
		_node.CredentialHash = &value
	}
	if value, ok := _c.mutation.CredentialVersion(); ok {
		_spec.SetField(executionnode.FieldCredentialVersion, field.TypeInt64, value)
		_node.CredentialVersion = value
	}
	if value, ok := _c.mutation.ProtocolVersion(); ok {
		_spec.SetField(executionnode.FieldProtocolVersion, field.TypeInt, value)
		_node.ProtocolVersion = value
	}
	if value, ok := _c.mutation.WorkerVersion(); ok {
		_spec.SetField(executionnode.FieldWorkerVersion, field.TypeString, value)
		_node.WorkerVersion = &value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(executionnode.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.HeartbeatAt(); ok {
		_spec.SetField(executionnode.FieldHeartbeatAt, field.TypeTime, value)
		_node.HeartbeatAt = &value
	}
	if value, ok := _c.mutation.LastError(); ok {
		_spec.SetField(executionnode.FieldLastError, field.TypeString, value)
		_node.LastError = &value
	}
	if value, ok := _c.mutation.Metadata(); ok {
		_spec.SetField(executionnode.FieldMetadata, field.TypeJSON, value)
		_node.Metadata = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(executionnode.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(executionnode.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	return _node, _spec
}

// ExecutionNodeCreateBulk is the builder for creating many ExecutionNode entities in bulk.
type ExecutionNodeCreateBulk struct {
	config
	err      error
	builders []*ExecutionNodeCreate
}

// Save creates the ExecutionNode entities in the database.
func (_c *ExecutionNodeCreateBulk) Save(ctx context.Context) ([]*ExecutionNode, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*ExecutionNode, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ExecutionNodeMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *ExecutionNodeCreateBulk) SaveX(ctx context.Context) []*ExecutionNode {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ExecutionNodeCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ExecutionNodeCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
