// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/slovx2/tyrs-hand/ent/platformsetting"
)

// PlatformSetting is the model entity for the PlatformSetting schema.
type PlatformSetting struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// SettingKey holds the value of the "setting_key" field.
	SettingKey string `json:"setting_key,omitempty"`
	// Value holds the value of the "value" field.
	Value map[string]interface{} `json:"value,omitempty"`
	// Version holds the value of the "version" field.
	Version int64 `json:"version,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt    time.Time `json:"updated_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*PlatformSetting) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case platformsetting.FieldValue:
			values[i] = new([]byte)
		case platformsetting.FieldID, platformsetting.FieldVersion:
			values[i] = new(sql.NullInt64)
		case platformsetting.FieldSettingKey:
			values[i] = new(sql.NullString)
		case platformsetting.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the PlatformSetting fields.
func (_m *PlatformSetting) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case platformsetting.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case platformsetting.FieldSettingKey:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field setting_key", values[i])
			} else if value.Valid {
				_m.SettingKey = value.String
			}
		case platformsetting.FieldValue:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field value", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.Value); err != nil {
					return fmt.Errorf("unmarshal field value: %w", err)
				}
			}
		case platformsetting.FieldVersion:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field version", values[i])
			} else if value.Valid {
				_m.Version = value.Int64
			}
		case platformsetting.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// GetValue returns the ent.Value that was dynamically selected and assigned to the PlatformSetting.
// This includes values selected through modifiers, order, etc.
func (_m *PlatformSetting) GetValue(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this PlatformSetting.
// Note that you need to call PlatformSetting.Unwrap() before calling this method if this PlatformSetting
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *PlatformSetting) Update() *PlatformSettingUpdateOne {
	return NewPlatformSettingClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the PlatformSetting entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *PlatformSetting) Unwrap() *PlatformSetting {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: PlatformSetting is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *PlatformSetting) String() string {
	var builder strings.Builder
	builder.WriteString("PlatformSetting(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("setting_key=")
	builder.WriteString(_m.SettingKey)
	builder.WriteString(", ")
	builder.WriteString("value=")
	builder.WriteString(fmt.Sprintf("%v", _m.Value))
	builder.WriteString(", ")
	builder.WriteString("version=")
	builder.WriteString(fmt.Sprintf("%v", _m.Version))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// PlatformSettings is a parsable slice of PlatformSetting.
type PlatformSettings []*PlatformSetting
