// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/slovx2/tyrs-hand/ent/predicate"
	"github.com/slovx2/tyrs-hand/ent/repository"
)

// RepositoryUpdate is the builder for updating Repository entities.
type RepositoryUpdate struct {
	config
	hooks    []Hook
	mutation *RepositoryMutation
}

// Where appends a list predicates to the RepositoryUpdate builder.
func (_u *RepositoryUpdate) Where(ps ...predicate.Repository) *RepositoryUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetInstallationID sets the "installation_id" field.
func (_u *RepositoryUpdate) SetInstallationID(v uuid.UUID) *RepositoryUpdate {
	_u.mutation.SetInstallationID(v)
	return _u
}

// SetNillableInstallationID sets the "installation_id" field if the given value is not nil.
func (_u *RepositoryUpdate) SetNillableInstallationID(v *uuid.UUID) *RepositoryUpdate {
	if v != nil {
		_u.SetInstallationID(*v)
	}
	return _u
}

// SetProvider sets the "provider" field.
func (_u *RepositoryUpdate) SetProvider(v string) *RepositoryUpdate {
	_u.mutation.SetProvider(v)
	return _u
}

// SetNillableProvider sets the "provider" field if the given value is not nil.
func (_u *RepositoryUpdate) SetNillableProvider(v *string) *RepositoryUpdate {
	if v != nil {
		_u.SetProvider(*v)
	}
	return _u
}

// SetExternalID sets the "external_id" field.
func (_u *RepositoryUpdate) SetExternalID(v int64) *RepositoryUpdate {
	_u.mutation.ResetExternalID()
	_u.mutation.SetExternalID(v)
	return _u
}

// SetNillableExternalID sets the "external_id" field if the given value is not nil.
func (_u *RepositoryUpdate) SetNillableExternalID(v *int64) *RepositoryUpdate {
	if v != nil {
		_u.SetExternalID(*v)
	}
	return _u
}

// AddExternalID adds value to the "external_id" field.
func (_u *RepositoryUpdate) AddExternalID(v int64) *RepositoryUpdate {
	_u.mutation.AddExternalID(v)
	return _u
}

// SetOwner sets the "owner" field.
func (_u *RepositoryUpdate) SetOwner(v string) *RepositoryUpdate {
	_u.mutation.SetOwner(v)
	return _u
}

// SetNillableOwner sets the "owner" field if the given value is not nil.
func (_u *RepositoryUpdate) SetNillableOwner(v *string) *RepositoryUpdate {
	if v != nil {
		_u.SetOwner(*v)
	}
	return _u
}

// SetName sets the "name" field.
func (_u *RepositoryUpdate) SetName(v string) *RepositoryUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *RepositoryUpdate) SetNillableName(v *string) *RepositoryUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetDefaultBranch sets the "default_branch" field.
func (_u *RepositoryUpdate) SetDefaultBranch(v string) *RepositoryUpdate {
	_u.mutation.SetDefaultBranch(v)
	return _u
}

// SetNillableDefaultBranch sets the "default_branch" field if the given value is not nil.
func (_u *RepositoryUpdate) SetNillableDefaultBranch(v *string) *RepositoryUpdate {
	if v != nil {
		_u.SetDefaultBranch(*v)
	}
	return _u
}

// SetCloneURL sets the "clone_url" field.
func (_u *RepositoryUpdate) SetCloneURL(v string) *RepositoryUpdate {
	_u.mutation.SetCloneURL(v)
	return _u
}

// SetNillableCloneURL sets the "clone_url" field if the given value is not nil.
func (_u *RepositoryUpdate) SetNillableCloneURL(v *string) *RepositoryUpdate {
	if v != nil {
		_u.SetCloneURL(*v)
	}
	return _u
}

// SetEnabled sets the "enabled" field.
func (_u *RepositoryUpdate) SetEnabled(v bool) *RepositoryUpdate {
	_u.mutation.SetEnabled(v)
	return _u
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_u *RepositoryUpdate) SetNillableEnabled(v *bool) *RepositoryUpdate {
	if v != nil {
		_u.SetEnabled(*v)
	}
	return _u
}

// SetMetadata sets the "metadata" field.
func (_u *RepositoryUpdate) SetMetadata(v map[string]interface{}) *RepositoryUpdate {
	_u.mutation.SetMetadata(v)
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *RepositoryUpdate) SetCreatedAt(v time.Time) *RepositoryUpdate {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *RepositoryUpdate) SetNillableCreatedAt(v *time.Time) *RepositoryUpdate {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *RepositoryUpdate) SetUpdatedAt(v time.Time) *RepositoryUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the RepositoryMutation object of the builder.
func (_u *RepositoryUpdate) Mutation() *RepositoryMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *RepositoryUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *RepositoryUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *RepositoryUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *RepositoryUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *RepositoryUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := repository.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

func (_u *RepositoryUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(repository.Table, repository.Columns, sqlgraph.NewFieldSpec(repository.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.InstallationID(); ok {
		_spec.SetField(repository.FieldInstallationID, field.TypeUUID, value)
	}
	if value, ok := _u.mutation.Provider(); ok {
		_spec.SetField(repository.FieldProvider, field.TypeString, value)
	}
	if value, ok := _u.mutation.ExternalID(); ok {
		_spec.SetField(repository.FieldExternalID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedExternalID(); ok {
		_spec.AddField(repository.FieldExternalID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Owner(); ok {
		_spec.SetField(repository.FieldOwner, field.TypeString, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(repository.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.DefaultBranch(); ok {
		_spec.SetField(repository.FieldDefaultBranch, field.TypeString, value)
	}
	if value, ok := _u.mutation.CloneURL(); ok {
		_spec.SetField(repository.FieldCloneURL, field.TypeString, value)
	}
	if value, ok := _u.mutation.Enabled(); ok {
		_spec.SetField(repository.FieldEnabled, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Metadata(); ok {
		_spec.SetField(repository.FieldMetadata, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(repository.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(repository.FieldUpdatedAt, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{repository.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// RepositoryUpdateOne is the builder for updating a single Repository entity.
type RepositoryUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *RepositoryMutation
}

// SetInstallationID sets the "installation_id" field.
func (_u *RepositoryUpdateOne) SetInstallationID(v uuid.UUID) *RepositoryUpdateOne {
	_u.mutation.SetInstallationID(v)
	return _u
}

// SetNillableInstallationID sets the "installation_id" field if the given value is not nil.
func (_u *RepositoryUpdateOne) SetNillableInstallationID(v *uuid.UUID) *RepositoryUpdateOne {
	if v != nil {
		_u.SetInstallationID(*v)
	}
	return _u
}

// SetProvider sets the "provider" field.
func (_u *RepositoryUpdateOne) SetProvider(v string) *RepositoryUpdateOne {
	_u.mutation.SetProvider(v)
	return _u
}

// SetNillableProvider sets the "provider" field if the given value is not nil.
func (_u *RepositoryUpdateOne) SetNillableProvider(v *string) *RepositoryUpdateOne {
	if v != nil {
		_u.SetProvider(*v)
	}
	return _u
}

// SetExternalID sets the "external_id" field.
func (_u *RepositoryUpdateOne) SetExternalID(v int64) *RepositoryUpdateOne {
	_u.mutation.ResetExternalID()
	_u.mutation.SetExternalID(v)
	return _u
}

// SetNillableExternalID sets the "external_id" field if the given value is not nil.
func (_u *RepositoryUpdateOne) SetNillableExternalID(v *int64) *RepositoryUpdateOne {
	if v != nil {
		_u.SetExternalID(*v)
	}
	return _u
}

// AddExternalID adds value to the "external_id" field.
func (_u *RepositoryUpdateOne) AddExternalID(v int64) *RepositoryUpdateOne {
	_u.mutation.AddExternalID(v)
	return _u
}

// SetOwner sets the "owner" field.
func (_u *RepositoryUpdateOne) SetOwner(v string) *RepositoryUpdateOne {
	_u.mutation.SetOwner(v)
	return _u
}

// SetNillableOwner sets the "owner" field if the given value is not nil.
func (_u *RepositoryUpdateOne) SetNillableOwner(v *string) *RepositoryUpdateOne {
	if v != nil {
		_u.SetOwner(*v)
	}
	return _u
}

// SetName sets the "name" field.
func (_u *RepositoryUpdateOne) SetName(v string) *RepositoryUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *RepositoryUpdateOne) SetNillableName(v *string) *RepositoryUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetDefaultBranch sets the "default_branch" field.
func (_u *RepositoryUpdateOne) SetDefaultBranch(v string) *RepositoryUpdateOne {
	_u.mutation.SetDefaultBranch(v)
	return _u
}

// SetNillableDefaultBranch sets the "default_branch" field if the given value is not nil.
func (_u *RepositoryUpdateOne) SetNillableDefaultBranch(v *string) *RepositoryUpdateOne {
	if v != nil {
		_u.SetDefaultBranch(*v)
	}
	return _u
}

// SetCloneURL sets the "clone_url" field.
func (_u *RepositoryUpdateOne) SetCloneURL(v string) *RepositoryUpdateOne {
	_u.mutation.SetCloneURL(v)
	return _u
}

// SetNillableCloneURL sets the "clone_url" field if the given value is not nil.
func (_u *RepositoryUpdateOne) SetNillableCloneURL(v *string) *RepositoryUpdateOne {
	if v != nil {
		_u.SetCloneURL(*v)
	}
	return _u
}

// SetEnabled sets the "enabled" field.
func (_u *RepositoryUpdateOne) SetEnabled(v bool) *RepositoryUpdateOne {
	_u.mutation.SetEnabled(v)
	return _u
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_u *RepositoryUpdateOne) SetNillableEnabled(v *bool) *RepositoryUpdateOne {
	if v != nil {
		_u.SetEnabled(*v)
	}
	return _u
}

// SetMetadata sets the "metadata" field.
func (_u *RepositoryUpdateOne) SetMetadata(v map[string]interface{}) *RepositoryUpdateOne {
	_u.mutation.SetMetadata(v)
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *RepositoryUpdateOne) SetCreatedAt(v time.Time) *RepositoryUpdateOne {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *RepositoryUpdateOne) SetNillableCreatedAt(v *time.Time) *RepositoryUpdateOne {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *RepositoryUpdateOne) SetUpdatedAt(v time.Time) *RepositoryUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the RepositoryMutation object of the builder.
func (_u *RepositoryUpdateOne) Mutation() *RepositoryMutation {
	return _u.mutation
}

// Where appends a list predicates to the RepositoryUpdate builder.
func (_u *RepositoryUpdateOne) Where(ps ...predicate.Repository) *RepositoryUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *RepositoryUpdateOne) Select(field string, fields ...string) *RepositoryUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Repository entity.
func (_u *RepositoryUpdateOne) Save(ctx context.Context) (*Repository, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *RepositoryUpdateOne) SaveX(ctx context.Context) *Repository {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *RepositoryUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *RepositoryUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *RepositoryUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := repository.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

func (_u *RepositoryUpdateOne) sqlSave(ctx context.Context) (_node *Repository, err error) {
	_spec := sqlgraph.NewUpdateSpec(repository.Table, repository.Columns, sqlgraph.NewFieldSpec(repository.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Repository.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, repository.FieldID)
		for _, f := range fields {
			if !repository.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != repository.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.InstallationID(); ok {
		_spec.SetField(repository.FieldInstallationID, field.TypeUUID, value)
	}
	if value, ok := _u.mutation.Provider(); ok {
		_spec.SetField(repository.FieldProvider, field.TypeString, value)
	}
	if value, ok := _u.mutation.ExternalID(); ok {
		_spec.SetField(repository.FieldExternalID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedExternalID(); ok {
		_spec.AddField(repository.FieldExternalID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Owner(); ok {
		_spec.SetField(repository.FieldOwner, field.TypeString, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(repository.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.DefaultBranch(); ok {
		_spec.SetField(repository.FieldDefaultBranch, field.TypeString, value)
	}
	if value, ok := _u.mutation.CloneURL(); ok {
		_spec.SetField(repository.FieldCloneURL, field.TypeString, value)
	}
	if value, ok := _u.mutation.Enabled(); ok {
		_spec.SetField(repository.FieldEnabled, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Metadata(); ok {
		_spec.SetField(repository.FieldMetadata, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(repository.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(repository.FieldUpdatedAt, field.TypeTime, value)
	}
	_node = &Repository{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{repository.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
