// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/slovx2/tyrs-hand/ent/repocache"
)

// RepoCacheCreate is the builder for creating a RepoCache entity.
type RepoCacheCreate struct {
	config
	mutation *RepoCacheMutation
	hooks    []Hook
}

// SetRepositoryID sets the "repository_id" field.
func (_c *RepoCacheCreate) SetRepositoryID(v uuid.UUID) *RepoCacheCreate {
	_c.mutation.SetRepositoryID(v)
	return _c
}

// SetPath sets the "path" field.
func (_c *RepoCacheCreate) SetPath(v string) *RepoCacheCreate {
	_c.mutation.SetPath(v)
	return _c
}

// SetStatus sets the "status" field.
func (_c *RepoCacheCreate) SetStatus(v string) *RepoCacheCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *RepoCacheCreate) SetNillableStatus(v *string) *RepoCacheCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetSizeBytes sets the "size_bytes" field.
func (_c *RepoCacheCreate) SetSizeBytes(v int64) *RepoCacheCreate {
	_c.mutation.SetSizeBytes(v)
	return _c
}

// SetNillableSizeBytes sets the "size_bytes" field if the given value is not nil.
func (_c *RepoCacheCreate) SetNillableSizeBytes(v *int64) *RepoCacheCreate {
	if v != nil {
		_c.SetSizeBytes(*v)
	}
	return _c
}

// SetLastFetchAt sets the "last_fetch_at" field.
func (_c *RepoCacheCreate) SetLastFetchAt(v time.Time) *RepoCacheCreate {
	_c.mutation.SetLastFetchAt(v)
	return _c
}

// SetNillableLastFetchAt sets the "last_fetch_at" field if the given value is not nil.
func (_c *RepoCacheCreate) SetNillableLastFetchAt(v *time.Time) *RepoCacheCreate {
	if v != nil {
		_c.SetLastFetchAt(*v)
	}
	return _c
}

// SetLastUsedAt sets the "last_used_at" field.
func (_c *RepoCacheCreate) SetLastUsedAt(v time.Time) *RepoCacheCreate {
	_c.mutation.SetLastUsedAt(v)
	return _c
}

// SetNillableLastUsedAt sets the "last_used_at" field if the given value is not nil.
func (_c *RepoCacheCreate) SetNillableLastUsedAt(v *time.Time) *RepoCacheCreate {
	if v != nil {
		_c.SetLastUsedAt(*v)
	}
	return _c
}

// SetError sets the "error" field.
func (_c *RepoCacheCreate) SetError(v string) *RepoCacheCreate {
	_c.mutation.SetError(v)
	return _c
}

// SetNillableError sets the "error" field if the given value is not nil.
func (_c *RepoCacheCreate) SetNillableError(v *string) *RepoCacheCreate {
	if v != nil {
		_c.SetError(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *RepoCacheCreate) SetID(v uuid.UUID) *RepoCacheCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *RepoCacheCreate) SetNillableID(v *uuid.UUID) *RepoCacheCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// Mutation returns the RepoCacheMutation object of the builder.
func (_c *RepoCacheCreate) Mutation() *RepoCacheMutation {
	return _c.mutation
}

// Save creates the RepoCache in the database.
func (_c *RepoCacheCreate) Save(ctx context.Context) (*RepoCache, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *RepoCacheCreate) SaveX(ctx context.Context) *RepoCache {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *RepoCacheCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *RepoCacheCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *RepoCacheCreate) defaults() {
	if _, ok := _c.mutation.Status(); !ok {
		v := repocache.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.SizeBytes(); !ok {
		v := repocache.DefaultSizeBytes
		_c.mutation.SetSizeBytes(v)
	}
	if _, ok := _c.mutation.LastUsedAt(); !ok {
		v := repocache.DefaultLastUsedAt()
		_c.mutation.SetLastUsedAt(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := repocache.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *RepoCacheCreate) check() error {
	if _, ok := _c.mutation.RepositoryID(); !ok {
		return &ValidationError{Name: "repository_id", err: errors.New(`ent: missing required field "RepoCache.repository_id"`)}
	}
	if _, ok := _c.mutation.Path(); !ok {
		return &ValidationError{Name: "path", err: errors.New(`ent: missing required field "RepoCache.path"`)}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "RepoCache.status"`)}
	}
	if _, ok := _c.mutation.SizeBytes(); !ok {
		return &ValidationError{Name: "size_bytes", err: errors.New(`ent: missing required field "RepoCache.size_bytes"`)}
	}
	if _, ok := _c.mutation.LastUsedAt(); !ok {
		return &ValidationError{Name: "last_used_at", err: errors.New(`ent: missing required field "RepoCache.last_used_at"`)}
	}
	return nil
}

func (_c *RepoCacheCreate) sqlSave(ctx context.Context) (*RepoCache, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *RepoCacheCreate) createSpec() (*RepoCache, *sqlgraph.CreateSpec) {
	var (
		_node = &RepoCache{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(repocache.Table, sqlgraph.NewFieldSpec(repocache.FieldID, field.TypeUUID))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.RepositoryID(); ok {
		_spec.SetField(repocache.FieldRepositoryID, field.TypeUUID, value)
		_node.RepositoryID = value
	}
	if value, ok := _c.mutation.Path(); ok {
		_spec.SetField(repocache.FieldPath, field.TypeString, value)
		_node.Path = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(repocache.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.SizeBytes(); ok {
		_spec.SetField(repocache.FieldSizeBytes, field.TypeInt64, value)
		_node.SizeBytes = value
	}
	if value, ok := _c.mutation.LastFetchAt(); ok {
		_spec.SetField(repocache.FieldLastFetchAt, field.TypeTime, value)
		_node.LastFetchAt = &value
	}
	if value, ok := _c.mutation.LastUsedAt(); ok {
		_spec.SetField(repocache.FieldLastUsedAt, field.TypeTime, value)
		_node.LastUsedAt = value
	}
	if value, ok := _c.mutation.Error(); ok {
		_spec.SetField(repocache.FieldError, field.TypeString, value)
		_node.Error = &value
	}
	return _node, _spec
}

// RepoCacheCreateBulk is the builder for creating many RepoCache entities in bulk.
type RepoCacheCreateBulk struct {
	config
	err      error
	builders []*RepoCacheCreate
}

// Save creates the RepoCache entities in the database.
func (_c *RepoCacheCreateBulk) Save(ctx context.Context) ([]*RepoCache, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*RepoCache, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*RepoCacheMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *RepoCacheCreateBulk) SaveX(ctx context.Context) []*RepoCache {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *RepoCacheCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *RepoCacheCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
