// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/dialect/sql/sqljson"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/slovx2/tyrs-hand/ent/predicate"
	"github.com/slovx2/tyrs-hand/ent/triggerrule"
)

// TriggerRuleUpdate is the builder for updating TriggerRule entities.
type TriggerRuleUpdate struct {
	config
	hooks    []Hook
	mutation *TriggerRuleMutation
}

// Where appends a list predicates to the TriggerRuleUpdate builder.
func (_u *TriggerRuleUpdate) Where(ps ...predicate.TriggerRule) *TriggerRuleUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetRepositoryID sets the "repository_id" field.
func (_u *TriggerRuleUpdate) SetRepositoryID(v uuid.UUID) *TriggerRuleUpdate {
	_u.mutation.SetRepositoryID(v)
	return _u
}

// SetNillableRepositoryID sets the "repository_id" field if the given value is not nil.
func (_u *TriggerRuleUpdate) SetNillableRepositoryID(v *uuid.UUID) *TriggerRuleUpdate {
	if v != nil {
		_u.SetRepositoryID(*v)
	}
	return _u
}

// SetAgentProfileID sets the "agent_profile_id" field.
func (_u *TriggerRuleUpdate) SetAgentProfileID(v uuid.UUID) *TriggerRuleUpdate {
	_u.mutation.SetAgentProfileID(v)
	return _u
}

// SetNillableAgentProfileID sets the "agent_profile_id" field if the given value is not nil.
func (_u *TriggerRuleUpdate) SetNillableAgentProfileID(v *uuid.UUID) *TriggerRuleUpdate {
	if v != nil {
		_u.SetAgentProfileID(*v)
	}
	return _u
}

// SetName sets the "name" field.
func (_u *TriggerRuleUpdate) SetName(v string) *TriggerRuleUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *TriggerRuleUpdate) SetNillableName(v *string) *TriggerRuleUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetEventName sets the "event_name" field.
func (_u *TriggerRuleUpdate) SetEventName(v string) *TriggerRuleUpdate {
	_u.mutation.SetEventName(v)
	return _u
}

// SetNillableEventName sets the "event_name" field if the given value is not nil.
func (_u *TriggerRuleUpdate) SetNillableEventName(v *string) *TriggerRuleUpdate {
	if v != nil {
		_u.SetEventName(*v)
	}
	return _u
}

// SetAction sets the "action" field.
func (_u *TriggerRuleUpdate) SetAction(v string) *TriggerRuleUpdate {
	_u.mutation.SetAction(v)
	return _u
}

// SetNillableAction sets the "action" field if the given value is not nil.
func (_u *TriggerRuleUpdate) SetNillableAction(v *string) *TriggerRuleUpdate {
	if v != nil {
		_u.SetAction(*v)
	}
	return _u
}

// ClearAction clears the value of the "action" field.
func (_u *TriggerRuleUpdate) ClearAction() *TriggerRuleUpdate {
	_u.mutation.ClearAction()
	return _u
}

// SetEnabled sets the "enabled" field.
func (_u *TriggerRuleUpdate) SetEnabled(v bool) *TriggerRuleUpdate {
	_u.mutation.SetEnabled(v)
	return _u
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_u *TriggerRuleUpdate) SetNillableEnabled(v *bool) *TriggerRuleUpdate {
	if v != nil {
		_u.SetEnabled(*v)
	}
	return _u
}

// SetPriority sets the "priority" field.
func (_u *TriggerRuleUpdate) SetPriority(v int) *TriggerRuleUpdate {
	_u.mutation.ResetPriority()
	_u.mutation.SetPriority(v)
	return _u
}

// SetNillablePriority sets the "priority" field if the given value is not nil.
func (_u *TriggerRuleUpdate) SetNillablePriority(v *int) *TriggerRuleUpdate {
	if v != nil {
		_u.SetPriority(*v)
	}
	return _u
}

// AddPriority adds value to the "priority" field.
func (_u *TriggerRuleUpdate) AddPriority(v int) *TriggerRuleUpdate {
	_u.mutation.AddPriority(v)
	return _u
}

// SetActorMinPermission sets the "actor_min_permission" field.
func (_u *TriggerRuleUpdate) SetActorMinPermission(v string) *TriggerRuleUpdate {
	_u.mutation.SetActorMinPermission(v)
	return _u
}

// SetNillableActorMinPermission sets the "actor_min_permission" field if the given value is not nil.
func (_u *TriggerRuleUpdate) SetNillableActorMinPermission(v *string) *TriggerRuleUpdate {
	if v != nil {
		_u.SetActorMinPermission(*v)
	}
	return _u
}

// SetMentionRequired sets the "mention_required" field.
func (_u *TriggerRuleUpdate) SetMentionRequired(v bool) *TriggerRuleUpdate {
	_u.mutation.SetMentionRequired(v)
	return _u
}

// SetNillableMentionRequired sets the "mention_required" field if the given value is not nil.
func (_u *TriggerRuleUpdate) SetNillableMentionRequired(v *bool) *TriggerRuleUpdate {
	if v != nil {
		_u.SetMentionRequired(*v)
	}
	return _u
}

// SetInstructionTemplate sets the "instruction_template" field.
func (_u *TriggerRuleUpdate) SetInstructionTemplate(v string) *TriggerRuleUpdate {
	_u.mutation.SetInstructionTemplate(v)
	return _u
}

// SetNillableInstructionTemplate sets the "instruction_template" field if the given value is not nil.
func (_u *TriggerRuleUpdate) SetNillableInstructionTemplate(v *string) *TriggerRuleUpdate {
	if v != nil {
		_u.SetInstructionTemplate(*v)
	}
	return _u
}

// SetSkills sets the "skills" field.
func (_u *TriggerRuleUpdate) SetSkills(v []string) *TriggerRuleUpdate {
	_u.mutation.SetSkills(v)
	return _u
}

// AppendSkills appends value to the "skills" field.
func (_u *TriggerRuleUpdate) AppendSkills(v []string) *TriggerRuleUpdate {
	_u.mutation.AppendSkills(v)
	return _u
}

// SetAllowedTools sets the "allowed_tools" field.
func (_u *TriggerRuleUpdate) SetAllowedTools(v []string) *TriggerRuleUpdate {
	_u.mutation.SetAllowedTools(v)
	return _u
}

// AppendAllowedTools appends value to the "allowed_tools" field.
func (_u *TriggerRuleUpdate) AppendAllowedTools(v []string) *TriggerRuleUpdate {
	_u.mutation.AppendAllowedTools(v)
	return _u
}

// SetDangerousActions sets the "dangerous_actions" field.
func (_u *TriggerRuleUpdate) SetDangerousActions(v []string) *TriggerRuleUpdate {
	_u.mutation.SetDangerousActions(v)
	return _u
}

// AppendDangerousActions appends value to the "dangerous_actions" field.
func (_u *TriggerRuleUpdate) AppendDangerousActions(v []string) *TriggerRuleUpdate {
	_u.mutation.AppendDangerousActions(v)
	return _u
}

// SetFilters sets the "filters" field.
func (_u *TriggerRuleUpdate) SetFilters(v map[string]interface{}) *TriggerRuleUpdate {
	_u.mutation.SetFilters(v)
	return _u
}

// SetVersion sets the "version" field.
func (_u *TriggerRuleUpdate) SetVersion(v int64) *TriggerRuleUpdate {
	_u.mutation.ResetVersion()
	_u.mutation.SetVersion(v)
	return _u
}

// SetNillableVersion sets the "version" field if the given value is not nil.
func (_u *TriggerRuleUpdate) SetNillableVersion(v *int64) *TriggerRuleUpdate {
	if v != nil {
		_u.SetVersion(*v)
	}
	return _u
}

// AddVersion adds value to the "version" field.
func (_u *TriggerRuleUpdate) AddVersion(v int64) *TriggerRuleUpdate {
	_u.mutation.AddVersion(v)
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *TriggerRuleUpdate) SetCreatedAt(v time.Time) *TriggerRuleUpdate {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *TriggerRuleUpdate) SetNillableCreatedAt(v *time.Time) *TriggerRuleUpdate {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *TriggerRuleUpdate) SetUpdatedAt(v time.Time) *TriggerRuleUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the TriggerRuleMutation object of the builder.
func (_u *TriggerRuleUpdate) Mutation() *TriggerRuleMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *TriggerRuleUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *TriggerRuleUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *TriggerRuleUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *TriggerRuleUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *TriggerRuleUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := triggerrule.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

func (_u *TriggerRuleUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(triggerrule.Table, triggerrule.Columns, sqlgraph.NewFieldSpec(triggerrule.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.RepositoryID(); ok {
		_spec.SetField(triggerrule.FieldRepositoryID, field.TypeUUID, value)
	}
	if value, ok := _u.mutation.AgentProfileID(); ok {
		_spec.SetField(triggerrule.FieldAgentProfileID, field.TypeUUID, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(triggerrule.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.EventName(); ok {
		_spec.SetField(triggerrule.FieldEventName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Action(); ok {
		_spec.SetField(triggerrule.FieldAction, field.TypeString, value)
	}
	if _u.mutation.ActionCleared() {
		_spec.ClearField(triggerrule.FieldAction, field.TypeString)
	}
	if value, ok := _u.mutation.Enabled(); ok {
		_spec.SetField(triggerrule.FieldEnabled, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Priority(); ok {
		_spec.SetField(triggerrule.FieldPriority, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedPriority(); ok {
		_spec.AddField(triggerrule.FieldPriority, field.TypeInt, value)
	}
	if value, ok := _u.mutation.ActorMinPermission(); ok {
		_spec.SetField(triggerrule.FieldActorMinPermission, field.TypeString, value)
	}
	if value, ok := _u.mutation.MentionRequired(); ok {
		_spec.SetField(triggerrule.FieldMentionRequired, field.TypeBool, value)
	}
	if value, ok := _u.mutation.InstructionTemplate(); ok {
		_spec.SetField(triggerrule.FieldInstructionTemplate, field.TypeString, value)
	}
	if value, ok := _u.mutation.Skills(); ok {
		_spec.SetField(triggerrule.FieldSkills, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedSkills(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, triggerrule.FieldSkills, value)
		})
	}
	if value, ok := _u.mutation.AllowedTools(); ok {
		_spec.SetField(triggerrule.FieldAllowedTools, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedAllowedTools(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, triggerrule.FieldAllowedTools, value)
		})
	}
	if value, ok := _u.mutation.DangerousActions(); ok {
		_spec.SetField(triggerrule.FieldDangerousActions, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedDangerousActions(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, triggerrule.FieldDangerousActions, value)
		})
	}
	if value, ok := _u.mutation.Filters(); ok {
		_spec.SetField(triggerrule.FieldFilters, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.Version(); ok {
		_spec.SetField(triggerrule.FieldVersion, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedVersion(); ok {
		_spec.AddField(triggerrule.FieldVersion, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(triggerrule.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(triggerrule.FieldUpdatedAt, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{triggerrule.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// TriggerRuleUpdateOne is the builder for updating a single TriggerRule entity.
type TriggerRuleUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *TriggerRuleMutation
}

// SetRepositoryID sets the "repository_id" field.
func (_u *TriggerRuleUpdateOne) SetRepositoryID(v uuid.UUID) *TriggerRuleUpdateOne {
	_u.mutation.SetRepositoryID(v)
	return _u
}

// SetNillableRepositoryID sets the "repository_id" field if the given value is not nil.
func (_u *TriggerRuleUpdateOne) SetNillableRepositoryID(v *uuid.UUID) *TriggerRuleUpdateOne {
	if v != nil {
		_u.SetRepositoryID(*v)
	}
	return _u
}

// SetAgentProfileID sets the "agent_profile_id" field.
func (_u *TriggerRuleUpdateOne) SetAgentProfileID(v uuid.UUID) *TriggerRuleUpdateOne {
	_u.mutation.SetAgentProfileID(v)
	return _u
}

// SetNillableAgentProfileID sets the "agent_profile_id" field if the given value is not nil.
func (_u *TriggerRuleUpdateOne) SetNillableAgentProfileID(v *uuid.UUID) *TriggerRuleUpdateOne {
	if v != nil {
		_u.SetAgentProfileID(*v)
	}
	return _u
}

// SetName sets the "name" field.
func (_u *TriggerRuleUpdateOne) SetName(v string) *TriggerRuleUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *TriggerRuleUpdateOne) SetNillableName(v *string) *TriggerRuleUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetEventName sets the "event_name" field.
func (_u *TriggerRuleUpdateOne) SetEventName(v string) *TriggerRuleUpdateOne {
	_u.mutation.SetEventName(v)
	return _u
}

// SetNillableEventName sets the "event_name" field if the given value is not nil.
func (_u *TriggerRuleUpdateOne) SetNillableEventName(v *string) *TriggerRuleUpdateOne {
	if v != nil {
		_u.SetEventName(*v)
	}
	return _u
}

// SetAction sets the "action" field.
func (_u *TriggerRuleUpdateOne) SetAction(v string) *TriggerRuleUpdateOne {
	_u.mutation.SetAction(v)
	return _u
}

// SetNillableAction sets the "action" field if the given value is not nil.
func (_u *TriggerRuleUpdateOne) SetNillableAction(v *string) *TriggerRuleUpdateOne {
	if v != nil {
		_u.SetAction(*v)
	}
	return _u
}

// ClearAction clears the value of the "action" field.
func (_u *TriggerRuleUpdateOne) ClearAction() *TriggerRuleUpdateOne {
	_u.mutation.ClearAction()
	return _u
}

// SetEnabled sets the "enabled" field.
func (_u *TriggerRuleUpdateOne) SetEnabled(v bool) *TriggerRuleUpdateOne {
	_u.mutation.SetEnabled(v)
	return _u
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_u *TriggerRuleUpdateOne) SetNillableEnabled(v *bool) *TriggerRuleUpdateOne {
	if v != nil {
		_u.SetEnabled(*v)
	}
	return _u
}

// SetPriority sets the "priority" field.
func (_u *TriggerRuleUpdateOne) SetPriority(v int) *TriggerRuleUpdateOne {
	_u.mutation.ResetPriority()
	_u.mutation.SetPriority(v)
	return _u
}

// SetNillablePriority sets the "priority" field if the given value is not nil.
func (_u *TriggerRuleUpdateOne) SetNillablePriority(v *int) *TriggerRuleUpdateOne {
	if v != nil {
		_u.SetPriority(*v)
	}
	return _u
}

// AddPriority adds value to the "priority" field.
func (_u *TriggerRuleUpdateOne) AddPriority(v int) *TriggerRuleUpdateOne {
	_u.mutation.AddPriority(v)
	return _u
}

// SetActorMinPermission sets the "actor_min_permission" field.
func (_u *TriggerRuleUpdateOne) SetActorMinPermission(v string) *TriggerRuleUpdateOne {
	_u.mutation.SetActorMinPermission(v)
	return _u
}

// SetNillableActorMinPermission sets the "actor_min_permission" field if the given value is not nil.
func (_u *TriggerRuleUpdateOne) SetNillableActorMinPermission(v *string) *TriggerRuleUpdateOne {
	if v != nil {
		_u.SetActorMinPermission(*v)
	}
	return _u
}

// SetMentionRequired sets the "mention_required" field.
func (_u *TriggerRuleUpdateOne) SetMentionRequired(v bool) *TriggerRuleUpdateOne {
	_u.mutation.SetMentionRequired(v)
	return _u
}

// SetNillableMentionRequired sets the "mention_required" field if the given value is not nil.
func (_u *TriggerRuleUpdateOne) SetNillableMentionRequired(v *bool) *TriggerRuleUpdateOne {
	if v != nil {
		_u.SetMentionRequired(*v)
	}
	return _u
}

// SetInstructionTemplate sets the "instruction_template" field.
func (_u *TriggerRuleUpdateOne) SetInstructionTemplate(v string) *TriggerRuleUpdateOne {
	_u.mutation.SetInstructionTemplate(v)
	return _u
}

// SetNillableInstructionTemplate sets the "instruction_template" field if the given value is not nil.
func (_u *TriggerRuleUpdateOne) SetNillableInstructionTemplate(v *string) *TriggerRuleUpdateOne {
	if v != nil {
		_u.SetInstructionTemplate(*v)
	}
	return _u
}

// SetSkills sets the "skills" field.
func (_u *TriggerRuleUpdateOne) SetSkills(v []string) *TriggerRuleUpdateOne {
	_u.mutation.SetSkills(v)
	return _u
}

// AppendSkills appends value to the "skills" field.
func (_u *TriggerRuleUpdateOne) AppendSkills(v []string) *TriggerRuleUpdateOne {
	_u.mutation.AppendSkills(v)
	return _u
}

// SetAllowedTools sets the "allowed_tools" field.
func (_u *TriggerRuleUpdateOne) SetAllowedTools(v []string) *TriggerRuleUpdateOne {
	_u.mutation.SetAllowedTools(v)
	return _u
}

// AppendAllowedTools appends value to the "allowed_tools" field.
func (_u *TriggerRuleUpdateOne) AppendAllowedTools(v []string) *TriggerRuleUpdateOne {
	_u.mutation.AppendAllowedTools(v)
	return _u
}

// SetDangerousActions sets the "dangerous_actions" field.
func (_u *TriggerRuleUpdateOne) SetDangerousActions(v []string) *TriggerRuleUpdateOne {
	_u.mutation.SetDangerousActions(v)
	return _u
}

// AppendDangerousActions appends value to the "dangerous_actions" field.
func (_u *TriggerRuleUpdateOne) AppendDangerousActions(v []string) *TriggerRuleUpdateOne {
	_u.mutation.AppendDangerousActions(v)
	return _u
}

// SetFilters sets the "filters" field.
func (_u *TriggerRuleUpdateOne) SetFilters(v map[string]interface{}) *TriggerRuleUpdateOne {
	_u.mutation.SetFilters(v)
	return _u
}

// SetVersion sets the "version" field.
func (_u *TriggerRuleUpdateOne) SetVersion(v int64) *TriggerRuleUpdateOne {
	_u.mutation.ResetVersion()
	_u.mutation.SetVersion(v)
	return _u
}

// SetNillableVersion sets the "version" field if the given value is not nil.
func (_u *TriggerRuleUpdateOne) SetNillableVersion(v *int64) *TriggerRuleUpdateOne {
	if v != nil {
		_u.SetVersion(*v)
	}
	return _u
}

// AddVersion adds value to the "version" field.
func (_u *TriggerRuleUpdateOne) AddVersion(v int64) *TriggerRuleUpdateOne {
	_u.mutation.AddVersion(v)
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *TriggerRuleUpdateOne) SetCreatedAt(v time.Time) *TriggerRuleUpdateOne {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *TriggerRuleUpdateOne) SetNillableCreatedAt(v *time.Time) *TriggerRuleUpdateOne {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *TriggerRuleUpdateOne) SetUpdatedAt(v time.Time) *TriggerRuleUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the TriggerRuleMutation object of the builder.
func (_u *TriggerRuleUpdateOne) Mutation() *TriggerRuleMutation {
	return _u.mutation
}

// Where appends a list predicates to the TriggerRuleUpdate builder.
func (_u *TriggerRuleUpdateOne) Where(ps ...predicate.TriggerRule) *TriggerRuleUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *TriggerRuleUpdateOne) Select(field string, fields ...string) *TriggerRuleUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated TriggerRule entity.
func (_u *TriggerRuleUpdateOne) Save(ctx context.Context) (*TriggerRule, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *TriggerRuleUpdateOne) SaveX(ctx context.Context) *TriggerRule {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *TriggerRuleUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *TriggerRuleUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *TriggerRuleUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := triggerrule.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

func (_u *TriggerRuleUpdateOne) sqlSave(ctx context.Context) (_node *TriggerRule, err error) {
	_spec := sqlgraph.NewUpdateSpec(triggerrule.Table, triggerrule.Columns, sqlgraph.NewFieldSpec(triggerrule.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "TriggerRule.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, triggerrule.FieldID)
		for _, f := range fields {
			if !triggerrule.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != triggerrule.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.RepositoryID(); ok {
		_spec.SetField(triggerrule.FieldRepositoryID, field.TypeUUID, value)
	}
	if value, ok := _u.mutation.AgentProfileID(); ok {
		_spec.SetField(triggerrule.FieldAgentProfileID, field.TypeUUID, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(triggerrule.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.EventName(); ok {
		_spec.SetField(triggerrule.FieldEventName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Action(); ok {
		_spec.SetField(triggerrule.FieldAction, field.TypeString, value)
	}
	if _u.mutation.ActionCleared() {
		_spec.ClearField(triggerrule.FieldAction, field.TypeString)
	}
	if value, ok := _u.mutation.Enabled(); ok {
		_spec.SetField(triggerrule.FieldEnabled, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Priority(); ok {
		_spec.SetField(triggerrule.FieldPriority, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedPriority(); ok {
		_spec.AddField(triggerrule.FieldPriority, field.TypeInt, value)
	}
	if value, ok := _u.mutation.ActorMinPermission(); ok {
		_spec.SetField(triggerrule.FieldActorMinPermission, field.TypeString, value)
	}
	if value, ok := _u.mutation.MentionRequired(); ok {
		_spec.SetField(triggerrule.FieldMentionRequired, field.TypeBool, value)
	}
	if value, ok := _u.mutation.InstructionTemplate(); ok {
		_spec.SetField(triggerrule.FieldInstructionTemplate, field.TypeString, value)
	}
	if value, ok := _u.mutation.Skills(); ok {
		_spec.SetField(triggerrule.FieldSkills, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedSkills(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, triggerrule.FieldSkills, value)
		})
	}
	if value, ok := _u.mutation.AllowedTools(); ok {
		_spec.SetField(triggerrule.FieldAllowedTools, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedAllowedTools(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, triggerrule.FieldAllowedTools, value)
		})
	}
	if value, ok := _u.mutation.DangerousActions(); ok {
		_spec.SetField(triggerrule.FieldDangerousActions, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedDangerousActions(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, triggerrule.FieldDangerousActions, value)
		})
	}
	if value, ok := _u.mutation.Filters(); ok {
		_spec.SetField(triggerrule.FieldFilters, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.Version(); ok {
		_spec.SetField(triggerrule.FieldVersion, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedVersion(); ok {
		_spec.AddField(triggerrule.FieldVersion, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(triggerrule.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(triggerrule.FieldUpdatedAt, field.TypeTime, value)
	}
	_node = &TriggerRule{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{triggerrule.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
