// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/slovx2/tyrs-hand/ent/workernode"
)

// WorkerNodeCreate is the builder for creating a WorkerNode entity.
type WorkerNodeCreate struct {
	config
	mutation *WorkerNodeMutation
	hooks    []Hook
}

// SetVersion sets the "version" field.
func (_c *WorkerNodeCreate) SetVersion(v string) *WorkerNodeCreate {
	_c.mutation.SetVersion(v)
	return _c
}

// SetStatus sets the "status" field.
func (_c *WorkerNodeCreate) SetStatus(v string) *WorkerNodeCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *WorkerNodeCreate) SetNillableStatus(v *string) *WorkerNodeCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetExecutionNodeID sets the "execution_node_id" field.
func (_c *WorkerNodeCreate) SetExecutionNodeID(v uuid.UUID) *WorkerNodeCreate {
	_c.mutation.SetExecutionNodeID(v)
	return _c
}

// SetNillableExecutionNodeID sets the "execution_node_id" field if the given value is not nil.
func (_c *WorkerNodeCreate) SetNillableExecutionNodeID(v *uuid.UUID) *WorkerNodeCreate {
	if v != nil {
		_c.SetExecutionNodeID(*v)
	}
	return _c
}

// SetMetadata sets the "metadata" field.
func (_c *WorkerNodeCreate) SetMetadata(v map[string]interface{}) *WorkerNodeCreate {
	_c.mutation.SetMetadata(v)
	return _c
}

// SetHeartbeatAt sets the "heartbeat_at" field.
func (_c *WorkerNodeCreate) SetHeartbeatAt(v time.Time) *WorkerNodeCreate {
	_c.mutation.SetHeartbeatAt(v)
	return _c
}

// SetNillableHeartbeatAt sets the "heartbeat_at" field if the given value is not nil.
func (_c *WorkerNodeCreate) SetNillableHeartbeatAt(v *time.Time) *WorkerNodeCreate {
	if v != nil {
		_c.SetHeartbeatAt(*v)
	}
	return _c
}

// SetStartedAt sets the "started_at" field.
func (_c *WorkerNodeCreate) SetStartedAt(v time.Time) *WorkerNodeCreate {
	_c.mutation.SetStartedAt(v)
	return _c
}

// SetNillableStartedAt sets the "started_at" field if the given value is not nil.
func (_c *WorkerNodeCreate) SetNillableStartedAt(v *time.Time) *WorkerNodeCreate {
	if v != nil {
		_c.SetStartedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *WorkerNodeCreate) SetID(v string) *WorkerNodeCreate {
	_c.mutation.SetID(v)
	return _c
}

// Mutation returns the WorkerNodeMutation object of the builder.
func (_c *WorkerNodeCreate) Mutation() *WorkerNodeMutation {
	return _c.mutation
}

// Save creates the WorkerNode in the database.
func (_c *WorkerNodeCreate) Save(ctx context.Context) (*WorkerNode, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *WorkerNodeCreate) SaveX(ctx context.Context) *WorkerNode {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *WorkerNodeCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *WorkerNodeCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *WorkerNodeCreate) defaults() {
	if _, ok := _c.mutation.Status(); !ok {
		v := workernode.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.Metadata(); !ok {
		v := workernode.DefaultMetadata
		_c.mutation.SetMetadata(v)
	}
	if _, ok := _c.mutation.HeartbeatAt(); !ok {
		v := workernode.DefaultHeartbeatAt()
		_c.mutation.SetHeartbeatAt(v)
	}
	if _, ok := _c.mutation.StartedAt(); !ok {
		v := workernode.DefaultStartedAt()
		_c.mutation.SetStartedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *WorkerNodeCreate) check() error {
	if _, ok := _c.mutation.Version(); !ok {
		return &ValidationError{Name: "version", err: errors.New(`ent: missing required field "WorkerNode.version"`)}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "WorkerNode.status"`)}
	}
	if _, ok := _c.mutation.Metadata(); !ok {
		return &ValidationError{Name: "metadata", err: errors.New(`ent: missing required field "WorkerNode.metadata"`)}
	}
	if _, ok := _c.mutation.HeartbeatAt(); !ok {
		return &ValidationError{Name: "heartbeat_at", err: errors.New(`ent: missing required field "WorkerNode.heartbeat_at"`)}
	}
	if _, ok := _c.mutation.StartedAt(); !ok {
		return &ValidationError{Name: "started_at", err: errors.New(`ent: missing required field "WorkerNode.started_at"`)}
	}
	return nil
}

func (_c *WorkerNodeCreate) sqlSave(ctx context.Context) (*WorkerNode, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected WorkerNode.ID type: %T", _spec.ID.Value)
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *WorkerNodeCreate) createSpec() (*WorkerNode, *sqlgraph.CreateSpec) {
	var (
		_node = &WorkerNode{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(workernode.Table, sqlgraph.NewFieldSpec(workernode.FieldID, field.TypeString))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.Version(); ok {
		_spec.SetField(workernode.FieldVersion, field.TypeString, value)
		_node.Version = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(workernode.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.ExecutionNodeID(); ok {
		_spec.SetField(workernode.FieldExecutionNodeID, field.TypeUUID, value)
		_node.ExecutionNodeID = &value
	}
	if value, ok := _c.mutation.Metadata(); ok {
		_spec.SetField(workernode.FieldMetadata, field.TypeJSON, value)
		_node.Metadata = value
	}
	if value, ok := _c.mutation.HeartbeatAt(); ok {
		_spec.SetField(workernode.FieldHeartbeatAt, field.TypeTime, value)
		_node.HeartbeatAt = value
	}
	if value, ok := _c.mutation.StartedAt(); ok {
		_spec.SetField(workernode.FieldStartedAt, field.TypeTime, value)
		_node.StartedAt = value
	}
	return _node, _spec
}

// WorkerNodeCreateBulk is the builder for creating many WorkerNode entities in bulk.
type WorkerNodeCreateBulk struct {
	config
	err      error
	builders []*WorkerNodeCreate
}

// Save creates the WorkerNode entities in the database.
func (_c *WorkerNodeCreateBulk) Save(ctx context.Context) ([]*WorkerNode, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*WorkerNode, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*WorkerNodeMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *WorkerNodeCreateBulk) SaveX(ctx context.Context) []*WorkerNode {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *WorkerNodeCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *WorkerNodeCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
