// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/slovx2/tyrs-hand/ent/predicate"
	"github.com/slovx2/tyrs-hand/ent/workernode"
)

// WorkerNodeUpdate is the builder for updating WorkerNode entities.
type WorkerNodeUpdate struct {
	config
	hooks    []Hook
	mutation *WorkerNodeMutation
}

// Where appends a list predicates to the WorkerNodeUpdate builder.
func (_u *WorkerNodeUpdate) Where(ps ...predicate.WorkerNode) *WorkerNodeUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetVersion sets the "version" field.
func (_u *WorkerNodeUpdate) SetVersion(v string) *WorkerNodeUpdate {
	_u.mutation.SetVersion(v)
	return _u
}

// SetNillableVersion sets the "version" field if the given value is not nil.
func (_u *WorkerNodeUpdate) SetNillableVersion(v *string) *WorkerNodeUpdate {
	if v != nil {
		_u.SetVersion(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *WorkerNodeUpdate) SetStatus(v string) *WorkerNodeUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *WorkerNodeUpdate) SetNillableStatus(v *string) *WorkerNodeUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetExecutionNodeID sets the "execution_node_id" field.
func (_u *WorkerNodeUpdate) SetExecutionNodeID(v uuid.UUID) *WorkerNodeUpdate {
	_u.mutation.SetExecutionNodeID(v)
	return _u
}

// SetNillableExecutionNodeID sets the "execution_node_id" field if the given value is not nil.
func (_u *WorkerNodeUpdate) SetNillableExecutionNodeID(v *uuid.UUID) *WorkerNodeUpdate {
	if v != nil {
		_u.SetExecutionNodeID(*v)
	}
	return _u
}

// ClearExecutionNodeID clears the value of the "execution_node_id" field.
func (_u *WorkerNodeUpdate) ClearExecutionNodeID() *WorkerNodeUpdate {
	_u.mutation.ClearExecutionNodeID()
	return _u
}

// SetMetadata sets the "metadata" field.
func (_u *WorkerNodeUpdate) SetMetadata(v map[string]interface{}) *WorkerNodeUpdate {
	_u.mutation.SetMetadata(v)
	return _u
}

// SetHeartbeatAt sets the "heartbeat_at" field.
func (_u *WorkerNodeUpdate) SetHeartbeatAt(v time.Time) *WorkerNodeUpdate {
	_u.mutation.SetHeartbeatAt(v)
	return _u
}

// SetNillableHeartbeatAt sets the "heartbeat_at" field if the given value is not nil.
func (_u *WorkerNodeUpdate) SetNillableHeartbeatAt(v *time.Time) *WorkerNodeUpdate {
	if v != nil {
		_u.SetHeartbeatAt(*v)
	}
	return _u
}

// SetStartedAt sets the "started_at" field.
func (_u *WorkerNodeUpdate) SetStartedAt(v time.Time) *WorkerNodeUpdate {
	_u.mutation.SetStartedAt(v)
	return _u
}

// SetNillableStartedAt sets the "started_at" field if the given value is not nil.
func (_u *WorkerNodeUpdate) SetNillableStartedAt(v *time.Time) *WorkerNodeUpdate {
	if v != nil {
		_u.SetStartedAt(*v)
	}
	return _u
}

// Mutation returns the WorkerNodeMutation object of the builder.
func (_u *WorkerNodeUpdate) Mutation() *WorkerNodeMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *WorkerNodeUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *WorkerNodeUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *WorkerNodeUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *WorkerNodeUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *WorkerNodeUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(workernode.Table, workernode.Columns, sqlgraph.NewFieldSpec(workernode.FieldID, field.TypeString))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Version(); ok {
		_spec.SetField(workernode.FieldVersion, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(workernode.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.ExecutionNodeID(); ok {
		_spec.SetField(workernode.FieldExecutionNodeID, field.TypeUUID, value)
	}
	if _u.mutation.ExecutionNodeIDCleared() {
		_spec.ClearField(workernode.FieldExecutionNodeID, field.TypeUUID)
	}
	if value, ok := _u.mutation.Metadata(); ok {
		_spec.SetField(workernode.FieldMetadata, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.HeartbeatAt(); ok {
		_spec.SetField(workernode.FieldHeartbeatAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.StartedAt(); ok {
		_spec.SetField(workernode.FieldStartedAt, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{workernode.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// WorkerNodeUpdateOne is the builder for updating a single WorkerNode entity.
type WorkerNodeUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *WorkerNodeMutation
}

// SetVersion sets the "version" field.
func (_u *WorkerNodeUpdateOne) SetVersion(v string) *WorkerNodeUpdateOne {
	_u.mutation.SetVersion(v)
	return _u
}

// SetNillableVersion sets the "version" field if the given value is not nil.
func (_u *WorkerNodeUpdateOne) SetNillableVersion(v *string) *WorkerNodeUpdateOne {
	if v != nil {
		_u.SetVersion(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *WorkerNodeUpdateOne) SetStatus(v string) *WorkerNodeUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *WorkerNodeUpdateOne) SetNillableStatus(v *string) *WorkerNodeUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetExecutionNodeID sets the "execution_node_id" field.
func (_u *WorkerNodeUpdateOne) SetExecutionNodeID(v uuid.UUID) *WorkerNodeUpdateOne {
	_u.mutation.SetExecutionNodeID(v)
	return _u
}

// SetNillableExecutionNodeID sets the "execution_node_id" field if the given value is not nil.
func (_u *WorkerNodeUpdateOne) SetNillableExecutionNodeID(v *uuid.UUID) *WorkerNodeUpdateOne {
	if v != nil {
		_u.SetExecutionNodeID(*v)
	}
	return _u
}

// ClearExecutionNodeID clears the value of the "execution_node_id" field.
func (_u *WorkerNodeUpdateOne) ClearExecutionNodeID() *WorkerNodeUpdateOne {
	_u.mutation.ClearExecutionNodeID()
	return _u
}

// SetMetadata sets the "metadata" field.
func (_u *WorkerNodeUpdateOne) SetMetadata(v map[string]interface{}) *WorkerNodeUpdateOne {
	_u.mutation.SetMetadata(v)
	return _u
}

// SetHeartbeatAt sets the "heartbeat_at" field.
func (_u *WorkerNodeUpdateOne) SetHeartbeatAt(v time.Time) *WorkerNodeUpdateOne {
	_u.mutation.SetHeartbeatAt(v)
	return _u
}

// SetNillableHeartbeatAt sets the "heartbeat_at" field if the given value is not nil.
func (_u *WorkerNodeUpdateOne) SetNillableHeartbeatAt(v *time.Time) *WorkerNodeUpdateOne {
	if v != nil {
		_u.SetHeartbeatAt(*v)
	}
	return _u
}

// SetStartedAt sets the "started_at" field.
func (_u *WorkerNodeUpdateOne) SetStartedAt(v time.Time) *WorkerNodeUpdateOne {
	_u.mutation.SetStartedAt(v)
	return _u
}

// SetNillableStartedAt sets the "started_at" field if the given value is not nil.
func (_u *WorkerNodeUpdateOne) SetNillableStartedAt(v *time.Time) *WorkerNodeUpdateOne {
	if v != nil {
		_u.SetStartedAt(*v)
	}
	return _u
}

// Mutation returns the WorkerNodeMutation object of the builder.
func (_u *WorkerNodeUpdateOne) Mutation() *WorkerNodeMutation {
	return _u.mutation
}

// Where appends a list predicates to the WorkerNodeUpdate builder.
func (_u *WorkerNodeUpdateOne) Where(ps ...predicate.WorkerNode) *WorkerNodeUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *WorkerNodeUpdateOne) Select(field string, fields ...string) *WorkerNodeUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated WorkerNode entity.
func (_u *WorkerNodeUpdateOne) Save(ctx context.Context) (*WorkerNode, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *WorkerNodeUpdateOne) SaveX(ctx context.Context) *WorkerNode {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *WorkerNodeUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *WorkerNodeUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *WorkerNodeUpdateOne) sqlSave(ctx context.Context) (_node *WorkerNode, err error) {
	_spec := sqlgraph.NewUpdateSpec(workernode.Table, workernode.Columns, sqlgraph.NewFieldSpec(workernode.FieldID, field.TypeString))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "WorkerNode.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, workernode.FieldID)
		for _, f := range fields {
			if !workernode.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != workernode.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Version(); ok {
		_spec.SetField(workernode.FieldVersion, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(workernode.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.ExecutionNodeID(); ok {
		_spec.SetField(workernode.FieldExecutionNodeID, field.TypeUUID, value)
	}
	if _u.mutation.ExecutionNodeIDCleared() {
		_spec.ClearField(workernode.FieldExecutionNodeID, field.TypeUUID)
	}
	if value, ok := _u.mutation.Metadata(); ok {
		_spec.SetField(workernode.FieldMetadata, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.HeartbeatAt(); ok {
		_spec.SetField(workernode.FieldHeartbeatAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.StartedAt(); ok {
		_spec.SetField(workernode.FieldStartedAt, field.TypeTime, value)
	}
	_node = &WorkerNode{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{workernode.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
