// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/slovx2/tyrs-hand/ent/predicate"
	"github.com/slovx2/tyrs-hand/ent/workerenrollment"
)

// WorkerEnrollmentUpdate is the builder for updating WorkerEnrollment entities.
type WorkerEnrollmentUpdate struct {
	config
	hooks    []Hook
	mutation *WorkerEnrollmentMutation
}

// Where appends a list predicates to the WorkerEnrollmentUpdate builder.
func (_u *WorkerEnrollmentUpdate) Where(ps ...predicate.WorkerEnrollment) *WorkerEnrollmentUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetWorkerID sets the "worker_id" field.
func (_u *WorkerEnrollmentUpdate) SetWorkerID(v uuid.UUID) *WorkerEnrollmentUpdate {
	_u.mutation.SetWorkerID(v)
	return _u
}

// SetNillableWorkerID sets the "worker_id" field if the given value is not nil.
func (_u *WorkerEnrollmentUpdate) SetNillableWorkerID(v *uuid.UUID) *WorkerEnrollmentUpdate {
	if v != nil {
		_u.SetWorkerID(*v)
	}
	return _u
}

// SetTokenHash sets the "token_hash" field.
func (_u *WorkerEnrollmentUpdate) SetTokenHash(v string) *WorkerEnrollmentUpdate {
	_u.mutation.SetTokenHash(v)
	return _u
}

// SetNillableTokenHash sets the "token_hash" field if the given value is not nil.
func (_u *WorkerEnrollmentUpdate) SetNillableTokenHash(v *string) *WorkerEnrollmentUpdate {
	if v != nil {
		_u.SetTokenHash(*v)
	}
	return _u
}

// SetExpiresAt sets the "expires_at" field.
func (_u *WorkerEnrollmentUpdate) SetExpiresAt(v time.Time) *WorkerEnrollmentUpdate {
	_u.mutation.SetExpiresAt(v)
	return _u
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_u *WorkerEnrollmentUpdate) SetNillableExpiresAt(v *time.Time) *WorkerEnrollmentUpdate {
	if v != nil {
		_u.SetExpiresAt(*v)
	}
	return _u
}

// SetConsumedAt sets the "consumed_at" field.
func (_u *WorkerEnrollmentUpdate) SetConsumedAt(v time.Time) *WorkerEnrollmentUpdate {
	_u.mutation.SetConsumedAt(v)
	return _u
}

// SetNillableConsumedAt sets the "consumed_at" field if the given value is not nil.
func (_u *WorkerEnrollmentUpdate) SetNillableConsumedAt(v *time.Time) *WorkerEnrollmentUpdate {
	if v != nil {
		_u.SetConsumedAt(*v)
	}
	return _u
}

// ClearConsumedAt clears the value of the "consumed_at" field.
func (_u *WorkerEnrollmentUpdate) ClearConsumedAt() *WorkerEnrollmentUpdate {
	_u.mutation.ClearConsumedAt()
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *WorkerEnrollmentUpdate) SetCreatedAt(v time.Time) *WorkerEnrollmentUpdate {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *WorkerEnrollmentUpdate) SetNillableCreatedAt(v *time.Time) *WorkerEnrollmentUpdate {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// Mutation returns the WorkerEnrollmentMutation object of the builder.
func (_u *WorkerEnrollmentUpdate) Mutation() *WorkerEnrollmentMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *WorkerEnrollmentUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *WorkerEnrollmentUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *WorkerEnrollmentUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *WorkerEnrollmentUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *WorkerEnrollmentUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(workerenrollment.Table, workerenrollment.Columns, sqlgraph.NewFieldSpec(workerenrollment.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.WorkerID(); ok {
		_spec.SetField(workerenrollment.FieldWorkerID, field.TypeUUID, value)
	}
	if value, ok := _u.mutation.TokenHash(); ok {
		_spec.SetField(workerenrollment.FieldTokenHash, field.TypeString, value)
	}
	if value, ok := _u.mutation.ExpiresAt(); ok {
		_spec.SetField(workerenrollment.FieldExpiresAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.ConsumedAt(); ok {
		_spec.SetField(workerenrollment.FieldConsumedAt, field.TypeTime, value)
	}
	if _u.mutation.ConsumedAtCleared() {
		_spec.ClearField(workerenrollment.FieldConsumedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(workerenrollment.FieldCreatedAt, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{workerenrollment.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// WorkerEnrollmentUpdateOne is the builder for updating a single WorkerEnrollment entity.
type WorkerEnrollmentUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *WorkerEnrollmentMutation
}

// SetWorkerID sets the "worker_id" field.
func (_u *WorkerEnrollmentUpdateOne) SetWorkerID(v uuid.UUID) *WorkerEnrollmentUpdateOne {
	_u.mutation.SetWorkerID(v)
	return _u
}

// SetNillableWorkerID sets the "worker_id" field if the given value is not nil.
func (_u *WorkerEnrollmentUpdateOne) SetNillableWorkerID(v *uuid.UUID) *WorkerEnrollmentUpdateOne {
	if v != nil {
		_u.SetWorkerID(*v)
	}
	return _u
}

// SetTokenHash sets the "token_hash" field.
func (_u *WorkerEnrollmentUpdateOne) SetTokenHash(v string) *WorkerEnrollmentUpdateOne {
	_u.mutation.SetTokenHash(v)
	return _u
}

// SetNillableTokenHash sets the "token_hash" field if the given value is not nil.
func (_u *WorkerEnrollmentUpdateOne) SetNillableTokenHash(v *string) *WorkerEnrollmentUpdateOne {
	if v != nil {
		_u.SetTokenHash(*v)
	}
	return _u
}

// SetExpiresAt sets the "expires_at" field.
func (_u *WorkerEnrollmentUpdateOne) SetExpiresAt(v time.Time) *WorkerEnrollmentUpdateOne {
	_u.mutation.SetExpiresAt(v)
	return _u
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_u *WorkerEnrollmentUpdateOne) SetNillableExpiresAt(v *time.Time) *WorkerEnrollmentUpdateOne {
	if v != nil {
		_u.SetExpiresAt(*v)
	}
	return _u
}

// SetConsumedAt sets the "consumed_at" field.
func (_u *WorkerEnrollmentUpdateOne) SetConsumedAt(v time.Time) *WorkerEnrollmentUpdateOne {
	_u.mutation.SetConsumedAt(v)
	return _u
}

// SetNillableConsumedAt sets the "consumed_at" field if the given value is not nil.
func (_u *WorkerEnrollmentUpdateOne) SetNillableConsumedAt(v *time.Time) *WorkerEnrollmentUpdateOne {
	if v != nil {
		_u.SetConsumedAt(*v)
	}
	return _u
}

// ClearConsumedAt clears the value of the "consumed_at" field.
func (_u *WorkerEnrollmentUpdateOne) ClearConsumedAt() *WorkerEnrollmentUpdateOne {
	_u.mutation.ClearConsumedAt()
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *WorkerEnrollmentUpdateOne) SetCreatedAt(v time.Time) *WorkerEnrollmentUpdateOne {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *WorkerEnrollmentUpdateOne) SetNillableCreatedAt(v *time.Time) *WorkerEnrollmentUpdateOne {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// Mutation returns the WorkerEnrollmentMutation object of the builder.
func (_u *WorkerEnrollmentUpdateOne) Mutation() *WorkerEnrollmentMutation {
	return _u.mutation
}

// Where appends a list predicates to the WorkerEnrollmentUpdate builder.
func (_u *WorkerEnrollmentUpdateOne) Where(ps ...predicate.WorkerEnrollment) *WorkerEnrollmentUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *WorkerEnrollmentUpdateOne) Select(field string, fields ...string) *WorkerEnrollmentUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated WorkerEnrollment entity.
func (_u *WorkerEnrollmentUpdateOne) Save(ctx context.Context) (*WorkerEnrollment, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *WorkerEnrollmentUpdateOne) SaveX(ctx context.Context) *WorkerEnrollment {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *WorkerEnrollmentUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *WorkerEnrollmentUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *WorkerEnrollmentUpdateOne) sqlSave(ctx context.Context) (_node *WorkerEnrollment, err error) {
	_spec := sqlgraph.NewUpdateSpec(workerenrollment.Table, workerenrollment.Columns, sqlgraph.NewFieldSpec(workerenrollment.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "WorkerEnrollment.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, workerenrollment.FieldID)
		for _, f := range fields {
			if !workerenrollment.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != workerenrollment.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.WorkerID(); ok {
		_spec.SetField(workerenrollment.FieldWorkerID, field.TypeUUID, value)
	}
	if value, ok := _u.mutation.TokenHash(); ok {
		_spec.SetField(workerenrollment.FieldTokenHash, field.TypeString, value)
	}
	if value, ok := _u.mutation.ExpiresAt(); ok {
		_spec.SetField(workerenrollment.FieldExpiresAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.ConsumedAt(); ok {
		_spec.SetField(workerenrollment.FieldConsumedAt, field.TypeTime, value)
	}
	if _u.mutation.ConsumedAtCleared() {
		_spec.ClearField(workerenrollment.FieldConsumedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(workerenrollment.FieldCreatedAt, field.TypeTime, value)
	}
	_node = &WorkerEnrollment{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{workerenrollment.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
