// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/dialect/sql/sqljson"
	"entgo.io/ent/schema/field"
	"github.com/slovx2/tyrs-hand/ent/predicate"
	"github.com/slovx2/tyrs-hand/ent/worker"
)

// WorkerUpdate is the builder for updating Worker entities.
type WorkerUpdate struct {
	config
	hooks    []Hook
	mutation *WorkerMutation
}

// Where appends a list predicates to the WorkerUpdate builder.
func (_u *WorkerUpdate) Where(ps ...predicate.Worker) *WorkerUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetName sets the "name" field.
func (_u *WorkerUpdate) SetName(v string) *WorkerUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *WorkerUpdate) SetNillableName(v *string) *WorkerUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetRoles sets the "roles" field.
func (_u *WorkerUpdate) SetRoles(v []string) *WorkerUpdate {
	_u.mutation.SetRoles(v)
	return _u
}

// AppendRoles appends value to the "roles" field.
func (_u *WorkerUpdate) AppendRoles(v []string) *WorkerUpdate {
	_u.mutation.AppendRoles(v)
	return _u
}

// SetEnabled sets the "enabled" field.
func (_u *WorkerUpdate) SetEnabled(v bool) *WorkerUpdate {
	_u.mutation.SetEnabled(v)
	return _u
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_u *WorkerUpdate) SetNillableEnabled(v *bool) *WorkerUpdate {
	if v != nil {
		_u.SetEnabled(*v)
	}
	return _u
}

// SetMaxConcurrentJobs sets the "max_concurrent_jobs" field.
func (_u *WorkerUpdate) SetMaxConcurrentJobs(v int) *WorkerUpdate {
	_u.mutation.ResetMaxConcurrentJobs()
	_u.mutation.SetMaxConcurrentJobs(v)
	return _u
}

// SetNillableMaxConcurrentJobs sets the "max_concurrent_jobs" field if the given value is not nil.
func (_u *WorkerUpdate) SetNillableMaxConcurrentJobs(v *int) *WorkerUpdate {
	if v != nil {
		_u.SetMaxConcurrentJobs(*v)
	}
	return _u
}

// AddMaxConcurrentJobs adds value to the "max_concurrent_jobs" field.
func (_u *WorkerUpdate) AddMaxConcurrentJobs(v int) *WorkerUpdate {
	_u.mutation.AddMaxConcurrentJobs(v)
	return _u
}

// SetCredentialHash sets the "credential_hash" field.
func (_u *WorkerUpdate) SetCredentialHash(v string) *WorkerUpdate {
	_u.mutation.SetCredentialHash(v)
	return _u
}

// SetNillableCredentialHash sets the "credential_hash" field if the given value is not nil.
func (_u *WorkerUpdate) SetNillableCredentialHash(v *string) *WorkerUpdate {
	if v != nil {
		_u.SetCredentialHash(*v)
	}
	return _u
}

// ClearCredentialHash clears the value of the "credential_hash" field.
func (_u *WorkerUpdate) ClearCredentialHash() *WorkerUpdate {
	_u.mutation.ClearCredentialHash()
	return _u
}

// SetCredentialVersion sets the "credential_version" field.
func (_u *WorkerUpdate) SetCredentialVersion(v int64) *WorkerUpdate {
	_u.mutation.ResetCredentialVersion()
	_u.mutation.SetCredentialVersion(v)
	return _u
}

// SetNillableCredentialVersion sets the "credential_version" field if the given value is not nil.
func (_u *WorkerUpdate) SetNillableCredentialVersion(v *int64) *WorkerUpdate {
	if v != nil {
		_u.SetCredentialVersion(*v)
	}
	return _u
}

// AddCredentialVersion adds value to the "credential_version" field.
func (_u *WorkerUpdate) AddCredentialVersion(v int64) *WorkerUpdate {
	_u.mutation.AddCredentialVersion(v)
	return _u
}

// SetProtocolVersion sets the "protocol_version" field.
func (_u *WorkerUpdate) SetProtocolVersion(v int) *WorkerUpdate {
	_u.mutation.ResetProtocolVersion()
	_u.mutation.SetProtocolVersion(v)
	return _u
}

// SetNillableProtocolVersion sets the "protocol_version" field if the given value is not nil.
func (_u *WorkerUpdate) SetNillableProtocolVersion(v *int) *WorkerUpdate {
	if v != nil {
		_u.SetProtocolVersion(*v)
	}
	return _u
}

// AddProtocolVersion adds value to the "protocol_version" field.
func (_u *WorkerUpdate) AddProtocolVersion(v int) *WorkerUpdate {
	_u.mutation.AddProtocolVersion(v)
	return _u
}

// SetWorkerVersion sets the "worker_version" field.
func (_u *WorkerUpdate) SetWorkerVersion(v string) *WorkerUpdate {
	_u.mutation.SetWorkerVersion(v)
	return _u
}

// SetNillableWorkerVersion sets the "worker_version" field if the given value is not nil.
func (_u *WorkerUpdate) SetNillableWorkerVersion(v *string) *WorkerUpdate {
	if v != nil {
		_u.SetWorkerVersion(*v)
	}
	return _u
}

// ClearWorkerVersion clears the value of the "worker_version" field.
func (_u *WorkerUpdate) ClearWorkerVersion() *WorkerUpdate {
	_u.mutation.ClearWorkerVersion()
	return _u
}

// SetStatus sets the "status" field.
func (_u *WorkerUpdate) SetStatus(v string) *WorkerUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *WorkerUpdate) SetNillableStatus(v *string) *WorkerUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetHeartbeatAt sets the "heartbeat_at" field.
func (_u *WorkerUpdate) SetHeartbeatAt(v time.Time) *WorkerUpdate {
	_u.mutation.SetHeartbeatAt(v)
	return _u
}

// SetNillableHeartbeatAt sets the "heartbeat_at" field if the given value is not nil.
func (_u *WorkerUpdate) SetNillableHeartbeatAt(v *time.Time) *WorkerUpdate {
	if v != nil {
		_u.SetHeartbeatAt(*v)
	}
	return _u
}

// ClearHeartbeatAt clears the value of the "heartbeat_at" field.
func (_u *WorkerUpdate) ClearHeartbeatAt() *WorkerUpdate {
	_u.mutation.ClearHeartbeatAt()
	return _u
}

// SetLastError sets the "last_error" field.
func (_u *WorkerUpdate) SetLastError(v string) *WorkerUpdate {
	_u.mutation.SetLastError(v)
	return _u
}

// SetNillableLastError sets the "last_error" field if the given value is not nil.
func (_u *WorkerUpdate) SetNillableLastError(v *string) *WorkerUpdate {
	if v != nil {
		_u.SetLastError(*v)
	}
	return _u
}

// ClearLastError clears the value of the "last_error" field.
func (_u *WorkerUpdate) ClearLastError() *WorkerUpdate {
	_u.mutation.ClearLastError()
	return _u
}

// SetMetadata sets the "metadata" field.
func (_u *WorkerUpdate) SetMetadata(v map[string]interface{}) *WorkerUpdate {
	_u.mutation.SetMetadata(v)
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *WorkerUpdate) SetCreatedAt(v time.Time) *WorkerUpdate {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *WorkerUpdate) SetNillableCreatedAt(v *time.Time) *WorkerUpdate {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *WorkerUpdate) SetUpdatedAt(v time.Time) *WorkerUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the WorkerMutation object of the builder.
func (_u *WorkerUpdate) Mutation() *WorkerMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *WorkerUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *WorkerUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *WorkerUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *WorkerUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *WorkerUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := worker.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

func (_u *WorkerUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(worker.Table, worker.Columns, sqlgraph.NewFieldSpec(worker.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(worker.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Roles(); ok {
		_spec.SetField(worker.FieldRoles, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedRoles(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, worker.FieldRoles, value)
		})
	}
	if value, ok := _u.mutation.Enabled(); ok {
		_spec.SetField(worker.FieldEnabled, field.TypeBool, value)
	}
	if value, ok := _u.mutation.MaxConcurrentJobs(); ok {
		_spec.SetField(worker.FieldMaxConcurrentJobs, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedMaxConcurrentJobs(); ok {
		_spec.AddField(worker.FieldMaxConcurrentJobs, field.TypeInt, value)
	}
	if value, ok := _u.mutation.CredentialHash(); ok {
		_spec.SetField(worker.FieldCredentialHash, field.TypeString, value)
	}
	if _u.mutation.CredentialHashCleared() {
		_spec.ClearField(worker.FieldCredentialHash, field.TypeString)
	}
	if value, ok := _u.mutation.CredentialVersion(); ok {
		_spec.SetField(worker.FieldCredentialVersion, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedCredentialVersion(); ok {
		_spec.AddField(worker.FieldCredentialVersion, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.ProtocolVersion(); ok {
		_spec.SetField(worker.FieldProtocolVersion, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedProtocolVersion(); ok {
		_spec.AddField(worker.FieldProtocolVersion, field.TypeInt, value)
	}
	if value, ok := _u.mutation.WorkerVersion(); ok {
		_spec.SetField(worker.FieldWorkerVersion, field.TypeString, value)
	}
	if _u.mutation.WorkerVersionCleared() {
		_spec.ClearField(worker.FieldWorkerVersion, field.TypeString)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(worker.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.HeartbeatAt(); ok {
		_spec.SetField(worker.FieldHeartbeatAt, field.TypeTime, value)
	}
	if _u.mutation.HeartbeatAtCleared() {
		_spec.ClearField(worker.FieldHeartbeatAt, field.TypeTime)
	}
	if value, ok := _u.mutation.LastError(); ok {
		_spec.SetField(worker.FieldLastError, field.TypeString, value)
	}
	if _u.mutation.LastErrorCleared() {
		_spec.ClearField(worker.FieldLastError, field.TypeString)
	}
	if value, ok := _u.mutation.Metadata(); ok {
		_spec.SetField(worker.FieldMetadata, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(worker.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(worker.FieldUpdatedAt, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{worker.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// WorkerUpdateOne is the builder for updating a single Worker entity.
type WorkerUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *WorkerMutation
}

// SetName sets the "name" field.
func (_u *WorkerUpdateOne) SetName(v string) *WorkerUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *WorkerUpdateOne) SetNillableName(v *string) *WorkerUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetRoles sets the "roles" field.
func (_u *WorkerUpdateOne) SetRoles(v []string) *WorkerUpdateOne {
	_u.mutation.SetRoles(v)
	return _u
}

// AppendRoles appends value to the "roles" field.
func (_u *WorkerUpdateOne) AppendRoles(v []string) *WorkerUpdateOne {
	_u.mutation.AppendRoles(v)
	return _u
}

// SetEnabled sets the "enabled" field.
func (_u *WorkerUpdateOne) SetEnabled(v bool) *WorkerUpdateOne {
	_u.mutation.SetEnabled(v)
	return _u
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_u *WorkerUpdateOne) SetNillableEnabled(v *bool) *WorkerUpdateOne {
	if v != nil {
		_u.SetEnabled(*v)
	}
	return _u
}

// SetMaxConcurrentJobs sets the "max_concurrent_jobs" field.
func (_u *WorkerUpdateOne) SetMaxConcurrentJobs(v int) *WorkerUpdateOne {
	_u.mutation.ResetMaxConcurrentJobs()
	_u.mutation.SetMaxConcurrentJobs(v)
	return _u
}

// SetNillableMaxConcurrentJobs sets the "max_concurrent_jobs" field if the given value is not nil.
func (_u *WorkerUpdateOne) SetNillableMaxConcurrentJobs(v *int) *WorkerUpdateOne {
	if v != nil {
		_u.SetMaxConcurrentJobs(*v)
	}
	return _u
}

// AddMaxConcurrentJobs adds value to the "max_concurrent_jobs" field.
func (_u *WorkerUpdateOne) AddMaxConcurrentJobs(v int) *WorkerUpdateOne {
	_u.mutation.AddMaxConcurrentJobs(v)
	return _u
}

// SetCredentialHash sets the "credential_hash" field.
func (_u *WorkerUpdateOne) SetCredentialHash(v string) *WorkerUpdateOne {
	_u.mutation.SetCredentialHash(v)
	return _u
}

// SetNillableCredentialHash sets the "credential_hash" field if the given value is not nil.
func (_u *WorkerUpdateOne) SetNillableCredentialHash(v *string) *WorkerUpdateOne {
	if v != nil {
		_u.SetCredentialHash(*v)
	}
	return _u
}

// ClearCredentialHash clears the value of the "credential_hash" field.
func (_u *WorkerUpdateOne) ClearCredentialHash() *WorkerUpdateOne {
	_u.mutation.ClearCredentialHash()
	return _u
}

// SetCredentialVersion sets the "credential_version" field.
func (_u *WorkerUpdateOne) SetCredentialVersion(v int64) *WorkerUpdateOne {
	_u.mutation.ResetCredentialVersion()
	_u.mutation.SetCredentialVersion(v)
	return _u
}

// SetNillableCredentialVersion sets the "credential_version" field if the given value is not nil.
func (_u *WorkerUpdateOne) SetNillableCredentialVersion(v *int64) *WorkerUpdateOne {
	if v != nil {
		_u.SetCredentialVersion(*v)
	}
	return _u
}

// AddCredentialVersion adds value to the "credential_version" field.
func (_u *WorkerUpdateOne) AddCredentialVersion(v int64) *WorkerUpdateOne {
	_u.mutation.AddCredentialVersion(v)
	return _u
}

// SetProtocolVersion sets the "protocol_version" field.
func (_u *WorkerUpdateOne) SetProtocolVersion(v int) *WorkerUpdateOne {
	_u.mutation.ResetProtocolVersion()
	_u.mutation.SetProtocolVersion(v)
	return _u
}

// SetNillableProtocolVersion sets the "protocol_version" field if the given value is not nil.
func (_u *WorkerUpdateOne) SetNillableProtocolVersion(v *int) *WorkerUpdateOne {
	if v != nil {
		_u.SetProtocolVersion(*v)
	}
	return _u
}

// AddProtocolVersion adds value to the "protocol_version" field.
func (_u *WorkerUpdateOne) AddProtocolVersion(v int) *WorkerUpdateOne {
	_u.mutation.AddProtocolVersion(v)
	return _u
}

// SetWorkerVersion sets the "worker_version" field.
func (_u *WorkerUpdateOne) SetWorkerVersion(v string) *WorkerUpdateOne {
	_u.mutation.SetWorkerVersion(v)
	return _u
}

// SetNillableWorkerVersion sets the "worker_version" field if the given value is not nil.
func (_u *WorkerUpdateOne) SetNillableWorkerVersion(v *string) *WorkerUpdateOne {
	if v != nil {
		_u.SetWorkerVersion(*v)
	}
	return _u
}

// ClearWorkerVersion clears the value of the "worker_version" field.
func (_u *WorkerUpdateOne) ClearWorkerVersion() *WorkerUpdateOne {
	_u.mutation.ClearWorkerVersion()
	return _u
}

// SetStatus sets the "status" field.
func (_u *WorkerUpdateOne) SetStatus(v string) *WorkerUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *WorkerUpdateOne) SetNillableStatus(v *string) *WorkerUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetHeartbeatAt sets the "heartbeat_at" field.
func (_u *WorkerUpdateOne) SetHeartbeatAt(v time.Time) *WorkerUpdateOne {
	_u.mutation.SetHeartbeatAt(v)
	return _u
}

// SetNillableHeartbeatAt sets the "heartbeat_at" field if the given value is not nil.
func (_u *WorkerUpdateOne) SetNillableHeartbeatAt(v *time.Time) *WorkerUpdateOne {
	if v != nil {
		_u.SetHeartbeatAt(*v)
	}
	return _u
}

// ClearHeartbeatAt clears the value of the "heartbeat_at" field.
func (_u *WorkerUpdateOne) ClearHeartbeatAt() *WorkerUpdateOne {
	_u.mutation.ClearHeartbeatAt()
	return _u
}

// SetLastError sets the "last_error" field.
func (_u *WorkerUpdateOne) SetLastError(v string) *WorkerUpdateOne {
	_u.mutation.SetLastError(v)
	return _u
}

// SetNillableLastError sets the "last_error" field if the given value is not nil.
func (_u *WorkerUpdateOne) SetNillableLastError(v *string) *WorkerUpdateOne {
	if v != nil {
		_u.SetLastError(*v)
	}
	return _u
}

// ClearLastError clears the value of the "last_error" field.
func (_u *WorkerUpdateOne) ClearLastError() *WorkerUpdateOne {
	_u.mutation.ClearLastError()
	return _u
}

// SetMetadata sets the "metadata" field.
func (_u *WorkerUpdateOne) SetMetadata(v map[string]interface{}) *WorkerUpdateOne {
	_u.mutation.SetMetadata(v)
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *WorkerUpdateOne) SetCreatedAt(v time.Time) *WorkerUpdateOne {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *WorkerUpdateOne) SetNillableCreatedAt(v *time.Time) *WorkerUpdateOne {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *WorkerUpdateOne) SetUpdatedAt(v time.Time) *WorkerUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the WorkerMutation object of the builder.
func (_u *WorkerUpdateOne) Mutation() *WorkerMutation {
	return _u.mutation
}

// Where appends a list predicates to the WorkerUpdate builder.
func (_u *WorkerUpdateOne) Where(ps ...predicate.Worker) *WorkerUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *WorkerUpdateOne) Select(field string, fields ...string) *WorkerUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Worker entity.
func (_u *WorkerUpdateOne) Save(ctx context.Context) (*Worker, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *WorkerUpdateOne) SaveX(ctx context.Context) *Worker {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *WorkerUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *WorkerUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *WorkerUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := worker.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

func (_u *WorkerUpdateOne) sqlSave(ctx context.Context) (_node *Worker, err error) {
	_spec := sqlgraph.NewUpdateSpec(worker.Table, worker.Columns, sqlgraph.NewFieldSpec(worker.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Worker.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, worker.FieldID)
		for _, f := range fields {
			if !worker.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != worker.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(worker.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Roles(); ok {
		_spec.SetField(worker.FieldRoles, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedRoles(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, worker.FieldRoles, value)
		})
	}
	if value, ok := _u.mutation.Enabled(); ok {
		_spec.SetField(worker.FieldEnabled, field.TypeBool, value)
	}
	if value, ok := _u.mutation.MaxConcurrentJobs(); ok {
		_spec.SetField(worker.FieldMaxConcurrentJobs, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedMaxConcurrentJobs(); ok {
		_spec.AddField(worker.FieldMaxConcurrentJobs, field.TypeInt, value)
	}
	if value, ok := _u.mutation.CredentialHash(); ok {
		_spec.SetField(worker.FieldCredentialHash, field.TypeString, value)
	}
	if _u.mutation.CredentialHashCleared() {
		_spec.ClearField(worker.FieldCredentialHash, field.TypeString)
	}
	if value, ok := _u.mutation.CredentialVersion(); ok {
		_spec.SetField(worker.FieldCredentialVersion, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedCredentialVersion(); ok {
		_spec.AddField(worker.FieldCredentialVersion, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.ProtocolVersion(); ok {
		_spec.SetField(worker.FieldProtocolVersion, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedProtocolVersion(); ok {
		_spec.AddField(worker.FieldProtocolVersion, field.TypeInt, value)
	}
	if value, ok := _u.mutation.WorkerVersion(); ok {
		_spec.SetField(worker.FieldWorkerVersion, field.TypeString, value)
	}
	if _u.mutation.WorkerVersionCleared() {
		_spec.ClearField(worker.FieldWorkerVersion, field.TypeString)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(worker.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.HeartbeatAt(); ok {
		_spec.SetField(worker.FieldHeartbeatAt, field.TypeTime, value)
	}
	if _u.mutation.HeartbeatAtCleared() {
		_spec.ClearField(worker.FieldHeartbeatAt, field.TypeTime)
	}
	if value, ok := _u.mutation.LastError(); ok {
		_spec.SetField(worker.FieldLastError, field.TypeString, value)
	}
	if _u.mutation.LastErrorCleared() {
		_spec.ClearField(worker.FieldLastError, field.TypeString)
	}
	if value, ok := _u.mutation.Metadata(); ok {
		_spec.SetField(worker.FieldMetadata, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(worker.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(worker.FieldUpdatedAt, field.TypeTime, value)
	}
	_node = &Worker{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{worker.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
