// Code generated by ent, DO NOT EDIT.

package codexturnintent

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the codexturnintent type in the database.
	Label = "codex_turn_intent"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldControlID holds the string denoting the control_id field in the database.
	FieldControlID = "control_id"
	// FieldSequenceNo holds the string denoting the sequence_no field in the database.
	FieldSequenceNo = "sequence_no"
	// FieldOperation holds the string denoting the operation field in the database.
	FieldOperation = "operation"
	// FieldBehavior holds the string denoting the behavior field in the database.
	FieldBehavior = "behavior"
	// FieldResolvedAction holds the string denoting the resolved_action field in the database.
	FieldResolvedAction = "resolved_action"
	// FieldTargetIntentID holds the string denoting the target_intent_id field in the database.
	FieldTargetIntentID = "target_intent_id"
	// FieldSourceType holds the string denoting the source_type field in the database.
	FieldSourceType = "source_type"
	// FieldWorkItemID holds the string denoting the work_item_id field in the database.
	FieldWorkItemID = "work_item_id"
	// FieldDiscordConversationID holds the string denoting the discord_conversation_id field in the database.
	FieldDiscordConversationID = "discord_conversation_id"
	// FieldDiscordMessageID holds the string denoting the discord_message_id field in the database.
	FieldDiscordMessageID = "discord_message_id"
	// FieldRepositoryID holds the string denoting the repository_id field in the database.
	FieldRepositoryID = "repository_id"
	// FieldAgentProfileID holds the string denoting the agent_profile_id field in the database.
	FieldAgentProfileID = "agent_profile_id"
	// FieldWebhookDeliveryID holds the string denoting the webhook_delivery_id field in the database.
	FieldWebhookDeliveryID = "webhook_delivery_id"
	// FieldIdempotencyKey holds the string denoting the idempotency_key field in the database.
	FieldIdempotencyKey = "idempotency_key"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldInstruction holds the string denoting the instruction field in the database.
	FieldInstruction = "instruction"
	// FieldPreparedInput holds the string denoting the prepared_input field in the database.
	FieldPreparedInput = "prepared_input"
	// FieldSkills holds the string denoting the skills field in the database.
	FieldSkills = "skills"
	// FieldAllowedTools holds the string denoting the allowed_tools field in the database.
	FieldAllowedTools = "allowed_tools"
	// FieldDangerousActions holds the string denoting the dangerous_actions field in the database.
	FieldDangerousActions = "dangerous_actions"
	// FieldTriggerRuleID holds the string denoting the trigger_rule_id field in the database.
	FieldTriggerRuleID = "trigger_rule_id"
	// FieldTriggerEvidence holds the string denoting the trigger_evidence field in the database.
	FieldTriggerEvidence = "trigger_evidence"
	// FieldActorLogin holds the string denoting the actor_login field in the database.
	FieldActorLogin = "actor_login"
	// FieldActorPermission holds the string denoting the actor_permission field in the database.
	FieldActorPermission = "actor_permission"
	// FieldPriority holds the string denoting the priority field in the database.
	FieldPriority = "priority"
	// FieldSteerable holds the string denoting the steerable field in the database.
	FieldSteerable = "steerable"
	// FieldAvailableAt holds the string denoting the available_at field in the database.
	FieldAvailableAt = "available_at"
	// FieldAttemptCount holds the string denoting the attempt_count field in the database.
	FieldAttemptCount = "attempt_count"
	// FieldMaxAttempts holds the string denoting the max_attempts field in the database.
	FieldMaxAttempts = "max_attempts"
	// FieldCodexSubmissionID holds the string denoting the codex_submission_id field in the database.
	FieldCodexSubmissionID = "codex_submission_id"
	// FieldConfirmedCodexTurnID holds the string denoting the confirmed_codex_turn_id field in the database.
	FieldConfirmedCodexTurnID = "confirmed_codex_turn_id"
	// FieldLastErrorCode holds the string denoting the last_error_code field in the database.
	FieldLastErrorCode = "last_error_code"
	// FieldLastErrorMessage holds the string denoting the last_error_message field in the database.
	FieldLastErrorMessage = "last_error_message"
	// FieldResult holds the string denoting the result field in the database.
	FieldResult = "result"
	// FieldResultDeliveryStatus holds the string denoting the result_delivery_status field in the database.
	FieldResultDeliveryStatus = "result_delivery_status"
	// FieldResultDeliveryAttemptCount holds the string denoting the result_delivery_attempt_count field in the database.
	FieldResultDeliveryAttemptCount = "result_delivery_attempt_count"
	// FieldResultDeliveryError holds the string denoting the result_delivery_error field in the database.
	FieldResultDeliveryError = "result_delivery_error"
	// FieldResultDeliveryToken holds the string denoting the result_delivery_token field in the database.
	FieldResultDeliveryToken = "result_delivery_token"
	// FieldResultDeliveryAvailableAt holds the string denoting the result_delivery_available_at field in the database.
	FieldResultDeliveryAvailableAt = "result_delivery_available_at"
	// FieldReplyPolicy holds the string denoting the reply_policy field in the database.
	FieldReplyPolicy = "reply_policy"
	// FieldReplyStatus holds the string denoting the reply_status field in the database.
	FieldReplyStatus = "reply_status"
	// FieldReplyHookBlockCount holds the string denoting the reply_hook_block_count field in the database.
	FieldReplyHookBlockCount = "reply_hook_block_count"
	// FieldReplyToolCallID holds the string denoting the reply_tool_call_id field in the database.
	FieldReplyToolCallID = "reply_tool_call_id"
	// FieldGithubCommentID holds the string denoting the github_comment_id field in the database.
	FieldGithubCommentID = "github_comment_id"
	// FieldGithubCommentURL holds the string denoting the github_comment_url field in the database.
	FieldGithubCommentURL = "github_comment_url"
	// FieldDispatchedAt holds the string denoting the dispatched_at field in the database.
	FieldDispatchedAt = "dispatched_at"
	// FieldConfirmedAt holds the string denoting the confirmed_at field in the database.
	FieldConfirmedAt = "confirmed_at"
	// FieldFinishedAt holds the string denoting the finished_at field in the database.
	FieldFinishedAt = "finished_at"
	// FieldResultDeliveredAt holds the string denoting the result_delivered_at field in the database.
	FieldResultDeliveredAt = "result_delivered_at"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// Table holds the table name of the codexturnintent in the database.
	Table = "codex_turn_intents"
)

// Columns holds all SQL columns for codexturnintent fields.
var Columns = []string{
	FieldID,
	FieldControlID,
	FieldSequenceNo,
	FieldOperation,
	FieldBehavior,
	FieldResolvedAction,
	FieldTargetIntentID,
	FieldSourceType,
	FieldWorkItemID,
	FieldDiscordConversationID,
	FieldDiscordMessageID,
	FieldRepositoryID,
	FieldAgentProfileID,
	FieldWebhookDeliveryID,
	FieldIdempotencyKey,
	FieldStatus,
	FieldInstruction,
	FieldPreparedInput,
	FieldSkills,
	FieldAllowedTools,
	FieldDangerousActions,
	FieldTriggerRuleID,
	FieldTriggerEvidence,
	FieldActorLogin,
	FieldActorPermission,
	FieldPriority,
	FieldSteerable,
	FieldAvailableAt,
	FieldAttemptCount,
	FieldMaxAttempts,
	FieldCodexSubmissionID,
	FieldConfirmedCodexTurnID,
	FieldLastErrorCode,
	FieldLastErrorMessage,
	FieldResult,
	FieldResultDeliveryStatus,
	FieldResultDeliveryAttemptCount,
	FieldResultDeliveryError,
	FieldResultDeliveryToken,
	FieldResultDeliveryAvailableAt,
	FieldReplyPolicy,
	FieldReplyStatus,
	FieldReplyHookBlockCount,
	FieldReplyToolCallID,
	FieldGithubCommentID,
	FieldGithubCommentURL,
	FieldDispatchedAt,
	FieldConfirmedAt,
	FieldFinishedAt,
	FieldResultDeliveredAt,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultOperation holds the default value on creation for the "operation" field.
	DefaultOperation string
	// DefaultStatus holds the default value on creation for the "status" field.
	DefaultStatus string
	// DefaultSkills holds the default value on creation for the "skills" field.
	DefaultSkills []string
	// DefaultAllowedTools holds the default value on creation for the "allowed_tools" field.
	DefaultAllowedTools []string
	// DefaultDangerousActions holds the default value on creation for the "dangerous_actions" field.
	DefaultDangerousActions []string
	// DefaultTriggerEvidence holds the default value on creation for the "trigger_evidence" field.
	DefaultTriggerEvidence map[string]interface{}
	// DefaultActorLogin holds the default value on creation for the "actor_login" field.
	DefaultActorLogin string
	// DefaultActorPermission holds the default value on creation for the "actor_permission" field.
	DefaultActorPermission string
	// DefaultPriority holds the default value on creation for the "priority" field.
	DefaultPriority int
	// DefaultSteerable holds the default value on creation for the "steerable" field.
	DefaultSteerable bool
	// DefaultAvailableAt holds the default value on creation for the "available_at" field.
	DefaultAvailableAt func() time.Time
	// DefaultAttemptCount holds the default value on creation for the "attempt_count" field.
	DefaultAttemptCount int
	// DefaultMaxAttempts holds the default value on creation for the "max_attempts" field.
	DefaultMaxAttempts int
	// DefaultResultDeliveryStatus holds the default value on creation for the "result_delivery_status" field.
	DefaultResultDeliveryStatus string
	// DefaultResultDeliveryAttemptCount holds the default value on creation for the "result_delivery_attempt_count" field.
	DefaultResultDeliveryAttemptCount int
	// DefaultReplyPolicy holds the default value on creation for the "reply_policy" field.
	DefaultReplyPolicy string
	// DefaultReplyStatus holds the default value on creation for the "reply_status" field.
	DefaultReplyStatus string
	// DefaultReplyHookBlockCount holds the default value on creation for the "reply_hook_block_count" field.
	DefaultReplyHookBlockCount int
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)

// OrderOption defines the ordering options for the CodexTurnIntent queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByControlID orders the results by the control_id field.
func ByControlID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldControlID, opts...).ToFunc()
}

// BySequenceNo orders the results by the sequence_no field.
func BySequenceNo(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSequenceNo, opts...).ToFunc()
}

// ByOperation orders the results by the operation field.
func ByOperation(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldOperation, opts...).ToFunc()
}

// ByBehavior orders the results by the behavior field.
func ByBehavior(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBehavior, opts...).ToFunc()
}

// ByResolvedAction orders the results by the resolved_action field.
func ByResolvedAction(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldResolvedAction, opts...).ToFunc()
}

// ByTargetIntentID orders the results by the target_intent_id field.
func ByTargetIntentID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTargetIntentID, opts...).ToFunc()
}

// BySourceType orders the results by the source_type field.
func BySourceType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSourceType, opts...).ToFunc()
}

// ByWorkItemID orders the results by the work_item_id field.
func ByWorkItemID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldWorkItemID, opts...).ToFunc()
}

// ByDiscordConversationID orders the results by the discord_conversation_id field.
func ByDiscordConversationID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDiscordConversationID, opts...).ToFunc()
}

// ByDiscordMessageID orders the results by the discord_message_id field.
func ByDiscordMessageID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDiscordMessageID, opts...).ToFunc()
}

// ByRepositoryID orders the results by the repository_id field.
func ByRepositoryID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRepositoryID, opts...).ToFunc()
}

// ByAgentProfileID orders the results by the agent_profile_id field.
func ByAgentProfileID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAgentProfileID, opts...).ToFunc()
}

// ByWebhookDeliveryID orders the results by the webhook_delivery_id field.
func ByWebhookDeliveryID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldWebhookDeliveryID, opts...).ToFunc()
}

// ByIdempotencyKey orders the results by the idempotency_key field.
func ByIdempotencyKey(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldIdempotencyKey, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// ByInstruction orders the results by the instruction field.
func ByInstruction(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldInstruction, opts...).ToFunc()
}

// ByTriggerRuleID orders the results by the trigger_rule_id field.
func ByTriggerRuleID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTriggerRuleID, opts...).ToFunc()
}

// ByActorLogin orders the results by the actor_login field.
func ByActorLogin(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldActorLogin, opts...).ToFunc()
}

// ByActorPermission orders the results by the actor_permission field.
func ByActorPermission(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldActorPermission, opts...).ToFunc()
}

// ByPriority orders the results by the priority field.
func ByPriority(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPriority, opts...).ToFunc()
}

// BySteerable orders the results by the steerable field.
func BySteerable(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSteerable, opts...).ToFunc()
}

// ByAvailableAt orders the results by the available_at field.
func ByAvailableAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAvailableAt, opts...).ToFunc()
}

// ByAttemptCount orders the results by the attempt_count field.
func ByAttemptCount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAttemptCount, opts...).ToFunc()
}

// ByMaxAttempts orders the results by the max_attempts field.
func ByMaxAttempts(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMaxAttempts, opts...).ToFunc()
}

// ByCodexSubmissionID orders the results by the codex_submission_id field.
func ByCodexSubmissionID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCodexSubmissionID, opts...).ToFunc()
}

// ByConfirmedCodexTurnID orders the results by the confirmed_codex_turn_id field.
func ByConfirmedCodexTurnID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldConfirmedCodexTurnID, opts...).ToFunc()
}

// ByLastErrorCode orders the results by the last_error_code field.
func ByLastErrorCode(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLastErrorCode, opts...).ToFunc()
}

// ByLastErrorMessage orders the results by the last_error_message field.
func ByLastErrorMessage(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLastErrorMessage, opts...).ToFunc()
}

// ByResultDeliveryStatus orders the results by the result_delivery_status field.
func ByResultDeliveryStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldResultDeliveryStatus, opts...).ToFunc()
}

// ByResultDeliveryAttemptCount orders the results by the result_delivery_attempt_count field.
func ByResultDeliveryAttemptCount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldResultDeliveryAttemptCount, opts...).ToFunc()
}

// ByResultDeliveryError orders the results by the result_delivery_error field.
func ByResultDeliveryError(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldResultDeliveryError, opts...).ToFunc()
}

// ByResultDeliveryToken orders the results by the result_delivery_token field.
func ByResultDeliveryToken(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldResultDeliveryToken, opts...).ToFunc()
}

// ByResultDeliveryAvailableAt orders the results by the result_delivery_available_at field.
func ByResultDeliveryAvailableAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldResultDeliveryAvailableAt, opts...).ToFunc()
}

// ByReplyPolicy orders the results by the reply_policy field.
func ByReplyPolicy(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldReplyPolicy, opts...).ToFunc()
}

// ByReplyStatus orders the results by the reply_status field.
func ByReplyStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldReplyStatus, opts...).ToFunc()
}

// ByReplyHookBlockCount orders the results by the reply_hook_block_count field.
func ByReplyHookBlockCount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldReplyHookBlockCount, opts...).ToFunc()
}

// ByReplyToolCallID orders the results by the reply_tool_call_id field.
func ByReplyToolCallID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldReplyToolCallID, opts...).ToFunc()
}

// ByGithubCommentID orders the results by the github_comment_id field.
func ByGithubCommentID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldGithubCommentID, opts...).ToFunc()
}

// ByGithubCommentURL orders the results by the github_comment_url field.
func ByGithubCommentURL(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldGithubCommentURL, opts...).ToFunc()
}

// ByDispatchedAt orders the results by the dispatched_at field.
func ByDispatchedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDispatchedAt, opts...).ToFunc()
}

// ByConfirmedAt orders the results by the confirmed_at field.
func ByConfirmedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldConfirmedAt, opts...).ToFunc()
}

// ByFinishedAt orders the results by the finished_at field.
func ByFinishedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFinishedAt, opts...).ToFunc()
}

// ByResultDeliveredAt orders the results by the result_delivered_at field.
func ByResultDeliveredAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldResultDeliveredAt, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}
