// Code generated by ent, DO NOT EDIT.

package workerenrollment

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
	"github.com/slovx2/tyrs-hand/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.WorkerEnrollment {
	return predicate.WorkerEnrollment(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.WorkerEnrollment {
	return predicate.WorkerEnrollment(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.WorkerEnrollment {
	return predicate.WorkerEnrollment(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.WorkerEnrollment {
	return predicate.WorkerEnrollment(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.WorkerEnrollment {
	return predicate.WorkerEnrollment(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.WorkerEnrollment {
	return predicate.WorkerEnrollment(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.WorkerEnrollment {
	return predicate.WorkerEnrollment(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.WorkerEnrollment {
	return predicate.WorkerEnrollment(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.WorkerEnrollment {
	return predicate.WorkerEnrollment(sql.FieldLTE(FieldID, id))
}

// WorkerID applies equality check predicate on the "worker_id" field. It's identical to WorkerIDEQ.
func WorkerID(v uuid.UUID) predicate.WorkerEnrollment {
	return predicate.WorkerEnrollment(sql.FieldEQ(FieldWorkerID, v))
}

// TokenHash applies equality check predicate on the "token_hash" field. It's identical to TokenHashEQ.
func TokenHash(v string) predicate.WorkerEnrollment {
	return predicate.WorkerEnrollment(sql.FieldEQ(FieldTokenHash, v))
}

// ExpiresAt applies equality check predicate on the "expires_at" field. It's identical to ExpiresAtEQ.
func ExpiresAt(v time.Time) predicate.WorkerEnrollment {
	return predicate.WorkerEnrollment(sql.FieldEQ(FieldExpiresAt, v))
}

// ConsumedAt applies equality check predicate on the "consumed_at" field. It's identical to ConsumedAtEQ.
func ConsumedAt(v time.Time) predicate.WorkerEnrollment {
	return predicate.WorkerEnrollment(sql.FieldEQ(FieldConsumedAt, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.WorkerEnrollment {
	return predicate.WorkerEnrollment(sql.FieldEQ(FieldCreatedAt, v))
}

// WorkerIDEQ applies the EQ predicate on the "worker_id" field.
func WorkerIDEQ(v uuid.UUID) predicate.WorkerEnrollment {
	return predicate.WorkerEnrollment(sql.FieldEQ(FieldWorkerID, v))
}

// WorkerIDNEQ applies the NEQ predicate on the "worker_id" field.
func WorkerIDNEQ(v uuid.UUID) predicate.WorkerEnrollment {
	return predicate.WorkerEnrollment(sql.FieldNEQ(FieldWorkerID, v))
}

// WorkerIDIn applies the In predicate on the "worker_id" field.
func WorkerIDIn(vs ...uuid.UUID) predicate.WorkerEnrollment {
	return predicate.WorkerEnrollment(sql.FieldIn(FieldWorkerID, vs...))
}

// WorkerIDNotIn applies the NotIn predicate on the "worker_id" field.
func WorkerIDNotIn(vs ...uuid.UUID) predicate.WorkerEnrollment {
	return predicate.WorkerEnrollment(sql.FieldNotIn(FieldWorkerID, vs...))
}

// WorkerIDGT applies the GT predicate on the "worker_id" field.
func WorkerIDGT(v uuid.UUID) predicate.WorkerEnrollment {
	return predicate.WorkerEnrollment(sql.FieldGT(FieldWorkerID, v))
}

// WorkerIDGTE applies the GTE predicate on the "worker_id" field.
func WorkerIDGTE(v uuid.UUID) predicate.WorkerEnrollment {
	return predicate.WorkerEnrollment(sql.FieldGTE(FieldWorkerID, v))
}

// WorkerIDLT applies the LT predicate on the "worker_id" field.
func WorkerIDLT(v uuid.UUID) predicate.WorkerEnrollment {
	return predicate.WorkerEnrollment(sql.FieldLT(FieldWorkerID, v))
}

// WorkerIDLTE applies the LTE predicate on the "worker_id" field.
func WorkerIDLTE(v uuid.UUID) predicate.WorkerEnrollment {
	return predicate.WorkerEnrollment(sql.FieldLTE(FieldWorkerID, v))
}

// TokenHashEQ applies the EQ predicate on the "token_hash" field.
func TokenHashEQ(v string) predicate.WorkerEnrollment {
	return predicate.WorkerEnrollment(sql.FieldEQ(FieldTokenHash, v))
}

// TokenHashNEQ applies the NEQ predicate on the "token_hash" field.
func TokenHashNEQ(v string) predicate.WorkerEnrollment {
	return predicate.WorkerEnrollment(sql.FieldNEQ(FieldTokenHash, v))
}

// TokenHashIn applies the In predicate on the "token_hash" field.
func TokenHashIn(vs ...string) predicate.WorkerEnrollment {
	return predicate.WorkerEnrollment(sql.FieldIn(FieldTokenHash, vs...))
}

// TokenHashNotIn applies the NotIn predicate on the "token_hash" field.
func TokenHashNotIn(vs ...string) predicate.WorkerEnrollment {
	return predicate.WorkerEnrollment(sql.FieldNotIn(FieldTokenHash, vs...))
}

// TokenHashGT applies the GT predicate on the "token_hash" field.
func TokenHashGT(v string) predicate.WorkerEnrollment {
	return predicate.WorkerEnrollment(sql.FieldGT(FieldTokenHash, v))
}

// TokenHashGTE applies the GTE predicate on the "token_hash" field.
func TokenHashGTE(v string) predicate.WorkerEnrollment {
	return predicate.WorkerEnrollment(sql.FieldGTE(FieldTokenHash, v))
}

// TokenHashLT applies the LT predicate on the "token_hash" field.
func TokenHashLT(v string) predicate.WorkerEnrollment {
	return predicate.WorkerEnrollment(sql.FieldLT(FieldTokenHash, v))
}

// TokenHashLTE applies the LTE predicate on the "token_hash" field.
func TokenHashLTE(v string) predicate.WorkerEnrollment {
	return predicate.WorkerEnrollment(sql.FieldLTE(FieldTokenHash, v))
}

// TokenHashContains applies the Contains predicate on the "token_hash" field.
func TokenHashContains(v string) predicate.WorkerEnrollment {
	return predicate.WorkerEnrollment(sql.FieldContains(FieldTokenHash, v))
}

// TokenHashHasPrefix applies the HasPrefix predicate on the "token_hash" field.
func TokenHashHasPrefix(v string) predicate.WorkerEnrollment {
	return predicate.WorkerEnrollment(sql.FieldHasPrefix(FieldTokenHash, v))
}

// TokenHashHasSuffix applies the HasSuffix predicate on the "token_hash" field.
func TokenHashHasSuffix(v string) predicate.WorkerEnrollment {
	return predicate.WorkerEnrollment(sql.FieldHasSuffix(FieldTokenHash, v))
}

// TokenHashEqualFold applies the EqualFold predicate on the "token_hash" field.
func TokenHashEqualFold(v string) predicate.WorkerEnrollment {
	return predicate.WorkerEnrollment(sql.FieldEqualFold(FieldTokenHash, v))
}

// TokenHashContainsFold applies the ContainsFold predicate on the "token_hash" field.
func TokenHashContainsFold(v string) predicate.WorkerEnrollment {
	return predicate.WorkerEnrollment(sql.FieldContainsFold(FieldTokenHash, v))
}

// ExpiresAtEQ applies the EQ predicate on the "expires_at" field.
func ExpiresAtEQ(v time.Time) predicate.WorkerEnrollment {
	return predicate.WorkerEnrollment(sql.FieldEQ(FieldExpiresAt, v))
}

// ExpiresAtNEQ applies the NEQ predicate on the "expires_at" field.
func ExpiresAtNEQ(v time.Time) predicate.WorkerEnrollment {
	return predicate.WorkerEnrollment(sql.FieldNEQ(FieldExpiresAt, v))
}

// ExpiresAtIn applies the In predicate on the "expires_at" field.
func ExpiresAtIn(vs ...time.Time) predicate.WorkerEnrollment {
	return predicate.WorkerEnrollment(sql.FieldIn(FieldExpiresAt, vs...))
}

// ExpiresAtNotIn applies the NotIn predicate on the "expires_at" field.
func ExpiresAtNotIn(vs ...time.Time) predicate.WorkerEnrollment {
	return predicate.WorkerEnrollment(sql.FieldNotIn(FieldExpiresAt, vs...))
}

// ExpiresAtGT applies the GT predicate on the "expires_at" field.
func ExpiresAtGT(v time.Time) predicate.WorkerEnrollment {
	return predicate.WorkerEnrollment(sql.FieldGT(FieldExpiresAt, v))
}

// ExpiresAtGTE applies the GTE predicate on the "expires_at" field.
func ExpiresAtGTE(v time.Time) predicate.WorkerEnrollment {
	return predicate.WorkerEnrollment(sql.FieldGTE(FieldExpiresAt, v))
}

// ExpiresAtLT applies the LT predicate on the "expires_at" field.
func ExpiresAtLT(v time.Time) predicate.WorkerEnrollment {
	return predicate.WorkerEnrollment(sql.FieldLT(FieldExpiresAt, v))
}

// ExpiresAtLTE applies the LTE predicate on the "expires_at" field.
func ExpiresAtLTE(v time.Time) predicate.WorkerEnrollment {
	return predicate.WorkerEnrollment(sql.FieldLTE(FieldExpiresAt, v))
}

// ConsumedAtEQ applies the EQ predicate on the "consumed_at" field.
func ConsumedAtEQ(v time.Time) predicate.WorkerEnrollment {
	return predicate.WorkerEnrollment(sql.FieldEQ(FieldConsumedAt, v))
}

// ConsumedAtNEQ applies the NEQ predicate on the "consumed_at" field.
func ConsumedAtNEQ(v time.Time) predicate.WorkerEnrollment {
	return predicate.WorkerEnrollment(sql.FieldNEQ(FieldConsumedAt, v))
}

// ConsumedAtIn applies the In predicate on the "consumed_at" field.
func ConsumedAtIn(vs ...time.Time) predicate.WorkerEnrollment {
	return predicate.WorkerEnrollment(sql.FieldIn(FieldConsumedAt, vs...))
}

// ConsumedAtNotIn applies the NotIn predicate on the "consumed_at" field.
func ConsumedAtNotIn(vs ...time.Time) predicate.WorkerEnrollment {
	return predicate.WorkerEnrollment(sql.FieldNotIn(FieldConsumedAt, vs...))
}

// ConsumedAtGT applies the GT predicate on the "consumed_at" field.
func ConsumedAtGT(v time.Time) predicate.WorkerEnrollment {
	return predicate.WorkerEnrollment(sql.FieldGT(FieldConsumedAt, v))
}

// ConsumedAtGTE applies the GTE predicate on the "consumed_at" field.
func ConsumedAtGTE(v time.Time) predicate.WorkerEnrollment {
	return predicate.WorkerEnrollment(sql.FieldGTE(FieldConsumedAt, v))
}

// ConsumedAtLT applies the LT predicate on the "consumed_at" field.
func ConsumedAtLT(v time.Time) predicate.WorkerEnrollment {
	return predicate.WorkerEnrollment(sql.FieldLT(FieldConsumedAt, v))
}

// ConsumedAtLTE applies the LTE predicate on the "consumed_at" field.
func ConsumedAtLTE(v time.Time) predicate.WorkerEnrollment {
	return predicate.WorkerEnrollment(sql.FieldLTE(FieldConsumedAt, v))
}

// ConsumedAtIsNil applies the IsNil predicate on the "consumed_at" field.
func ConsumedAtIsNil() predicate.WorkerEnrollment {
	return predicate.WorkerEnrollment(sql.FieldIsNull(FieldConsumedAt))
}

// ConsumedAtNotNil applies the NotNil predicate on the "consumed_at" field.
func ConsumedAtNotNil() predicate.WorkerEnrollment {
	return predicate.WorkerEnrollment(sql.FieldNotNull(FieldConsumedAt))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.WorkerEnrollment {
	return predicate.WorkerEnrollment(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.WorkerEnrollment {
	return predicate.WorkerEnrollment(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.WorkerEnrollment {
	return predicate.WorkerEnrollment(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.WorkerEnrollment {
	return predicate.WorkerEnrollment(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.WorkerEnrollment {
	return predicate.WorkerEnrollment(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.WorkerEnrollment {
	return predicate.WorkerEnrollment(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.WorkerEnrollment {
	return predicate.WorkerEnrollment(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.WorkerEnrollment {
	return predicate.WorkerEnrollment(sql.FieldLTE(FieldCreatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.WorkerEnrollment) predicate.WorkerEnrollment {
	return predicate.WorkerEnrollment(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.WorkerEnrollment) predicate.WorkerEnrollment {
	return predicate.WorkerEnrollment(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.WorkerEnrollment) predicate.WorkerEnrollment {
	return predicate.WorkerEnrollment(sql.NotPredicates(p))
}
